//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.FinCare.Contracts.Enums;

namespace RMA.Service.FinCare.Database.Entities
{
    public partial class billing_CollectionBatch : ILazyLoadSafeEntity
    {
        public int CollectionBatchId { get; set; } // CollectionBatchId (Primary key)
        public System.DateTime CreatedDate { get; set; } // CreatedDate
        public string Reference { get; set; } // Reference (length: 250)

        // Reverse navigation

        /// <summary>
        /// Child billing_Collections where [Collections].[CollectionBatchId] point to this entity (FK_Collections_CollectionBatch)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<billing_Collection> Collections { get; set; } // Collections.FK_Collections_CollectionBatch

        public billing_CollectionBatch()
        {
            Collections = new System.Collections.Generic.List<billing_Collection>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
