//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.FinCare.Contracts.Enums;

namespace RMA.Service.FinCare.Database.Entities
{
    public partial class commission_CommisionPaymentBatch : ILazyLoadSafeEntity
    {
        public int Id { get; set; } // ID (Primary key)
        public System.DateTime BatchCreateDate { get; set; } // BatchCreateDate
        public int BatchStatus { get; set; } // BatchStatus
        public int BrokerId { get; set; } // BrokerID
        public int PolicyCount { get; set; } // PolicyCount
        public decimal BatchTotal { get; set; } // BatchTotal

        public commission_CommisionPaymentBatch()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
