//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.FinCare.Contracts.Enums;

namespace RMA.Service.FinCare.Database.Entities
{
    public partial class Load_MyValuePlusBenefit : ILazyLoadSafeEntity
    {
        public System.Guid FileIdentifier { get; set; } // FileIdentifier (Primary key)
        public string ProductOptionName { get; set; } // ProductOptionName (Primary key) (length: 128)
        public string BenefitName { get; set; } // BenefitName (Primary key) (length: 128)
        public string BenefitNameOriginal { get; set; } // BenefitName_Original (length: 128)
        public int? ProductOptionId { get; set; } // ProductOptionId
        public int? BenefitId { get; set; } // BenefitId
        public CoverMemberTypeEnum? CoverMemberType { get; set; } // CoverMemberTypeId
        public int? MaxPersonsPerProductOption { get; set; } // MaxPersonsPerProductOption
        public int? MaxPersonsPerBenefit { get; set; } // MaxPersonsPerBenefit
        public int? MinEntryAge { get; set; } // MinEntryAge
        public int? MaxEntryAge { get; set; } // MaxEntryAge
        public decimal? CapCover { get; set; } // CapCover

        public Load_MyValuePlusBenefit()
        {
            MaxPersonsPerProductOption = 999;
            MaxPersonsPerBenefit = 999;
            MinEntryAge = 0;
            MaxEntryAge = 999;
            CapCover = 104000m;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
