//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.FinCare.Contracts.Enums;

namespace RMA.Service.FinCare.Database.Entities
{
    public partial class Load_PostRetirementMedicalAidData : ILazyLoadSafeEntity
    {
        public int HarmonyDataId { get; set; } // HarmonyDataId (Primary key)
        public int? PolicyId { get; set; } // PolicyId
        public string PolicyNumber { get; set; } // PolicyNumber (length: 50)
        public string EmployeeNumber { get; set; } // EmployeeNumber (length: 50)
        public string EmployeeSurname { get; set; } // EmployeeSurname (length: 50)
        public string EmployeeInitials { get; set; } // EmployeeInitials (length: 50)
        public string PromiseRule { get; set; } // PromiseRule (length: 50)
        public string Status { get; set; } // Status (length: 50)
        public string DateJoinedGroup { get; set; } // DateJoinedGroup (length: 50)
        public string IdNumber { get; set; } // IdNumber (length: 50)
        public string DateOfBirth { get; set; } // DateOfBirth (length: 50)
        public string Gender { get; set; } // Gender (length: 50)
        public string Age { get; set; } // Age (length: 50)
        public string MedicalDependentMedicalAidFamilyIndicator { get; set; } // MedicalDependentMedicalAidFamilyIndicator (length: 50)
        public string MedicalScheme { get; set; } // MedicalScheme (length: 50)
        public string MedicalRegistration { get; set; } // MedicalRegistration (length: 50)
        public string MembershipNo { get; set; } // MembershipNo (length: 50)
        public string MedicalOptionPlanType { get; set; } // MedicalOptionPlanType (length: 50)
        public string RetiredIndicator { get; set; } // RetiredIndicator (length: 50)
        public string YearsInService { get; set; } // YearsInService (length: 50)
        public string DateOfTermination { get; set; } // DateOfTermination (length: 50)
        public string PromiseIndicator { get; set; } // PromiseIndicator (length: 50)
        public string BenefitPercentageIncrease { get; set; } // BenefitPercentageIncrease (length: 50)
        public string NextIncreaseDateLastIncreaseDate { get; set; } // NextIncreaseDateLastIncreaseDate (length: 50)
        public string BenefitEntitlementPercentage { get; set; } // BenefitEntitlementPercentage (length: 50)
        public string CompanyContribution { get; set; } // CompanyContribution (length: 50)
        public string MemberContribution { get; set; } // MemberContribution (length: 50)
        public string TotalContributionDue { get; set; } // TotalContributionDue (length: 50)
        public string SpouseNames { get; set; } // SpouseNames (length: 50)
        public string SpouseId { get; set; } // SpouseId (length: 50)
        public string SpouseDateOfBirth { get; set; } // SpouseDateOfBirth (length: 50)
        public string SpouseGender { get; set; } // SpouseGender (length: 50)
        public string ChildOne { get; set; } // ChildOne (length: 50)
        public string ChildOneId { get; set; } // ChildOneId (length: 50)
        public string ChildDateOfDate { get; set; } // ChildDateOfDate (length: 50)
        public string ChildOneGender { get; set; } // ChildOneGender (length: 50)
        public string ChildTwo { get; set; } // ChildTwo (length: 50)
        public string ChildTwoId { get; set; } // ChildTwoId (length: 50)
        public string ChildTwoDateOfBirth { get; set; } // ChildTwoDateOfBirth (length: 50)
        public string ChildTwoGender { get; set; } // ChildTwoGender (length: 50)
        public string ChildThree { get; set; } // ChildThree (length: 50)
        public string ChildThreeId { get; set; } // ChildThreeId (length: 50)
        public string ChildThreeDateOfBirth { get; set; } // ChildThreeDateOfBirth (length: 50)
        public string ChildThreeGender { get; set; } // ChildThreeGender (length: 50)
        public string AdultOneDependent { get; set; } // AdultOneDependent (length: 50)
        public string AdultOneId { get; set; } // AdultOneId (length: 50)
        public string AdultOneDateOfBirth { get; set; } // AdultOneDateOfBirth (length: 50)
        public string AdultOneGender { get; set; } // AdultOneGender (length: 50)
        public string AdultTwoDependent { get; set; } // AdultTwoDependent (length: 50)
        public string AdultTwoId { get; set; } // AdultTwoId (length: 50)
        public string AdultTwoDateOfBirth { get; set; } // AdultTwoDateOfBirth (length: 50)
        public string AdultTwoGender { get; set; } // AdultTwoGender (length: 50)

        public Load_PostRetirementMedicalAidData()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
