//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.FinCare.Contracts.Enums;

namespace RMA.Service.FinCare.Database.Entities
{
    public partial class payment_LastViewed : ILazyLoadSafeEntity
    {
        public int Id { get; set; } // Id (Primary key)
        public int ItemId { get; set; } // ItemId
        public string ItemType { get; set; } // ItemType (length: 50)
        public string User { get; set; } // User (length: 50)
        public System.DateTime Date { get; set; } // Date

        public payment_LastViewed()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
