

CREATE PROCEDURE [claim].[GLPostingReport]
	@StartDate As Date,
	@EndDate AS Date
	
AS
	BEGIN

	
--	SELECT DISTINCT 
--REFERENCE, 
--TRANSACTIONDATE AS 'Transaction Date', 
--'' AS 'NO. OF TRANSACTIONS',
--COMPANYNO  as COMPANY,
--BRANCHNO AS BRANCH, 
--LEVEL1 AS PRODUCT,
--LEVEL2 AS 'COST CENTRE', 
--CHARTISNO AS 'IS CHART NO',
--TRANSACTIONTYPE AS 'IS CHART NAME',
--CHARTBSNO AS 'BS CHART NO',
--TRANSACTIONTYPE AS 'BS CHART NAME', 
--CASE WHEN ISPROCESSED = 1 THEN 'YES' ELSE 'NO' END AS PROCESSED,
--DAILYTOTAL AS DAILYTOTAL 
--FROM finance.AbilityPosting 
--where convert(date,TRANSACTIONDATE) between @StartDate and @EndDate

----
	
--SELECT DISTINCT TOP 0
--REFERENCE, 
--TRANSACTIONDATE, 
--0 AS 'NO. OF TRANSACTIONS',
--COMPANYNO,
--BRANCHNO, 
--LEVEL1,
--LEVEL2, 
--CHARTISNO,
--TRANSACTIONTYPE AS CHARTISNAME,
--CHARTBSNO,
--TRANSACTIONTYPE AS CHARTBSNAME,
-- ISPROCESSED,
--DAILYTOTAL AS DAILYTOTAL 
--INTO finance.AbilityPosting2
--FROM finance.AbilityPosting 
----

SELECT DISTINCT 
REFERENCE,TRANSACTIONDATE,[NO. OF TRANSACTIONS],COMPANYNO as COMPANY
,BRANCHNO as BRANCH
,LEVEL1 as PRODUCT
,LEVEL2  AS 'COST CENTRE'
,CHARTISNO AS 'IS CHART NO'
,CHARTISNAME AS 'IS CHART NAME'
,CHARTBSNO AS 'BS CHART NO' 
,CHARTBSNAME AS 'BS CHART NAME'
,ISPROCESSED as PROCESSED
,DAILYTOTAL as DAILYTOTAL
FROM finance.AbilityPosting2
where convert(date,TRANSACTIONDATE) between @StartDate and @EndDate

		END