//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.ClientCare.Database.Entities;

namespace RMA.Service.ClientCare.Database.Configuration
{
    public class broker_FscaLicenseCategoryConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<broker_FscaLicenseCategory>
    {
        public broker_FscaLicenseCategoryConfiguration()
            : this("broker")
        {
        }

        public broker_FscaLicenseCategoryConfiguration(string schema)
        {
            ToTable("FscaLicenseCategory", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.ProductClass).HasColumnName(@"ProductClassId").HasColumnType("int").IsRequired();
            Property(x => x.CategoryNo).HasColumnName(@"CategoryNo").HasColumnType("int").IsRequired();
            Property(x => x.SubCategoryNo).HasColumnName(@"SubCategoryNo").HasColumnType("int").IsRequired();
            Property(x => x.Description).HasColumnName(@"Description").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
        }
    }

}
