//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.ClientCare.Database.Entities;

namespace RMA.Service.ClientCare.Database.Configuration
{
    public class client_MinimumAllowablePremiumConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<client_MinimumAllowablePremium>
    {
        public client_MinimumAllowablePremiumConfiguration()
            : this("client")
        {
        }

        public client_MinimumAllowablePremiumConfiguration(string schema)
        {
            ToTable("MinimumAllowablePremium", schema);
            HasKey(x => x.MinimumAllowablePremiumId);

            Property(x => x.MinimumAllowablePremiumId).HasColumnName(@"MinimumAllowablePremiumId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.IndustryClassDeclarationConfigurationId).HasColumnName(@"IndustryClassDeclarationConfigurationId").HasColumnType("int").IsRequired();
            Property(x => x.MinimumPremium).HasColumnName(@"MinimumPremium").HasColumnType("decimal").IsRequired().HasPrecision(18,2);
            Property(x => x.EffectiveFrom).HasColumnName(@"EffectiveFrom").HasColumnType("date").IsRequired();
            Property(x => x.EffectiveTo).HasColumnName(@"EffectiveTo").HasColumnType("date").IsOptional();

            // Foreign keys
            HasRequired(a => a.IndustryClassDeclarationConfiguration).WithMany(b => b.MinimumAllowablePremiums).HasForeignKey(c => c.IndustryClassDeclarationConfigurationId).WillCascadeOnDelete(false); // FK_MinimumAllowablePremium_IndustryClassDeclarationConfiguration
        }
    }

}
