//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.ClientCare.Database.Entities;

namespace RMA.Service.ClientCare.Database.Configuration
{
    public class client_VopdResponseConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<client_VopdResponse>
    {
        public client_VopdResponseConfiguration()
            : this("client")
        {
        }

        public client_VopdResponseConfiguration(string schema)
        {
            ToTable("VopdResponse", schema);
            HasKey(x => x.VopdResponseId);

            Property(x => x.VopdResponseId).HasColumnName(@"VopdResponseId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.RolePlayerId).HasColumnName(@"RolePlayerId").HasColumnType("int").IsRequired();
            Property(x => x.VopdStatus).HasColumnName(@"VopdStatusId").HasColumnType("int").IsRequired();
            Property(x => x.Reason).HasColumnName(@"Reason").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.Identity).HasColumnName(@"Identity").HasColumnType("bit").IsOptional();
            Property(x => x.MaritalStatus).HasColumnName(@"MaritalStatus").HasColumnType("bit").IsOptional();
            Property(x => x.Death).HasColumnName(@"Death").HasColumnType("bit").IsOptional();
            Property(x => x.DateVerified).HasColumnName(@"DateVerified").HasColumnType("date").IsOptional();
            Property(x => x.IdNumber).HasColumnName(@"IdNumber").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(13);
            Property(x => x.Surname).HasColumnName(@"Surname").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.DeceasedStatus).HasColumnName(@"DeceasedStatus").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.DateOfDeath).HasColumnName(@"DateOfDeath").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.Firstname).HasColumnName(@"Firstname").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.SubmittedDate).HasColumnName(@"SubmittedDate").HasColumnType("datetime").IsOptional();
            Property(x => x.ResubmittedDate).HasColumnName(@"ResubmittedDate").HasColumnType("datetime").IsOptional();
            Property(x => x.OverrideCount).HasColumnName(@"OverrideCount").HasColumnType("int").IsOptional();
        }
    }

}
