//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.ClientCare.Database.Entities;

namespace RMA.Service.ClientCare.Database.Configuration
{
    public class client_QlinkTransactionConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<client_QlinkTransaction>
    {
        public client_QlinkTransactionConfiguration()
            : this("client")
        {
        }

        public client_QlinkTransactionConfiguration(string schema)
        {
            ToTable("QlinkTransaction", schema);
            HasKey(x => x.QlinkTransactionId);

            Property(x => x.QlinkTransactionId).HasColumnName(@"QlinkTransactionId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.QLinkTransactionType).HasColumnName(@"QlinkTransactionTypeId").HasColumnType("int").IsRequired();
            Property(x => x.ItemType).HasColumnName(@"ItemType").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.ItemId).HasColumnName(@"ItemId").HasColumnType("int").IsRequired();
            Property(x => x.Request).HasColumnName(@"Request").HasColumnType("varchar(max)").IsRequired().IsUnicode(false);
            Property(x => x.Response).HasColumnName(@"Response").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
            Property(x => x.StatusCode).HasColumnName(@"StatusCode").HasColumnType("int").IsRequired();
            Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();
            Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.IsFalsePositive).HasColumnName(@"IsFalsePositive").HasColumnType("bit").IsRequired();
        }
    }

}
