//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.ClientCare.Database.Entities;

namespace RMA.Service.ClientCare.Database.Configuration
{
    public class client_QlinkReservationTransactionConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<client_QlinkReservationTransaction>
    {
        public client_QlinkReservationTransactionConfiguration()
            : this("client")
        {
        }

        public client_QlinkReservationTransactionConfiguration(string schema)
        {
            ToTable("QlinkReservationTransaction", schema);
            HasKey(x => x.QlinkReservationTransactionId);

            Property(x => x.QlinkReservationTransactionId).HasColumnName(@"QlinkReservationTransactionId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.QlinkParentTransactionId).HasColumnName(@"QlinkParentTransactionId").HasColumnType("int").IsRequired();
            Property(x => x.QlinkChildTransactionId).HasColumnName(@"QlinkChildTransactionId").HasColumnType("int").IsOptional();
            Property(x => x.ReservationActivated).HasColumnName(@"ReservationActivated").HasColumnType("bit").IsRequired();
            Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();
            Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.Comment).HasColumnName(@"Comment").HasColumnType("varchar").IsOptional().HasMaxLength(300);

            // Foreign keys
            HasOptional(a => a.QlinkChildTransaction).WithMany(b => b.QlinkReservationTransactions_QlinkChildTransactionId).HasForeignKey(c => c.QlinkChildTransactionId).WillCascadeOnDelete(false); // FK__QlinkRese__Qlink__1AE2E34F
            HasRequired(a => a.QlinkParentTransaction).WithMany(b => b.QlinkReservationTransactions_QlinkParentTransactionId).HasForeignKey(c => c.QlinkParentTransactionId).WillCascadeOnDelete(false); // FK__QlinkRese__Qlink__19EEBF16
        }
    }

}
