//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.ClientCare.Database.Entities;

namespace RMA.Service.ClientCare.Database.Configuration
{
    public class lead_CompanyConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<lead_Company>
    {
        public lead_CompanyConfiguration()
            : this("lead")
        {
        }

        public lead_CompanyConfiguration(string schema)
        {
            ToTable("Company", schema);
            HasKey(x => x.LeadId);

            Property(x => x.LeadId).HasColumnName(@"LeadId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Name).HasColumnName(@"Name").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(255);
            Property(x => x.RegistrationType).HasColumnName(@"RegistrationTypeId").HasColumnType("int").IsOptional();
            Property(x => x.RegistrationNumber).HasColumnName(@"RegistrationNumber").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.CompensationFundReferenceNumber).HasColumnName(@"CompensationFundReferenceNumber").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.CompensationFundRegistrationNumber).HasColumnName(@"CompensationFundRegistrationNumber").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.IndustryClass).HasColumnName(@"IndustryClassId").HasColumnType("int").IsRequired();
            Property(x => x.IndustryTypeId).HasColumnName(@"IndustryTypeId").HasColumnType("int").IsRequired();
            Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();

            // Foreign keys
            HasRequired(a => a.Lead).WithOptional(b => b.Company).WillCascadeOnDelete(false); // FK_Lead_Company_LeadId
        }
    }

}
