//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.ClientCare.Database.Entities;

namespace RMA.Service.ClientCare.Database.Configuration
{
    public class Load_ClientClass13RatesConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Load_ClientClass13Rates>
    {
        public Load_ClientClass13RatesConfiguration()
            : this("Load")
        {
        }

        public Load_ClientClass13RatesConfiguration(string schema)
        {
            ToTable("ClientClass13Rates", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.FileIdentifier).HasColumnName(@"FileIdentifier").HasColumnType("uniqueidentifier").IsRequired();
            Property(x => x.RefNo).HasColumnName(@"RefNo").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(32);
            Property(x => x.CompanyName).HasColumnName(@"CompanyName").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(256);
            Property(x => x.Industry).HasColumnName(@"Industry").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(256);
            Property(x => x.IndustryGroup).HasColumnName(@"IndustryGroup").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(32);
            Property(x => x.EmpCategory).HasColumnName(@"EmpCategory").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(32);
            Property(x => x.IndRate).HasColumnName(@"IndRate").HasColumnType("decimal").IsOptional().HasPrecision(10,8);
            Property(x => x.PremRate).HasColumnName(@"PremRate").HasColumnType("decimal").IsOptional().HasPrecision(10,8);
            Property(x => x.GpLimited).HasColumnName(@"GPLimited").HasColumnType("decimal").IsOptional().HasPrecision(10,8);
            Property(x => x.FinalRate).HasColumnName(@"FinalRate").HasColumnType("decimal").IsOptional().HasPrecision(10,8);
            Property(x => x.DiscountOrLoading).HasColumnName(@"DiscountOrLoading").HasColumnType("decimal").IsOptional().HasPrecision(10,8);
            Property(x => x.DiscountOrLoadingStatus).HasColumnName(@"DiscountOrLoadingStatus").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(32);
            Property(x => x.RatingYear).HasColumnName(@"RatingYear").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(32);
            Property(x => x.LoadDate).HasColumnName(@"LoadDate").HasColumnType("datetime").IsOptional();
            Property(x => x.Product).HasColumnName(@"Product").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(32);
            Property(x => x.ExcelRowNumber).HasColumnName(@"ExcelRowNumber").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.IsExisting).HasColumnName(@"IsExisting").HasColumnType("bit").IsOptional();
            Property(x => x.UploadVersion).HasColumnName(@"UploadVersion").HasColumnType("int").IsOptional();
            Property(x => x.UploadVersionCounter).HasColumnName(@"UploadVersionCounter").HasColumnType("int").IsOptional();
        }
    }

}
