//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.ClientCare.Database.Entities;

namespace RMA.Service.ClientCare.Database.Configuration
{
    public class policy_BenefitPayrollConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<policy_BenefitPayroll>
    {
        public policy_BenefitPayrollConfiguration()
            : this("policy")
        {
        }

        public policy_BenefitPayrollConfiguration(string schema)
        {
            ToTable("BenefitPayroll", schema);
            HasKey(x => x.BenefitPayrollId);

            Property(x => x.BenefitPayrollId).HasColumnName(@"BenefitPayrollId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.BenefitDetailId).HasColumnName(@"BenefitDetailId").HasColumnType("int").IsRequired();
            Property(x => x.BenefitCategoryId).HasColumnName(@"BenefitCategoryId").HasColumnType("int").IsOptional();
            Property(x => x.EffectiveDate).HasColumnName(@"EffectiveDate").HasColumnType("date").IsRequired();
            Property(x => x.LinkedBenefitPayrollId).HasColumnName(@"LinkedBenefitPayrollId").HasColumnType("int").IsOptional();
            Property(x => x.MonthlySalary).HasColumnName(@"MonthlySalary").HasColumnType("decimal").IsOptional().HasPrecision(18,2);
            Property(x => x.SumAssured).HasColumnName(@"SumAssured").HasColumnType("decimal").IsOptional().HasPrecision(18,2);
            Property(x => x.NoOfMembers).HasColumnName(@"NoOfMembers").HasColumnType("int").IsOptional();
            Property(x => x.FixedSum).HasColumnName(@"FixedSum").HasColumnType("decimal").IsOptional().HasPrecision(18,2);
            Property(x => x.PayrollStatusId).HasColumnName(@"PayrollStatusId").HasColumnType("int").IsRequired();
            Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType("bit").IsRequired();
            Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();

            // Foreign keys
            HasOptional(a => a.LinkedBenefitPayroll).WithMany(b => b.BenefitPayrolls).HasForeignKey(c => c.LinkedBenefitPayrollId).WillCascadeOnDelete(false); // BenefitPayroll_BenefitPayroll
            HasRequired(a => a.PolicyBenefitDetail).WithMany(b => b.BenefitPayrolls).HasForeignKey(c => c.BenefitDetailId).WillCascadeOnDelete(false); // PolicyBenefitDetail_BenefitPayroll
        }
    }

}
