//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.ClientCare.Database.Entities;

namespace RMA.Service.ClientCare.Database.Configuration
{
    public class policy_BenefitRateSplitConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<policy_BenefitRateSplit>
    {
        public policy_BenefitRateSplitConfiguration()
            : this("policy")
        {
        }

        public policy_BenefitRateSplitConfiguration(string schema)
        {
            ToTable("BenefitRateSplit", schema);
            HasKey(x => x.BenefitRateSplitId);

            Property(x => x.BenefitRateSplitId).HasColumnName(@"BenefitRateSplitId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.BenefitRateDetailId).HasColumnName(@"BenefitRateDetailId").HasColumnType("int").IsRequired();
            Property(x => x.PremiumComponentId).HasColumnName(@"PremiumComponentId").HasColumnType("int").IsRequired();
            Property(x => x.TreatyId).HasColumnName(@"TreatyId").HasColumnType("int").IsRequired();
            Property(x => x.RateSplitValue).HasColumnName(@"RateSplitValue").HasColumnType("decimal").IsRequired().HasPrecision(24,6);
            Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();

            // Foreign keys
            HasRequired(a => a.BenefitRateDetail).WithMany(b => b.BenefitRateSplits).HasForeignKey(c => c.BenefitRateDetailId).WillCascadeOnDelete(false); // BenefitRateDetail_BenefitRateSplit
            HasRequired(a => a.PremiumComponent).WithMany(b => b.BenefitRateSplits).HasForeignKey(c => c.PremiumComponentId).WillCascadeOnDelete(false); // PremiumComponent_BenefitRateSplit
            HasRequired(a => a.Treaty).WithMany(b => b.BenefitRateSplits).HasForeignKey(c => c.TreatyId).WillCascadeOnDelete(false); // Treaty_BenefitRateSplit
        }
    }

}
