//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.ClientCare.Database.Entities;

namespace RMA.Service.ClientCare.Database.Configuration
{
    public class policy_PremiumListingScheduleConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<policy_PremiumListingSchedule>
    {
        public policy_PremiumListingScheduleConfiguration()
            : this("policy")
        {
        }

        public policy_PremiumListingScheduleConfiguration(string schema)
        {
            ToTable("PremiumListingSchedule", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.FileIdentifier).HasColumnName(@"FileIdentifier").HasColumnType("uniqueidentifier").IsRequired();
            Property(x => x.PolicyId).HasColumnName(@"PolicyId").HasColumnType("int").IsRequired();
            Property(x => x.ActionType).HasColumnName(@"ActionType").HasColumnType("int").IsRequired();
        }
    }

}
