//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.ClientCare.Database.Entities;

namespace RMA.Service.ClientCare.Database.Configuration
{
    public class policy_PolicyTreatyConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<policy_PolicyTreaty>
    {
        public policy_PolicyTreatyConfiguration()
            : this("policy")
        {
        }

        public policy_PolicyTreatyConfiguration(string schema)
        {
            ToTable("PolicyTreaty", schema);
            HasKey(x => x.PolicyTreatyId);

            Property(x => x.PolicyTreatyId).HasColumnName(@"PolicyTreatyId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.PolicyId).HasColumnName(@"PolicyId").HasColumnType("int").IsRequired();
            Property(x => x.TreatyId).HasColumnName(@"TreatyId").HasColumnType("int").IsRequired();
            Property(x => x.EffectiveDate).HasColumnName(@"EffectiveDate").HasColumnType("date").IsRequired();
            Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();

            // Foreign keys
            HasRequired(a => a.Policy).WithMany(b => b.PolicyTreaties).HasForeignKey(c => c.PolicyId).WillCascadeOnDelete(false); // Policy_PolicyTreaty
            HasRequired(a => a.Treaty).WithMany(b => b.PolicyTreaties).HasForeignKey(c => c.TreatyId).WillCascadeOnDelete(false); // Treaty_PolicyTreaty
        }
    }

}
