//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.ClientCare.Database.Entities;

namespace RMA.Service.ClientCare.Database.Configuration
{
    public class policy_PolicyProductDeviationConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<policy_PolicyProductDeviation>
    {
        public policy_PolicyProductDeviationConfiguration()
            : this("policy")
        {
        }

        public policy_PolicyProductDeviationConfiguration(string schema)
        {
            ToTable("PolicyProductDeviation", schema);
            HasKey(x => x.ProductDeviationId);

            Property(x => x.ProductDeviationId).HasColumnName(@"ProductDeviationId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.PolicyId).HasColumnName(@"PolicyId").HasColumnType("int").IsRequired();
            Property(x => x.ProductDeviationType).HasColumnName(@"ProductDeviationTypeId").HasColumnType("int").IsRequired();
            Property(x => x.FromBenefitId).HasColumnName(@"FromBenefitId").HasColumnType("int").IsRequired();
            Property(x => x.ToBenefitId).HasColumnName(@"ToBenefitId").HasColumnType("int").IsRequired();
            Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();

            // Foreign keys
            HasRequired(a => a.FromBenefit).WithMany(b => b.PolicyProductDeviations_FromBenefitId).HasForeignKey(c => c.FromBenefitId).WillCascadeOnDelete(false); // FK_PolicyProductDeviation_FromBenefitId
            HasRequired(a => a.Policy).WithMany(b => b.PolicyProductDeviations).HasForeignKey(c => c.PolicyId).WillCascadeOnDelete(false); // FK_PolicyProductDeviation_Policy
            HasRequired(a => a.ToBenefit).WithMany(b => b.PolicyProductDeviations_ToBenefitId).HasForeignKey(c => c.ToBenefitId).WillCascadeOnDelete(false); // FK_PolicyProductDeviation_ToBenefitId
        }
    }

}
