//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.ClientCare.Database.Entities;

namespace RMA.Service.ClientCare.Database.Configuration
{
    public class product_BenefitCoverMemberTypeConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<product_BenefitCoverMemberType>
    {
        public product_BenefitCoverMemberTypeConfiguration()
            : this("product")
        {
        }

        public product_BenefitCoverMemberTypeConfiguration(string schema)
        {
            ToTable("BenefitCoverMemberType", schema);
            HasKey(x => x.BenefitCoverMemberTypeId);

            Property(x => x.BenefitCoverMemberTypeId).HasColumnName(@"BenefitCoverMemberTypeId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.StartDate).HasColumnName(@"StartDate").HasColumnType("date").IsRequired();
            Property(x => x.EndDate).HasColumnName(@"EndDate").HasColumnType("date").IsOptional();
            Property(x => x.BenefitId).HasColumnName(@"BenefitId").HasColumnType("int").IsRequired();
            Property(x => x.CoverMemberType).HasColumnName(@"CoverMemberTypeId").HasColumnType("int").IsRequired();
            Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();

            // Foreign keys
            HasRequired(a => a.Benefit).WithMany(b => b.BenefitCoverMemberTypes).HasForeignKey(c => c.BenefitId).WillCascadeOnDelete(false); // FK_BenefitCoverMemberType_Benefit
        }
    }

}
