//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.ClientCare.Database.Entities;

namespace RMA.Service.ClientCare.Database.Configuration
{
    public class product_ProductOptionDependencyConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<product_ProductOptionDependency>
    {
        public product_ProductOptionDependencyConfiguration()
            : this("product")
        {
        }

        public product_ProductOptionDependencyConfiguration(string schema)
        {
            ToTable("ProductOptionDependency", schema);
            HasKey(x => x.ProductOptionDependencyId);

            Property(x => x.ProductOptionDependencyId).HasColumnName(@"ProductOptionDependencyId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.ProductOptionId).HasColumnName(@"ProductOptionId").HasColumnType("int").IsOptional();
            Property(x => x.ChildOptionId).HasColumnName(@"ChildOptionId").HasColumnType("int").IsRequired();
            Property(x => x.IndustryClass).HasColumnName(@"IndustryClassId").HasColumnType("int").IsRequired();
            Property(x => x.ChildPremiumPecentage).HasColumnName(@"ChildPremiumPecentage").HasColumnType("decimal").IsRequired().HasPrecision(18,2);
            Property(x => x.QuoteAutoAcceptParentAccount).HasColumnName(@"QuoteAutoAcceptParentAccount").HasColumnType("bit").IsRequired();

            // Foreign keys
            HasOptional(a => a.ProductOption).WithMany(b => b.ProductOptionDependencies).HasForeignKey(c => c.ProductOptionId).WillCascadeOnDelete(false); // FK_ProductOptionDependency_ProductOption
        }
    }

}
