//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.ClientCare.Database.Entities;

namespace RMA.Service.ClientCare.Database.Configuration
{
    public class product_BenefitProductConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<product_BenefitProduct>
    {
        public product_BenefitProductConfiguration()
            : this("product")
        {
        }

        public product_BenefitProductConfiguration(string schema)
        {
            ToTable("BenefitProduct", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.BenefitId).HasColumnName(@"BenefitId").HasColumnType("int").IsRequired();
            Property(x => x.ProductId).HasColumnName(@"ProductId").HasColumnType("int").IsRequired();

            // Foreign keys
            HasRequired(a => a.Benefit).WithMany(b => b.BenefitProducts).HasForeignKey(c => c.BenefitId).WillCascadeOnDelete(false); // FK_BenefitProduct_Benefit
            HasRequired(a => a.Product).WithMany(b => b.BenefitProducts).HasForeignKey(c => c.ProductId).WillCascadeOnDelete(false); // FK_BenefitProduct_Product
        }
    }

}
