CREATE TABLE [payment].[PaymentErrorAudit] (
    [PaymentErrorAuditId]     INT            IDENTITY (1, 1) NOT NULL,
    [ClaimId]                 INT            NULL,
    [PaymentId]               INT            NULL,
    [PolicyId]                INT            NULL,
    [PaymentInstructionId]    INT            NULL,
    [RefundHeaderId]          INT            NULL,
    [CanEdit]                 BIT            NOT NULL,
    [PaymentStatusId]         INT            NULL,
    [PaymentTypeId]           INT            NULL,
    [Payee]                   VARCHAR (80)   NOT NULL,
    [Bank]                    VARCHAR (50)   NOT NULL,
    [BankBranch]              VARCHAR (10)   NOT NULL,
    [AccountNo]               VARCHAR (17)   NOT NULL,
    [Amount]                  MONEY          NOT NULL,
    [RetainedCommission]      MONEY          NULL,
    [Product]                 VARCHAR (100)  NULL,
    [Company]                 VARCHAR (10)   NULL,
    [Branch]                  VARCHAR (10)   NULL,
    [SenderAccountNo]         VARCHAR (17)   NULL,
    [BrokerCode]              INT            NULL,
    [BrokerName]              VARCHAR (80)   NULL,
    [FSBAccredited]           BIT            NULL,
    [ErrorCode]               VARCHAR (50)   NULL,
    [MaxSubmissionCount]      INT            NULL,
    [SubmissionCount]         INT            NULL,
    [BankAccountTypeId]       INT            NULL,
    [IdNumber]                VARCHAR (13)   NULL,
    [EmailAddress]            VARCHAR (100)  NULL,
    [ClaimTypeId]             INT            NULL,
    [ErrorDescription]        NVARCHAR (150) NULL,
    [SubmissionDate]          DATETIME       NULL,
    [PaymentConfirmationDate] DATETIME       NULL,
    [ClientNotificationDate]  DATETIME       NULL,
    [CanResubmit]             BIT            NULL,
    [PaymentRejectionTypeId]  INT            NULL,
    [ClientTypeId]            INT            NULL,
    [ClaimReference]          VARCHAR (250)  NULL,
    [PolicyReference]         VARCHAR (250)  NULL,
    [Reference]               VARCHAR (250)  NULL,
    [BatchReference]          VARCHAR (250)  NULL,
    [PaymentSubmissonBatchid] INT            NULL,
    [ReconciliationDate]      DATETIME       NULL,
    [RejectionDate]           DATETIME       NULL,
    [TransactionType]         VARCHAR (20)   NULL,
    [IsActive]                BIT            NOT NULL,
    [IsDeleted]               BIT            NOT NULL,
    [CreatedBy]               VARCHAR (50)   NOT NULL,
    [CreatedDate]             DATETIME       NOT NULL,
    [ModifiedBy]              VARCHAR (50)   NOT NULL,
    [ModifiedDate]            DATETIME       NOT NULL,
    [IsImmediatePayment]      BIT            NULL,
    [RecalledDate]            DATETIME       NULL,
    CONSTRAINT [PK_payment.PaymentErrorAudit] PRIMARY KEY CLUSTERED ([PaymentErrorAuditId] ASC),
    CONSTRAINT [FK_Payment_Payment] FOREIGN KEY ([PaymentId]) REFERENCES [payment].[Payment] ([PaymentId])
);

