CREATE TABLE [payment].[paymentPensionReject] (
    [PaymentId]               INT            NOT NULL,
    [ClaimId]                 INT            NULL,
    [PolicyId]                INT            NULL,
    [PaymentInstructionId]    INT            NULL,
    [RefundHeaderId]          INT            NULL,
    [IsActive]                BIT            NOT NULL,
    [IsDeleted]               BIT            NOT NULL,
    [CreatedBy]               VARCHAR (50)   NOT NULL,
    [CreatedDate]             DATETIME       NOT NULL,
    [ModifiedBy]              VARCHAR (50)   NOT NULL,
    [ModifiedDate]            DATETIME       NOT NULL,
    [CanEdit]                 BIT            NOT NULL,
    [PaymentStatus]           INT            NULL,
    [PaymentType]             INT            NULL,
    [Payee]                   VARCHAR (80)   NOT NULL,
    [Bank]                    VARCHAR (50)   NOT NULL,
    [BankBranch]              VARCHAR (10)   NOT NULL,
    [AccountNo]               VARCHAR (17)   NOT NULL,
    [Amount]                  MONEY          NOT NULL,
    [RetainedCommission]      MONEY          NULL,
    [Product]                 VARCHAR (100)  NULL,
    [Company]                 VARCHAR (10)   NULL,
    [Branch]                  VARCHAR (10)   NULL,
    [SenderAccountNo]         VARCHAR (17)   NULL,
    [BrokerCode]              INT            NULL,
    [BrokerName]              VARCHAR (80)   NULL,
    [FSBAccredited]           BIT            NULL,
    [ErrorCode]               VARCHAR (50)   NULL,
    [MaxSubmissionCount]      INT            NULL,
    [SubmissionCount]         INT            NULL,
    [BankAccountType]         INT            NULL,
    [IdNumber]                VARCHAR (13)   NULL,
    [EmailAddress]            VARCHAR (100)  NULL,
    [ClaimType]               INT            NULL,
    [ErrorDescription]        NVARCHAR (150) NULL,
    [SubmissionDate]          DATETIME       NULL,
    [PaymentConfirmationDate] DATETIME       NULL,
    [ClientNotificationDate]  DATETIME       NULL,
    [CanResubmit]             BIT            NULL,
    [RejectionType]           INT            NULL,
    [ClientType]              INT            NULL,
    [Claim Number]            VARCHAR (250)  NULL,
    [PolicyReference]         VARCHAR (250)  NULL,
    [Ref Number]              VARCHAR (250)  NULL,
    [BatchReference]          VARCHAR (250)  NULL,
    [PaymentSubmissonBatchid] INT            NULL,
    [ReconciliationDate]      DATETIME       NULL,
    [RejectionDate]           DATETIME       NULL,
    [TransactionType]         VARCHAR (20)   NULL,
    [BankStatementReference]  VARCHAR (30)   NULL,
    [Pension Case No]         VARCHAR (50)   NULL
);

