export enum IndustryTypeEnum {
    CoalOpencast = 1,
    CoalUndergroundMixed = 2,
    Copper = 3,
    DeepUndergroundGold = 4,
    DeepUndergroundOther = 5,
    OfficesAdmin = 6,
    OpenCast = 7,
    ShallowUnderground = 8,
    SurfaceEmployeesMining = 9,
    Electriccableandsafetyrazorblades = 10,
    Foundryproductsandstovemanufacturing = 11,
    Ironandsteelproductionincludingprocessing = 12,
    Ironbuttonbuckehookeyehairpinvehicle = 13,
    Metaltubefurnituredooretcmanufacturing = 14,
    Motorcarassemblyincludingalloperations = 15,
    Motorgaraging = 16,
    Wagoncoach = 17,
    SurfaceEmployeesMetals = 18,
    DefaultMining = 19,
    DefaultMetals = 20,
    Other = 21,
    Individual = 22
}
