export enum LeadItemTypeEnum {
  Client = 1,
  Quote = 2,
  Address = 3,
  Beneficiary = 4,
  BankAccount = 5,
  Reminder = 6,
  Company = 7,
  Contact = 8,
  LeadProduct = 9,
  Notes = 10,
  Person = 11,
  Lead = 12,
  QuoteDetail = 13,
}
