export enum TransactionTypeEnum {
  PaymentReversal = 1,
  CreditNoteReversal = 2,
  Payment = 3,
  CreditNote = 4,
  InvoiceReversal = 5,
  Invoice = 6,
  Interest = 7,
  Refund = 8,
  InterDebtorTransfer = 9,
  PaymentPlan = 10,
  PaymentAllocation = 11,
  PaymentAllocationReversal = 13,
  ClaimRecoveryInvoice = 14,
  ClaimRecoveryPayment = 15,
  ClaimRecoveryPaymentReversal = 16,
  InterestReversal = 17,
  DebitReallocation = 18,
  CreditReallocation = 19
}
