export enum WorkPoolEnum {
    AllPools = 0,
    FuneralClaims = 1,
    IndividualAssessor = 2,
    SecondApprover = 3,
    InvestigationPool = 4,
    Finance = 5,
    Decline = 6,
    PolicyManager = 7,
    MedicalPool = 10,
    CadPool = 11,
    CmcPool = 12,
    FatalInvestigationPool = 13,
    EarningsAssessorPool = 14,
    ScaPool = 15,
    CcaPool = 16,
    CcaTeamLeadPool = 17,
    ClaimsAssessorPool = 18,
    ReferralPool = 19,
    PaymentPool = 20,
    CommissionPool = 21,
    CompliancePool = 22,
    PremiumCashBack = 23,
    InterbankTransfer = 24,
    MAAMedicalPool = 25,
    MIAMedicalPool = 26,
    MICMedicalPool = 27,
    CSAMedicalPool = 28

}
