//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.ClaimCare.Database.Entities;

namespace RMA.Service.ClaimCare.Database.Configuration
{
    public class claim_ClaimRequirementCategoryConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<claim_ClaimRequirementCategory>
    {
        public claim_ClaimRequirementCategoryConfiguration()
            : this("claim")
        {
        }

        public claim_ClaimRequirementCategoryConfiguration(string schema)
        {
            ToTable("ClaimRequirementCategory", schema);
            HasKey(x => x.ClaimRequirementCategoryId);

            Property(x => x.ClaimRequirementCategoryId).HasColumnName(@"ClaimRequirementCategoryId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Name).HasColumnName(@"Name").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(150);
            Property(x => x.Description).HasColumnName(@"Description").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(150);
            Property(x => x.IsManuallyAdded).HasColumnName(@"isManuallyAdded").HasColumnType("bit").IsRequired();
            Property(x => x.IsManuallyClosed).HasColumnName(@"isManuallyClosed").HasColumnType("bit").IsRequired();
            Property(x => x.IsBlockClaimChangeMacroStatus).HasColumnName(@"IsBlockClaimChangeMacroStatus").HasColumnType("bit").IsRequired();
            Property(x => x.IsBlockClaimChangeStatus).HasColumnName(@"IsBlockClaimChangeStatus").HasColumnType("bit").IsRequired();
            Property(x => x.IsBlockClaimChangeLiabilityStatus).HasColumnName(@"IsBlockClaimChangeLiabilityStatus").HasColumnType("bit").IsRequired();
            Property(x => x.IsMemberVisible).HasColumnName(@"IsMemberVisible").HasColumnType("bit").IsRequired();
            Property(x => x.IsOutstandingReason).HasColumnName(@"IsOutstandingReason").HasColumnType("bit").IsRequired();
            Property(x => x.IsPersonEventRequirement).HasColumnName(@"IsPersonEventRequirement").HasColumnType("bit").IsRequired();
            Property(x => x.IsAssurerVisible).HasColumnName(@"IsAssurerVisible").HasColumnType("bit").IsRequired();
            Property(x => x.IsBlockCloseClaim).HasColumnName(@"IsBlockCloseClaim").HasColumnType("bit").IsRequired();
            Property(x => x.Code).HasColumnName(@"Code").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.IsActive).HasColumnName(@"isActive").HasColumnType("bit").IsRequired();
            Property(x => x.IsDeleted).HasColumnName(@"isDeleted").HasColumnType("bit").IsRequired();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(100);
            Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(100);
            Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.DocumentType).HasColumnName(@"DocumentTypeId").HasColumnType("int").IsOptional();
            Property(x => x.DocumentSet).HasColumnName(@"DocumentSetId").HasColumnType("int").IsOptional();
        }
    }

}
