//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.ClaimCare.Database.Entities;

namespace RMA.Service.ClaimCare.Database.Configuration
{
    public class claim_HearingAssessmentConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<claim_HearingAssessment>
    {
        public claim_HearingAssessmentConfiguration()
            : this("claim")
        {
        }

        public claim_HearingAssessmentConfiguration(string schema)
        {
            ToTable("HearingAssessment", schema);
            HasKey(x => x.HearingAssessmentId);

            Property(x => x.HearingAssessmentId).HasColumnName(@"HearingAssessmentId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.RolePlayerId).HasColumnName(@"RolePlayerId").HasColumnType("int").IsRequired();
            Property(x => x.AssessmentDate).HasColumnName(@"AssessmentDate").HasColumnType("datetime").IsRequired();
            Property(x => x.AssessedByUserId).HasColumnName(@"AssessedByUserId").HasColumnType("int").IsRequired();
            Property(x => x.AssessedByName).HasColumnName(@"AssessedByName").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.Description).HasColumnName(@"Description").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(150);
            Property(x => x.HearingAssessmentTypeId).HasColumnName(@"HearingAssessmentTypeId").HasColumnType("int").IsRequired();
            Property(x => x.PersonEventId).HasColumnName(@"PersonEventId").HasColumnType("int").IsOptional();
            Property(x => x.PercentageHl).HasColumnName(@"PercentageHL").HasColumnType("decimal").IsOptional().HasPrecision(10,2);
            Property(x => x.BaselinePhl).HasColumnName(@"BaselinePHL").HasColumnType("decimal").IsOptional().HasPrecision(10,2);
            Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType("bit").IsRequired();
            Property(x => x.CalcOperands).HasColumnName(@"CalcOperands").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(250);
            Property(x => x.BaselineAudiogram).HasColumnName(@"BaselineAudiogram").HasColumnType("decimal").IsOptional().HasPrecision(10,2);
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();

            // Foreign keys
            HasRequired(a => a.HearingAssessmentType).WithMany(b => b.HearingAssessments).HasForeignKey(c => c.HearingAssessmentTypeId).WillCascadeOnDelete(false); // FK_HearingAssessment_HearingAssessmentType
        }
    }

}
