//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.ClaimCare.Database.Entities;

namespace RMA.Service.ClaimCare.Database.Configuration
{
    public class claim_TracerInvoiceConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<claim_TracerInvoice>
    {
        public claim_TracerInvoiceConfiguration()
            : this("claim")
        {
        }

        public claim_TracerInvoiceConfiguration(string schema)
        {
            ToTable("TracerInvoice", schema);
            HasKey(x => x.TracerInvoiceId);

            Property(x => x.TracerInvoiceId).HasColumnName(@"TracerInvoiceId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.ClaimId).HasColumnName(@"ClaimId").HasColumnType("int").IsRequired();
            Property(x => x.RolePlayerId).HasColumnName(@"RolePlayerId").HasColumnType("int").IsRequired();
            Property(x => x.TracingFee).HasColumnName(@"TracingFee").HasColumnType("decimal").IsOptional().HasPrecision(18,2);
            Property(x => x.PaymentStatus).HasColumnName(@"PaymentStatus").HasColumnType("int").IsRequired();
            Property(x => x.Reason).HasColumnName(@"Reason").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(100);
            Property(x => x.PayDate).HasColumnName(@"PayDate").HasColumnType("datetime").IsOptional();
            Property(x => x.PaymentId).HasColumnName(@"PaymentId").HasColumnType("int").IsOptional();
            Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();

            // Foreign keys
            HasRequired(a => a.Claim).WithMany(b => b.TracerInvoices).HasForeignKey(c => c.ClaimId).WillCascadeOnDelete(false); // FK_TracerInvoice_Claim
        }
    }

}
