//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.ClaimCare.Database.Entities;

namespace RMA.Service.ClaimCare.Database.Configuration
{
    public class claim_PhysicalDamageConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<claim_PhysicalDamage>
    {
        public claim_PhysicalDamageConfiguration()
            : this("claim")
        {
        }

        public claim_PhysicalDamageConfiguration(string schema)
        {
            ToTable("PhysicalDamage", schema);
            HasKey(x => x.PhysicalDamageId);

            Property(x => x.PhysicalDamageId).HasColumnName(@"PhysicalDamageId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Icd10DiagnosticGroupId).HasColumnName(@"ICD10DiagnosticGroupId").HasColumnType("int").IsRequired();
            Property(x => x.PersonEventId).HasColumnName(@"PersonEventId").HasColumnType("int").IsRequired();
            Property(x => x.Description).HasColumnName(@"Description").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(250);
            Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.IcdCategoryId).HasColumnName(@"IcdCategoryId").HasColumnType("int").IsOptional();
            Property(x => x.IcdSubCategoryId).HasColumnName(@"IcdSubCategoryId").HasColumnType("int").IsOptional();

            // Foreign keys
            HasRequired(a => a.PersonEvent).WithMany(b => b.PhysicalDamages).HasForeignKey(c => c.PersonEventId).WillCascadeOnDelete(false); // FK_PhysicalDamage_PersonEvent
        }
    }

}
