//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.ClaimCare.Database.Entities;

namespace RMA.Service.ClaimCare.Database.Configuration
{
    public class claim_FuneralInvoiceConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<claim_FuneralInvoice>
    {
        public claim_FuneralInvoiceConfiguration()
            : this("claim")
        {
        }

        public claim_FuneralInvoiceConfiguration(string schema)
        {
            ToTable("FuneralInvoice", schema);
            HasKey(x => x.ClaimInvoiceId);

            Property(x => x.ClaimInvoiceId).HasColumnName(@"ClaimInvoiceId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.ReferenceNumber).HasColumnName(@"ReferenceNumber").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(10);
            Property(x => x.RefundAmount).HasColumnName(@"RefundAmount").HasColumnType("decimal").IsOptional().HasPrecision(18,2);
            Property(x => x.OutstandingPremiumAmount).HasColumnName(@"OutstandingPremiumAmount").HasColumnType("decimal").IsOptional().HasPrecision(18,2);
            Property(x => x.UnclaimedPaymentInterest).HasColumnName(@"UnclaimedPaymentInterest").HasColumnType("decimal").IsOptional().HasPrecision(18,2);
            Property(x => x.TracingFees).HasColumnName(@"TracingFees").HasColumnType("decimal").IsOptional().HasPrecision(18,2);
            Property(x => x.CapAmount).HasColumnName(@"CapAmount").HasColumnType("decimal").IsOptional().HasPrecision(18,2);
            Property(x => x.CoverAmount).HasColumnName(@"CoverAmount").HasColumnType("decimal").IsOptional().HasPrecision(18,2);
            Property(x => x.ClaimInvoiceDecision).HasColumnName(@"ClaimInvoiceDecisionId").HasColumnType("int").IsOptional();
            Property(x => x.ClaimInvoiceDeclineReason).HasColumnName(@"ClaimInvoiceDeclineReasonId").HasColumnType("int").IsOptional();
            Property(x => x.ClaimInvoiceReversalReason).HasColumnName(@"ClaimInvoiceReversalReasonId").HasColumnType("int").IsOptional();
            Property(x => x.AllocationPercentage).HasColumnName(@"AllocationPercentage").HasColumnType("decimal").IsOptional().HasPrecision(18,2);
            Property(x => x.DecisionNote).HasColumnName(@"DecisionNote").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
            Property(x => x.BankAccountId).HasColumnName(@"BankAccountId").HasColumnType("int").IsOptional();
            Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();

            // Foreign keys
            HasRequired(a => a.ClaimInvoice).WithOptional(b => b.FuneralInvoice).WillCascadeOnDelete(false); // FK_FuneralInvoice_ClaimInvoice
        }
    }

}
