//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.ClaimCare.Database.Entities;

namespace RMA.Service.ClaimCare.Database.Configuration
{
    public class claim_ClaimBroadcastScheduleConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<claim_ClaimBroadcastSchedule>
    {
        public claim_ClaimBroadcastScheduleConfiguration()
            : this("claim")
        {
        }

        public claim_ClaimBroadcastScheduleConfiguration(string schema)
        {
            ToTable("ClaimBroadcastSchedule", schema);
            HasKey(x => x.ClaimBroadcastScheduleId);

            Property(x => x.ClaimBroadcastScheduleId).HasColumnName(@"ClaimBroadcastScheduleId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.ParamId).HasColumnName(@"ParamId").HasColumnType("int").IsRequired();
            Property(x => x.DateChanged).HasColumnName(@"DateChanged").HasColumnType("datetime").IsRequired();
            Property(x => x.UpdatedAbility).HasColumnName(@"UpdatedAbility").HasColumnType("bit").IsRequired();
            Property(x => x.MessageType).HasColumnName(@"MessageType").HasColumnType("int").IsRequired();
            Property(x => x.MsmqQueId).HasColumnName(@"MSMQQueID").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(100);
            Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();
        }
    }

}
