//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.ClaimCare.Database.Entities;

namespace RMA.Service.ClaimCare.Database.Configuration
{
    public class claim_EventCauseConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<claim_EventCause>
    {
        public claim_EventCauseConfiguration()
            : this("claim")
        {
        }

        public claim_EventCauseConfiguration(string schema)
        {
            ToTable("EventCause", schema);
            HasKey(x => x.EventCauseId);

            Property(x => x.EventCauseId).HasColumnName(@"EventCauseID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Name).HasColumnName(@"Name").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.Code).HasColumnName(@"Code").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(12);
            Property(x => x.Description).HasColumnName(@"Description").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(250);
            Property(x => x.EventType).HasColumnName(@"EventTypeID").HasColumnType("int").IsRequired();
            Property(x => x.IsThirdPartyInvolved).HasColumnName(@"IsThirdPartyInvolved").HasColumnType("bit").IsRequired();
            Property(x => x.Icd10Codes).HasColumnName(@"ICD10Codes").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.DiseaseTypeId).HasColumnName(@"DiseaseTypeID").HasColumnType("int").IsOptional();
            Property(x => x.AccidentTypeId).HasColumnName(@"AccidentTypeID").HasColumnType("int").IsOptional();
            Property(x => x.EventActionId).HasColumnName(@"EventActionID").HasColumnType("int").IsOptional();
            Property(x => x.EventActivityId).HasColumnName(@"EventActivityID").HasColumnType("int").IsOptional();
            Property(x => x.EventAgentId).HasColumnName(@"EventAgentID").HasColumnType("int").IsOptional();
            Property(x => x.IsNeedEarnings).HasColumnName(@"IsNeedEarnings").HasColumnType("bit").IsOptional();
            Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType("bit").IsRequired();
            Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(30);
            Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();
        }
    }

}
