//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.ClaimCare.Database.Entities;

namespace RMA.Service.ClaimCare.Database.Configuration
{
    public class claim_FatalLumpSumInvoiceConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<claim_FatalLumpSumInvoice>
    {
        public claim_FatalLumpSumInvoiceConfiguration()
            : this("claim")
        {
        }

        public claim_FatalLumpSumInvoiceConfiguration(string schema)
        {
            ToTable("FatalLumpSumInvoice", schema);
            HasKey(x => x.ClaimInvoiceId);

            Property(x => x.ClaimInvoiceId).HasColumnName(@"ClaimInvoiceId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.PayeeId).HasColumnName(@"PayeeId").HasColumnType("int").IsRequired();
            Property(x => x.PayeeTypeId).HasColumnName(@"PayeeTypeId").HasColumnType("int").IsRequired();
            Property(x => x.Description).HasColumnName(@"Description").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(250);
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.ClaimId).HasColumnName(@"ClaimId").HasColumnType("int").IsRequired();

            // Foreign keys
            HasRequired(a => a.Claim).WithMany(b => b.FatalLumpSumInvoices).HasForeignKey(c => c.ClaimId).WillCascadeOnDelete(false); // FK_FatalLumpSumInvoice_Claim
            HasRequired(a => a.ClaimInvoice).WithOptional(b => b.FatalLumpSumInvoice).WillCascadeOnDelete(false); // FK_FatalLumpSumInvoice_ClaimInvoice
        }
    }

}
