//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.ClaimCare.Database.Entities;

namespace RMA.Service.ClaimCare.Database.Configuration
{
    public class common_ReferralConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<common_Referral>
    {
        public common_ReferralConfiguration()
            : this("common")
        {
        }

        public common_ReferralConfiguration(string schema)
        {
            ToTable("Referral", schema);
            HasKey(x => x.ReferralId);

            Property(x => x.ReferralId).HasColumnName(@"ReferralId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.ReferralReferenceNumber).HasColumnName(@"ReferralReferenceNumber").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.SourceModuleTypeId).HasColumnName(@"SourceModuleTypeId").HasColumnType("int").IsRequired();
            Property(x => x.ReferralType).HasColumnName(@"ReferralTypeId").HasColumnType("int").IsRequired();
            Property(x => x.ReferralNatureOfQueryId).HasColumnName(@"ReferralNatureOfQueryId").HasColumnType("int").IsRequired();
            Property(x => x.ReferralItemType).HasColumnName(@"ReferralItemTypeId").HasColumnType("int").IsOptional();
            Property(x => x.ItemId).HasColumnName(@"ItemId").HasColumnType("bigint").IsOptional();
            Property(x => x.LinkUrl).HasColumnName(@"LinkUrl").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.Comment).HasColumnName(@"Comment").HasColumnType("varchar(max)").IsRequired().IsUnicode(false);
            Property(x => x.ReferralStatus).HasColumnName(@"ReferralStatusId").HasColumnType("int").IsRequired();
            Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.ReferralPerformanceRatingId).HasColumnName(@"ReferralPerformanceRatingId").HasColumnType("int").IsOptional();
            Property(x => x.TargetModuleTypeId).HasColumnName(@"TargetModuleTypeId").HasColumnType("int").IsOptional();
            Property(x => x.AssignedByUserId).HasColumnName(@"AssignedByUserId").HasColumnType("int").IsOptional();
            Property(x => x.AssignedToRoleId).HasColumnName(@"AssignedToRoleId").HasColumnType("int").IsOptional();
            Property(x => x.AssignedToUserId).HasColumnName(@"AssignedToUserId").HasColumnType("int").IsOptional();
            Property(x => x.ReferralItemTypeReference).HasColumnName(@"ReferralItemTypeReference").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);

            // Foreign keys
            HasOptional(a => a.ReferralPerformanceRating).WithMany(b => b.Referrals).HasForeignKey(c => c.ReferralPerformanceRatingId).WillCascadeOnDelete(false); // FK_Referral_ReferralPerformanceRating
            HasRequired(a => a.ReferralNatureOfQuery).WithMany(b => b.Referrals).HasForeignKey(c => c.ReferralNatureOfQueryId).WillCascadeOnDelete(false); // FK_Referral_ReferralNatureOfQuery
        }
    }

}
