//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.ClaimCare.Database.Entities;

namespace RMA.Service.ClaimCare.Database.Configuration
{
    public class common_ReferralStatusChangeAuditConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<common_ReferralStatusChangeAudit>
    {
        public common_ReferralStatusChangeAuditConfiguration()
            : this("common")
        {
        }

        public common_ReferralStatusChangeAuditConfiguration(string schema)
        {
            ToTable("ReferralStatusChangeAudit", schema);
            HasKey(x => x.ReferralStatusChangeAuditId);

            Property(x => x.ReferralStatusChangeAuditId).HasColumnName(@"ReferralStatusChangeAuditId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.ReferralId).HasColumnName(@"ReferralId").HasColumnType("int").IsRequired();
            Property(x => x.ReferralStatus).HasColumnName(@"ReferralStatusId").HasColumnType("int").IsRequired();
            Property(x => x.ModifiedByUserId).HasColumnName(@"ModifiedByUserId").HasColumnType("int").IsRequired();
            Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();

            // Foreign keys
            HasRequired(a => a.Referral).WithMany(b => b.ReferralStatusChangeAudits).HasForeignKey(c => c.ReferralId).WillCascadeOnDelete(false); // FK_ReferralStatusChangeAudit_Referral
        }
    }

}
