//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.ClaimCare.Database.Entities;

namespace RMA.Service.ClaimCare.Database.Configuration
{
    public class common_UnderAssessReasonConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<common_UnderAssessReason>
    {
        public common_UnderAssessReasonConfiguration()
            : this("common")
        {
        }

        public common_UnderAssessReasonConfiguration(string schema)
        {
            ToTable("UnderAssessReason", schema);
            HasKey(x => x.UnderAssessReasonId);

            Property(x => x.UnderAssessReasonId).HasColumnName(@"UnderAssessReasonId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Code).HasColumnName(@"Code").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(12);
            Property(x => x.Description).HasColumnName(@"Description").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(2048);
            Property(x => x.InvoiceType).HasColumnName(@"InvoiceTypeId").HasColumnType("int").IsRequired();
            Property(x => x.InvoiceStatus).HasColumnName(@"InvoiceStatusId").HasColumnType("int").IsRequired();
            Property(x => x.OverrideAuditObjectTypeId).HasColumnName(@"OverrideAuditObjectTypeId").HasColumnType("int").IsOptional();
            Property(x => x.ConfirmAuditObjectTypeId).HasColumnName(@"ConfirmAuditObjectTypeId").HasColumnType("int").IsOptional();
            Property(x => x.CanReinstate).HasColumnName(@"CanReinstate").HasColumnType("bit").IsOptional();
            Property(x => x.Action).HasColumnName(@"Action").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(10);
            Property(x => x.FirstNotification).HasColumnName(@"FirstNotification").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.SecondNotification).HasColumnName(@"SecondNotification").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.ThirdNotification).HasColumnName(@"ThirdNotification").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.IsLineItemReason).HasColumnName(@"IsLineItemReason").HasColumnType("bit").IsRequired();
            Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType("bit").IsRequired();
            Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();
        }
    }

}
