CREATE TABLE [Load].[BankStatementEntryStaging] (
    [BankStatementEntryId]      INT            IDENTITY (1, 1) NOT NULL,
    [IsActive]                  BIT            NOT NULL,
    [IsDeleted]                 BIT            NOT NULL,
    [CreatedBy]                 VARCHAR (50)   NOT NULL,
    [CreatedDate]               DATETIME       NOT NULL,
    [ModifiedBy]                VARCHAR (50)   NOT NULL,
    [ModifiedDate]              DATETIME       NOT NULL,
    [CanEdit]                   VARCHAR (50)   NULL,
    [TransactionType]           VARCHAR (50)   NULL,
    [DocumentType]              VARCHAR (50)   NULL,
    [UserReference1]            VARCHAR (1000) NULL,
    [UserReference2]            VARCHAR (1000) NULL,
    [RequisitionNumber]         VARCHAR (50)   NULL,
    [ChequeDepositNumber]       VARCHAR (50)   NULL,
    [BankAccountNumber]         VARCHAR (50)   NULL,
    [UniqueUserCode]            VARCHAR (50)   NULL,
    [BankBranch]                VARCHAR (50)   NULL,
    [SubType]                   VARCHAR (50)   NULL,
    [TransactionDate]           VARCHAR (50)   NULL,
    [StatementDate]             VARCHAR (50)   NULL,
    [EStatementNumber]          VARCHAR (50)   NULL,
    [StatementNumber]           VARCHAR (50)   NULL,
    [BankName]                  VARCHAR (50)   NULL,
    [RecordID]                  VARCHAR (50)   NULL,
    [HyphenDateProcessed]       VARCHAR (50)   NULL,
    [BankAndStatementDate]      VARCHAR (50)   NULL,
    [ReReceiveCode]             VARCHAR (50)   NULL,
    [StatementTransactionCount] VARCHAR (50)   NULL,
    [NettAmount]                VARCHAR (50)   NULL,
    [HyphenDateReceived]        VARCHAR (50)   NULL,
    [Status]                    VARCHAR (50)   NULL,
    [StatementAndLineNumber]    VARCHAR (50)   NULL,
    [BatchNumber]               VARCHAR (50)   NULL,
    [DebitCredit]               VARCHAR (50)   NULL,
    [StatementLineNumber]       VARCHAR (50)   NULL,
    [ErrorCode]                 VARCHAR (50)   NULL,
    [Proccessed]                VARCHAR (50)   NULL,
    [User]                      VARCHAR (50)   NULL,
    [Code1]                     VARCHAR (50)   NULL,
    [Code2]                     VARCHAR (50)   NULL,
    [UserReference]             VARCHAR (1000) NULL,
    [ClaimCheckReference]       VARCHAR (1000) NULL,
    [ErrorMessage]              VARCHAR (1000) NULL,
    [Imported]                  BIT            NULL,
    CONSTRAINT [PK__BankStat__5354C86343298158] PRIMARY KEY CLUSTERED ([BankStatementEntryId] ASC)
);

