CREATE TABLE [Load].[ConsolidatedFuneral] (
    [Id]                          INT              IDENTITY (1, 1) NOT NULL,
    [FileIdentifier]              UNIQUEIDENTIFIER NOT NULL,
    [ClientReference]             VARCHAR (32)     NULL,
    [ClientType]                  VARCHAR (32)     NULL,
    [FirstName]                   VARCHAR (256)    NULL,
    [Surname]                     VARCHAR (256)    NULL,
    [MainMemberID]                VARCHAR (32)     NULL,
    [IdNumber]                    VARCHAR (32)     NULL,
    [PassportNumber]              VARCHAR (32)     NULL,
    [DateOfBirth]                 VARCHAR (32)     NULL,
    [Gender]                      VARCHAR (16)     NULL,
    [BenefitName]                 VARCHAR (128)    NULL,
    [JoinDate]                    VARCHAR (32)     NULL,
    [AffordibilityChecked]        VARCHAR (32)     NULL,
    [Premium]                     VARCHAR (64)     NULL,
    [CoverAmount]                 VARCHAR (64)     NULL,
    [PreviousInsurer]             VARCHAR (256)    NULL,
    [PreviousInsurerPolicyNumber] VARCHAR (50)     NULL,
    [PreviousInsurerStartDate]    VARCHAR (32)     NULL,
    [PreviousInsurerEndDate]      VARCHAR (32)     NULL,
    [PreviousInsurerCoverAmount]  VARCHAR (64)     NULL,
    [Address1]                    VARCHAR (256)    NULL,
    [Address2]                    VARCHAR (256)    NULL,
    [City]                        VARCHAR (256)    NULL,
    [Province]                    VARCHAR (256)    NULL,
    [Country]                     VARCHAR (256)    NULL,
    [PostalCode]                  VARCHAR (8)      NULL,
    [PostalAddress1]              VARCHAR (256)    NULL,
    [PostalAddress2]              VARCHAR (256)    NULL,
    [PostalCity]                  VARCHAR (256)    NULL,
    [PostalProvince]              VARCHAR (256)    NULL,
    [PostalCountry]               VARCHAR (256)    NULL,
    [PostalPostCode]              VARCHAR (8)      NULL,
    [Telephone]                   VARCHAR (24)     NULL,
    [Mobile]                      VARCHAR (24)     NULL,
    [Email]                       VARCHAR (128)    NULL,
    [PreferredCommunication]      VARCHAR (24)     NULL,
    [ProductOption]               VARCHAR (128)    NULL,
    [AnnualIncreaseOption]        VARCHAR (16)     NULL,
    [IncreaseMonth]               VARCHAR (16)     NULL,
    [Employer]                    VARCHAR (128)    NULL,
    [PersalNumber]                VARCHAR (32)     NULL,
    [Department]                  VARCHAR (64)     NULL,
    [Bank]                        VARCHAR (64)     NULL,
    [BranchCode]                  VARCHAR (16)     NULL,
    [AccountNo]                   VARCHAR (32)     NULL,
    [AccountType]                 VARCHAR (64)     NULL,
    [DebitOrderDay]               VARCHAR (8)      NULL,
    [RepIdNumber]                 VARCHAR (16)     NULL,
    [PolicyNumber]                VARCHAR (32)     NULL,
    [ExcelRowNumber]              INT              NULL,
    CONSTRAINT [PK__Consolid__3214EC0732C50D3A] PRIMARY KEY CLUSTERED ([Id] ASC)
);

