CREATE TABLE [Load].[ConsolidatedFuneralMember] (
    [Id]                     INT              IDENTITY (1, 1) NOT NULL,
    [FileIdentifier]         UNIQUEIDENTIFIER NOT NULL,
    [ClientReference]        VARCHAR (64)     NOT NULL,
    [JoinDate]               DATE             NULL,
    [CoverMemberTypeId]      INT              NOT NULL,
    [RolePlayerTypeId]       INT              NOT NULL,
    [IdTypeId]               INT              NOT NULL,
    [IdNumber]               VARCHAR (64)     NOT NULL,
    [MainMemberIdNumber]     VARCHAR (32)     NOT NULL,
    [FirstName]              VARCHAR (64)     NOT NULL,
    [Surname]                VARCHAR (64)     NOT NULL,
    [MemberName]             VARCHAR (128)    NOT NULL,
    [DateOfBirth]            DATE             NULL,
    [Gender]                 VARCHAR (16)     NULL,
    [Age]                    INT              NOT NULL,
    [JoinAge]                INT              NOT NULL,
    [Affordability]          VARCHAR (32)     NULL,
    [ProductOption]          VARCHAR (128)    NULL,
    [BenefitName]            VARCHAR (128)    NULL,
    [BrokerageId]            INT              NULL,
    [RepresentativeId]       INT              NULL,
    [RepIdNumber]            VARCHAR (16)     NULL,
    [PolicyId]               INT              NOT NULL,
    [PolicyNumber]           VARCHAR (32)     NULL,
    [PolicyPremium]          DECIMAL (18, 2)  NOT NULL,
    [PolicyCover]            DECIMAL (18, 2)  NOT NULL,
    [ExistingCover]          DECIMAL (18, 2)  NULL,
    [Multiplier]             INT              NOT NULL,
    [RolePlayerId]           INT              NOT NULL,
    [MainMemberRolePlayerId] INT              NOT NULL,
    [ProductOptionId]        INT              NOT NULL,
    [BenefitId]              INT              NOT NULL,
    [PolicyExists]           BIT              NOT NULL,
    [RolePlayerExists]       BIT              NOT NULL,
    [Address1]               VARCHAR (256)    NULL,
    [Address2]               VARCHAR (256)    NULL,
    [City]                   VARCHAR (256)    NULL,
    [Province]               VARCHAR (256)    NULL,
    [Country]                VARCHAR (256)    NULL,
    [PostalCode]             VARCHAR (8)      NULL,
    [PostalAddress1]         VARCHAR (256)    NULL,
    [PostalAddress2]         VARCHAR (256)    NULL,
    [PostalCity]             VARCHAR (256)    NULL,
    [PostalProvince]         VARCHAR (256)    NULL,
    [PostalCountry]          VARCHAR (256)    NULL,
    [PostalPostCode]         VARCHAR (8)      NULL,
    [TelNo]                  VARCHAR (32)     NULL,
    [CelNo]                  VARCHAR (32)     NULL,
    [Email]                  VARCHAR (128)    NULL,
    [PreferredCommunication] INT              NULL,
    [AnnualIncreaseType]     INT              NULL,
    [AnnualIncreaseMonth]    INT              NULL,
    [DebitOrderDay]          INT              NULL,
    [TestDateOfBirth]        VARCHAR (24)     NULL,
    [TestJoinDate]           VARCHAR (24)     NULL,
    CONSTRAINT [PK_ConsolidatedFuneralMember] PRIMARY KEY CLUSTERED ([Id] ASC)
);

