CREATE TABLE [Load].[ConsolidatedFuneral](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FileIdentifier] [uniqueidentifier] NOT NULL,
	[ClientReference] [varchar] (32) NULL,
	[ClientType] [varchar](32) NULL,
	[FirstName] [varchar](256) NULL,
	[Surname] [varchar](256) NULL,
	[MainMemberID] [varchar](32) NULL,
	[IdNumber] [varchar](32) NULL,
	[PassportNumber] [varchar](32) NULL,
	[DateOfBirth] [varchar](32) NULL,
	[Gender] [varchar](16) NULL,
	[BenefitName] [varchar](128) NULL,
	[JoinDate] [varchar](32) NULL,
	[AffordibilityChecked] [varchar](8) NULL,
	[Premium] [varchar](64) NULL,
	[CoverAmount] [varchar](64) NULL,
	[PreviousInsurer] [varchar](256) NULL,
	[PreviousInsurerPolicyNumber] [varchar](50) NULL,
	[PreviousInsurerStartDate] [varchar](32) NULL,
	[PreviousInsurerEndDate] [varchar](32) NULL,
	[PreviousInsurerCoverAmount] [varchar](64) NULL,
	[Address1] [varchar](256) NULL,
	[Address2] [varchar](256) NULL,
	[City] [varchar](256) NULL,
	[Province] [varchar](256) NULL,
	[Country] [varchar](256) NULL,
	[PostalCode] [varchar](8) NULL,
	[PostalAddress1] [varchar](256) NULL,
	[PostalAddress2] [varchar](256) NULL,
	[PostalCity] [varchar](256) NULL,
	[PostalProvince] [varchar](256) NULL,
	[PostalCountry] [varchar](256) NULL,
	[PostalPostCode] [varchar](8) NULL,
	[Telephone] [varchar](24) NULL,
	[Mobile] [varchar](24) NULL,
	[Email] [varchar](128) NULL,
	[PreferredCommunication] [varchar](24) NULL,
	[EuropAssist] [varchar](8) NULL,
	[AnnualIncreaseOption] [varchar](16) NULL,
	[IncreaseMonth] [varchar](16) NULL,
	[Employer] [varchar](128) NULL,
	[PersalNumber] [varchar](32) NULL,
	[Department] [varchar](64) NULL,
	[Bank] [varchar](64) NULL,
	[BranchCode] [varchar](16) NULL,
	[AccountNo] [varchar](32) NULL,
	[AccountType] [varchar](64) NULL,
	[DebitOrderDay] [varchar](8) NULL,
	[ExcelRowNumber] [int] NULL,
PRIMARY KEY CLUSTERED
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
