CREATE TABLE [Load].[DiscountFileListing] (
    [Id]                     INT              IDENTITY (1, 1) NOT NULL,
    [FileIdentifier]         UNIQUEIDENTIFIER NOT NULL,
    [HealthCarePractitioner] VARCHAR (150)    NULL,
    [TakPrc]                 VARCHAR (50)     NULL,
    [AccPer]                 VARCHAR (50)     NULL,
    [AccountNumber]          VARCHAR (50)     NULL,
    [PatientInitials]        VARCHAR (50)     NULL,
    [PatientName]            VARCHAR (50)     NULL,
    [MedicalAidCode]         VARCHAR (50)     NULL,
    [MedicalAidName]         VARCHAR (150)    NULL,
    [MedicalAidNumber]       VARCHAR (50)     NULL,
    [LosAuthCode]            VARCHAR (50)     NULL,
    [MedicalAidPlan]         VARCHAR (50)     NULL,
    [TrackingNumber]         VARCHAR (50)     NULL,
    [SwitchRef]              VARCHAR (50)     NULL,
    [BatchNumber]            VARCHAR (50)     NULL,
    [AdmDate]                VARCHAR (50)     NULL,
    [DisDate]                VARCHAR (50)     NULL,
    [RenDate]                VARCHAR (50)     NULL,
    [LastRenDate]            VARCHAR (50)     NULL,
    [DateDelivered]          VARCHAR (50)     NULL,
    [DateReceived]           VARCHAR (50)     NULL,
    [DateSent]               VARCHAR (50)     NULL,
    [AccountTotal]           VARCHAR (50)     NULL,
    [OutstandingBalance]     VARCHAR (50)     NULL,
    [PharmacyTotal]          VARCHAR (50)     NULL,
    [ReceiptTotal]           VARCHAR (50)     NULL,
    [ReceiptDate]            VARCHAR (50)     NULL,
    [ReceiptNumber]          VARCHAR (50)     NULL,
    [BatchNo]                VARCHAR (50)     NULL,
    [BatchType]              VARCHAR (50)     NULL,
    [PrivateAmount]          VARCHAR (50)     NULL,
    [BenefitAmount]          VARCHAR (50)     NULL,
    [FinalBenefitAmount]     VARCHAR (50)     NULL,
    [PatType]                VARCHAR (50)     NULL,
    [ArrServProvider]        VARCHAR (50)     NULL,
    [DeliveredReceipt]       VARCHAR (50)     NULL,
    [RenderedToReceipt]      VARCHAR (50)     NULL,
    [LastRenderedToReceipt]  VARCHAR (50)     NULL,
    [DateSend]               VARCHAR (50)     NULL,
    [DaysCalculated]         VARCHAR (50)     NULL,
    [DiscountPercentage]     VARCHAR (50)     NULL,
    [Discount]               VARCHAR (50)     NULL,
    [HCPInvoiceNumber]       VARCHAR (50)     NULL,
    [HCPAccountNumber]       VARCHAR (50)     NULL,
    [RMAInvoiceNumber]       VARCHAR (50)     NULL,
    [ExcelRowNumber]         INT              NULL,
    [IsDeleted]              BIT              CONSTRAINT [DF_DiscountFileListing_IsDeleted] DEFAULT ((0)) NOT NULL,
    [CreatedBy]              VARCHAR (50)     CONSTRAINT [DF_DiscountFileListing_CreatedBy] DEFAULT ('system@randmutual.co.za') NOT NULL,
    [CreatedDate]            DATETIME         CONSTRAINT [DF_DiscountFileListing_CreatedDate] DEFAULT (getdate()) NOT NULL,
    [ModifiedBy]             VARCHAR (50)     CONSTRAINT [DF_DiscountFileListing_ModifiedBy] DEFAULT ('system@randmutual.co.za') NOT NULL,
    [ModifiedDate]           DATETIME         CONSTRAINT [DF_DiscountFileListing_ModifiedDate] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK__DiscountFileListing__3214EC0732C50D3A] PRIMARY KEY CLUSTERED ([Id] ASC)
);

