CREATE TABLE [Load].[Leads] (
    [Id]                       INT              IDENTITY (1, 1) NOT NULL,
    [FileIdentifier]           UNIQUEIDENTIFIER NOT NULL,
    [LeadSource]               VARCHAR (32)     NULL,
    [MemberName]               VARCHAR (256)    NULL,
    [ClientType]               VARCHAR (32)     NULL,
    [CommunicationType]        VARCHAR (32)     NULL,
    [IsPreferredCommunication] BIT              CONSTRAINT [DF_Leads_IsPreferredCommunication] DEFAULT ((0)) NULL,
    [ContactName]              VARCHAR (256)    NULL,
    [Contact]                  VARCHAR (256)    NULL,
    [AddressType]              VARCHAR (32)     NULL,
    [AddressLine1]             VARCHAR (256)    NULL,
    [AddressLine2]             VARCHAR (256)    NULL,
    [PostalCode]               VARCHAR (32)     NULL,
    [Country]                  VARCHAR (32)     NULL,
    [Province]                 VARCHAR (32)     NULL,
    [City]                     VARCHAR (32)     NULL,
    [NoteText]                 VARCHAR (MAX)    NULL,
    [IndustryClass]            VARCHAR (32)     NULL,
    [IndustryType]             VARCHAR (32)     NULL,
    [RegistrationType]         VARCHAR (32)     NULL,
    [CompanyRegNo]             VARCHAR (32)     NULL,
    [CFReferenceNo]            VARCHAR (32)     NULL,
    [CFRegistrationNo]         VARCHAR (32)     NULL,
    [IDType]                   VARCHAR (32)     NULL,
    [IDNumber]                 VARCHAR (32)     NULL,
    [FirstName]                VARCHAR (50)     NULL,
    [Surname]                  VARCHAR (50)     NULL,
    [ExcelRowNumber]           VARCHAR (50)     NULL,
    [Notes]                    NVARCHAR (MAX)   NULL,
    [IsExisting]               BIT              CONSTRAINT [DF_Leads_IsExisting] DEFAULT ((0)) NULL,
    [UploadVersion]            INT              NULL,
    [UploadVersionCounter]     INT              NULL,
    CONSTRAINT [PK__Leads__3214EC07FA2ECE40] PRIMARY KEY CLUSTERED ([Id] ASC)
);

