CREATE TABLE [Load].[QLinkPaymentRecordStaging] (
    [QLinkMonthlyPremiumEntryId]      INT           IDENTITY (1, 1) NOT NULL,
    [ClaimCheckReference]             NVARCHAR (50) NOT NULL,
    [SalaryMonth]                     NVARCHAR (10) NOT NULL,
    [OperationType]                   NVARCHAR (10) NOT NULL,
    [Payroll]                         NVARCHAR (10) NOT NULL,
    [EmployeeNumber]                  NVARCHAR (50) NOT NULL,
    [Surname]                         NVARCHAR (50) NOT NULL,
    [Initials]                        NVARCHAR (4)  NOT NULL,
    [IDNumber]                        NVARCHAR (13) NOT NULL,
    [ReferenceNumber]                 NVARCHAR (50) NOT NULL,
    [Amount]                          INT           NOT NULL,
    [StartDate]                       NVARCHAR (10) NOT NULL,
    [EndDate]                         NVARCHAR (10) NOT NULL,
    [DeductionType]                   NVARCHAR (10) NOT NULL,
    [Department]                      NVARCHAR (50) NOT NULL,
    [Location]                        NVARCHAR (50) NOT NULL,
    [BranchCode]                      NVARCHAR (10) NOT NULL,
    [AppointmentCode]                 NVARCHAR (10) NOT NULL,
    [Partner]                         NVARCHAR (50) NOT NULL,
    [HyphenDateReceived]              NVARCHAR (10) NULL,
    [HyphenDateProcessed]             NVARCHAR (10) NULL,
    [StatementDate]                   NVARCHAR (10) NULL,
    [Premium]                         INT           NULL,
    [Commission]                      INT           NULL,
    [ImportedToQlinkTransactionTable] BIT           CONSTRAINT [DF__QLinkPaym__Impor__1BACEA56] DEFAULT ((0)) NOT NULL,
    [IsActive]                        BIT           CONSTRAINT [DF_QLinkPaymentRecordStaging_IsActive] DEFAULT ((1)) NOT NULL,
    [IsDeleted]                       BIT           CONSTRAINT [DF_QLinkPaymentRecordStaging_IsDeleted] DEFAULT ((0)) NOT NULL,
    [CreatedDate]                     DATETIME      NOT NULL,
    [CreatedBy]                       VARCHAR (50)  NOT NULL,
    [ModifiedDate]                    DATETIME      NOT NULL,
    [ModifiedBy]                      VARCHAR (50)  NOT NULL,
    CONSTRAINT [PK_QLinkMonthlyPremiumEntryStaging] PRIMARY KEY CLUSTERED ([QLinkMonthlyPremiumEntryId] ASC)
);

