CREATE TABLE [Load].[StageGroupRisk] (
    [StageGroupRiskId]                       INT             IDENTITY (1, 1) NOT NULL,
    [ExcelRowNumber]                         INT             NOT NULL,
    [FileIdentifier]                         VARCHAR (50)    NOT NULL,
    [SchemeNumber]                           VARCHAR (20)    NOT NULL,
    [BranchName]                             VARCHAR (20)    NOT NULL,
    [FinPayeeRolePlayerId]                   INT             NOT NULL,
    [EmployeeRolePlayerId]                   INT             NOT NULL,
    [EmployeeIndustryNumber]                 VARCHAR (100)   NULL,
    [EmployeeNumber]                         VARCHAR (100)   NULL,
    [IdOrPassport]                           VARCHAR (20)    NOT NULL,
    [IdentityTypeId]                         INT             NOT NULL,
    [DateOfBirth]                            DATETIME        NOT NULL,
    [FirstName]                              VARCHAR (50)    NOT NULL,
    [Surname]                                VARCHAR (50)    NOT NULL,
    [GenderId]                               INT             NOT NULL,
    [MobileNumber]                           VARCHAR (25)    NULL,
    [Email]                                  VARCHAR (50)    NULL,
    [PreferredStakeholderCommunication]      VARCHAR (20)    NULL,
    [MemberPreferredMethodOfCommunicationId] INT             NOT NULL,
    [MonthlyRiskSalary]                      DECIMAL (10, 2) NOT NULL,
    [EmployeeStartDate]                      DATETIME        NOT NULL,
    [PolicyStartDate]                        DATETIME        NOT NULL,
    [BrokerageFspNumber]                     VARCHAR (20)    NOT NULL,
    [RepresentativeIdNumber]                 VARCHAR (20)    NOT NULL,
    [PolicyNumber]                           VARCHAR (50)    NULL,
    [PolicyId]                               INT             NULL,
    [ProductOptionId]                        INT             NOT NULL,
    [BenefitId]                              INT             NOT NULL,
    [WizardId]                               INT             NULL,
    [GroupRiskPolicyActionTypeId]            INT             NOT NULL,
    [GroupRiskStagingStatusTypeId]           INT             NOT NULL,
    [Escalation]                             VARCHAR (500)   NULL,
    [Note]                                   VARCHAR (500)   NULL,
    [DiscountPercentage]                     DECIMAL (3, 2)  DEFAULT ((0)) NOT NULL,
    [BenefitMultiplier]                      INT             NOT NULL,
    [IsDeleted]                              BIT             DEFAULT ((0)) NOT NULL,
    [CreatedDate]                            DATETIME        DEFAULT (getdate()) NOT NULL,
    [CreatedBy]                              VARCHAR (50)    NOT NULL,
    [ModifiedDate]                           DATETIME        DEFAULT (getdate()) NOT NULL,
    [ModifiedBy]                             VARCHAR (50)    NOT NULL,
    PRIMARY KEY CLUSTERED ([StageGroupRiskId] ASC),
    FOREIGN KEY ([GenderId]) REFERENCES [common].[Gender] ([Id]),
    FOREIGN KEY ([GroupRiskPolicyActionTypeId]) REFERENCES [common].[GroupRiskPolicyActionType] ([Id]),
    FOREIGN KEY ([GroupRiskStagingStatusTypeId]) REFERENCES [common].[GroupRiskStagingStatusType] ([Id]),
    FOREIGN KEY ([IdentityTypeId]) REFERENCES [common].[IdType] ([Id]),
    FOREIGN KEY ([MemberPreferredMethodOfCommunicationId]) REFERENCES [common].[CommunicationType] ([Id])
);

