using System.ComponentModel.DataAnnotations;

namespace RMA.Service.ClientCare.Contracts.Enums.RolePlayer
{
    public enum RolePlayerTypeEnum
    {
        [Display(Name = "Policy Owner")]
        PolicyOwner = 1,
        [Display(Name = "Policy Payee")]
        PolicyPayee = 2,
        [Display(Name = "Insured Life")]
        InsuredLife = 3,
        [Display(Name = "Financial Service Provider")]
        FinancialServiceProvider = 4,
        [Display(Name = "Claimant")]
        Claimant = 5,
        [Display(Name = "Medical Service Provider")]
        MedicalServiceProvider = 6,
        [Display(Name = "Funeral Parlor")]
        FuneralParlor = 7,
        [Display(Name = "Body Collector")]
        BodyCollector = 8,
        [Display(Name = "Undertaker")]
        Undertaker = 9,
        [Display(Name = "Main Member (self)")]
        MainMemberSelf = 10,
        [Display(Name = "Spouse")]
        Spouse = 11,
        [Display(Name = "Daughter")]
        Daughter = 12,
        [Display(Name = "Daughter in law")]
        DaughterInlaw = 13,
        [Display(Name = "Son in law")]
        SonInlaw = 14,
        [Display(Name = "Son")]
        Son = 15,
        [Display(Name = "Parent")]
        Parent = 16,
        [Display(Name = "Parent in law")]
        ParentInlaw = 17,
        [Display(Name = "Grandparent")]
        Grandparent = 18,
        [Display(Name = "Mother")]
        Mother = 19,
        [Display(Name = "Mother in law")]
        MotherInlaw = 20,
        [Display(Name = "Father")]
        Father = 21,
        [Display(Name = "Father in law")]
        FatherInlaw = 22,
        [Display(Name = "Brother")]
        Brother = 23,
        [Display(Name = "Brother in law")]
        BrotherInlaw = 24,
        [Display(Name = "Sister")]
        Sister = 25,
        [Display(Name = "Sister in law")]
        SisterInlaw = 26,
        [Display(Name = "Aunt")]
        Aunt = 27,
        [Display(Name = "Niece")]
        Niece = 28,
        [Display(Name = "Nephew")]
        Nephew = 29,
        [Display(Name = "Husband")]
        Husband = 30,
        [Display(Name = "Wife")]
        Wife = 31,
        [Display(Name = "Child")]
        Child = 32,
        [Display(Name = "Special Child")]
        SpecialChild = 33,
        [Display(Name = "Other")]
        Other = 34,
        [Display(Name = "Guardian Recipient")]
        GuardianRecipient = 35,
        [Display(Name = "Person Individual")]
        PersonIndividual = 36,
        [Display(Name = "Pensioner")]
        Pensioner = 37,
        [Display(Name = "Extended")]
        Extended = 38,
        [Display(Name = "Disabled Child")]
        DisabledChild = 39,
        [Display(Name = "Uncle")]
        Uncle = 40,
        [Display(Name = "Beneficiary")]
        Beneficiary = 41,
        [Display(Name = "Cousin")]
        Cousin = 42,
        [Display(Name = "Grand Child")]
        GrandChild = 44,
        [Display(Name = "Friend")]
        Friend = 45,
        [Display(Name = "Supsense Account")]
        SupsenseAccount = 46,
        [Display(Name = "Subsidiary")]
        Subsidiary = 47,
        [Display(Name = "Branch")]
        Branch = 48
    }
}