CREATE TABLE [common].[ProductCode_Temp] (
    [ProductCodeID]         INT                                        IDENTITY (1, 1) NOT NULL,
    [ProductCode]           VARCHAR (40)                               NULL,
    [Name]                  VARCHAR (50)                               NULL,
    [Description]           VARCHAR (2048)                             NULL,
    [ProductStatusId]       INT                                        NULL,
    [NoteID]                INT                                        NULL,
    [StartDate]             DATETIME                                   NOT NULL,
    [EndDate]               DATETIME                                   NOT NULL,
    [HasClientRates]        CHAR (1)                                   NULL,
    [RIExcessofLoss]        MONEY                                      NULL,
    [RIShortfallPercentage] DECIMAL (7, 2)                             NULL,
    [IsAugProduct]          TINYINT                                    NULL,
    [IsStatProduct]         TINYINT                                    NULL,
    [IsMainProduct]         TINYINT                                    NULL,
    [ParentInsuranceTypeID] INT                                        NULL,
    [StatMinEarnings]       MONEY MASKED WITH (FUNCTION = 'default()') NULL,
    [StatMaxEarnings]       MONEY MASKED WITH (FUNCTION = 'default()') NULL,
    [IsAccumulated]         TINYINT                                    NULL,
    [IsVatIndicator]        BIT                                        NULL,
    [IsTaxIndicator]        BIT                                        NULL,
    [IsUnderAct]            BIT                                        NULL,
    [IsActive]              INT                                        NULL,
    [LastChangedBy]         VARCHAR (30)                               NULL,
    [LastChangedDate]       DATETIME                                   NULL,
    [SOITypeID]             INT                                        NULL,
    [IsFuneralProduct]      BIT                                        NULL,
    [GroupCompanyID]        INT                                        NULL,
    CONSTRAINT [PK_Common_ProductCode_ProductCodeID] PRIMARY KEY CLUSTERED ([ProductCodeID] ASC) WITH (FILLFACTOR = 95)
);

