CREATE TABLE [common].[TebaBulkInvoice_Temp](
	[TebaBulkInvoiceId]			INT IDENTITY(1,1) NOT NULL,
	[InvoiceAmount]				DECIMAL(18, 2) NULL,
	[InvoiceVAT]				DECIMAL(18, 2) NULL,
	[AuthorisedAmount]			DECIMAL(18, 2) NULL,
	[AuthorisedVAT]				DECIMAL(18, 2) NULL,
	[VATPercentage]				DECIMAL(7, 2) NULL,
	[VatCodeId]					INT NOT NULL,
	[DateTravelledFrom]			DATETIME NULL,
	[DateTravelledTo]			DATETIME NULL,
	[SPInvoiceNumber]			DATETIME NULL,
	[InvoicerId]				INT NOT NULL,
	[InvoicerTypeId]			INT NOT NULL,
	[PayeeId]					INT NOT NULL,
	[PayeeTypeId]				INT NOT NULL,
	[InvoiceStatusId]			INT NOT NULL,
	[Description]				VARCHAR(2048) NULL,
	[UnderAssessedReason]		VARCHAR(512) NULL,
	[CalcOperands]				VARCHAR(200) NULL,
	[DateCaptured]				DATETIME NOT NULL,
	[DateSubmitted]				DATETIME NOT NULL,
	[DateReceived]				DATETIME NULL,
	[DateCompleted]				DATETIME NULL,
	[InvoiceAmountInclusive]	AS (ISNULL([InvoiceAmount],(0))+ISNULL([InvoiceVAT],(0))),
	[AuthorisedAmountInclusive] AS (ISNULL([AuthorisedAmount],(0))+ISNULL([AuthorisedVAT],(0))),
	[SwitchBatchId]				INT NOT NULL,
	[SwitchTransactionNo]		VARCHAR(50) NULL,
	[HoldingKey]				VARCHAR(50) NULL,
	[SPAccountNumber]			VARCHAR(50) NULL,
	[IsActive]					BIT NOT NULL,
	[IsDeleted]					BIT NOT NULL,
	[CreatedBy]					VARCHAR(50) NOT NULL,
	[CreatedDate]				DATETIME NOT NULL,
	[ModifiedBy]				VARCHAR(50) NOT NULL,
	[ModifiedDate]				DATETIME NOT NULL,
    CONSTRAINT [PK_common_TebaBulkInvoice_TebaBulkInvoiceId] PRIMARY KEY CLUSTERED ([TebaBulkInvoiceId] ASC) WITH (FILLFACTOR = 90, PAD_INDEX = ON)
 );