CREATE TABLE [common].[TEBABulkInvoiceBreakdown_Temp] (
    [TEBABulkInvoiceBreakdownId] INT            IDENTITY (1, 1) NOT NULL,
    [TEBABulkInvoiceId]          INT            NOT NULL,
    [Quantity]                   DECIMAL (18)   NOT NULL,
    [TotalInvoiceLineVAT]        MONEY          NOT NULL,
    [TotalInvoiceLineCost]       MONEY          NOT NULL,
    [TotalServiceLineCost]       MONEY          NOT NULL,
    [CreditAmount]               MONEY          NOT NULL,
    [AuthorisedAmount]           MONEY          NULL,
    [AuthorisedVAT]              MONEY          NULL,
    [VATPercentage]              DECIMAL (18)   NULL,
    [VatCodeId]                  INT            NOT NULL,
    [ServiceCodeId]              INT            NOT NULL,
    [Description]                VARCHAR (2048) NULL,
    [SummaryInvBreakdownId]      INT            NULL,
    [IsDuplicate]                BIT            NOT NULL,
    [DuplicateTIBId]             INT            NOT NULL,
    [UnderAssessReasonId]        INT            NOT NULL,
    [UnderAssessedReason]        VARCHAR (512)  NULL,
    [ServiceDate]                DATETIME       NOT NULL,
    [IsActive]                   BIT            NOT NULL,
    [TotalServiceCodeLineVAT]    MONEY          NOT NULL,
    [CalcOperands]               VARCHAR (2048) NULL,
    [UnitCost]                   AS             (((isnull([TotalInvoiceLineCost],(0))+isnull([CreditAmount],(0)))+isnull([TotalInvoiceLineVat],(0)))/[Quantity]),
    [InclTotalLineCost]          AS             (isnull([TotalInvoiceLineCost],(0))+isnull([TotalInvoiceLineVat],(0))),
    [InclAuthorisedAmount]       AS             (isnull([AuthorisedAmount],(0))+isnull([AuthorisedVAT],(0))),
    [TotalServiceCodeLineIncl]   AS             ([TotalServiceLineCost]+[TotalServiceCodeLineVAT]),
    [TreatmentAuthID]            INT            NULL,
    [IsDeleted]                  BIT            NOT NULL,
    [CreatedBy]                  VARCHAR (50)   NOT NULL,
    [CreatedDate]                DATETIME       NOT NULL,
    [ModifiedBy]                 VARCHAR (50)   NOT NULL,
    [ModifiedDate]               DATETIME       NOT NULL,
    CONSTRAINT [PK_common_TEBABulkInvoiceBreakdown_Temp_TEBABulkInvoiceBreakdownId] PRIMARY KEY CLUSTERED ([TEBABulkInvoiceBreakdownId] ASC) WITH (FILLFACTOR = 90, PAD_INDEX = ON)
);

