CREATE TABLE [common].[WorkflowRouting_Temp] (
    [WorkflowRoutingId]     INT             IDENTITY (1, 1) NOT NULL,
    [Name]                  VARCHAR (100)   NOT NULL,
    [Description]           VARCHAR (2048)  NULL,
    [HoursToAlertTime]      INT             NOT NULL,
    [HoursToDeadlineTime]   INT             NOT NULL,
    [TaskTypeId]            INT             NOT NULL,
    [PriorityId]            INT             NOT NULL,
    [WorkURLTemplate]       VARCHAR (2048)  NULL,
    [IsSystemClosed]        BIT             NOT NULL,
    [IsDeleted]             BIT             NOT NULL,
    [CreatedBy]             VARCHAR (50)    NOT NULL,
    [CreatedDate]           DATETIME        NOT NULL,
    [ModifiedBy]            VARCHAR (50)    NOT NULL,
    [ModifiedDate]          DATETIME        NOT NULL,
    [IsSendSMS]             BIT             NULL,
    [IsSendEmail]           BIT             NULL,
    [AttachFilepath]        VARCHAR (500)   NULL,
    [IsAmountCheck]         INT             NULL,
    [IsEditable]            BIT             NULL,
    [ForApplication]        TINYINT         NULL,
    [IsActive]              BIT             CONSTRAINT [WorkflowRouting_Temp_IsActive] DEFAULT ((1)) NOT NULL,
    [ContextType]           VARCHAR (50)    CONSTRAINT [WorkflowRouting_Temp_ContextType] DEFAULT ('NOT SET') NOT NULL,
    [MessageTemplate]       NVARCHAR (1000) CONSTRAINT [WorkflowRouting_Temp_MessageTemplate] DEFAULT ('{0}') NOT NULL,
    [AutoCloseTime]         INT             CONSTRAINT [WorkflowRouting_Temp_AutoClosingTime] DEFAULT ('30') NOT NULL,
    [IsDistributionEnabled] BIT             CONSTRAINT [WorkflowRouting_Temp_IsDistributionEnabled] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_common_WorkflowRouting_Temp_WorkflowRoutingId] PRIMARY KEY CLUSTERED ([WorkflowRoutingId] ASC) WITH (FILLFACTOR = 90, PAD_INDEX = ON),
    CONSTRAINT [FK_WorkflowRouting_Temp_AppName_Temp] FOREIGN KEY ([ForApplication]) REFERENCES [common].[AppName_Temp] ([AppId]),
    CONSTRAINT [FK_WorkflowRouting_Temp_TaskType_Temp] FOREIGN KEY ([TaskTypeId]) REFERENCES [common].[TaskType_Temp] ([TaskTypeId])
);

