//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.BusinessProcessManager.Database.Entities;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;

namespace RMA.Service.Admin.BusinessProcessManager.Database.Configuration
{
    public class bpm_WizardConfig : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<bpm_Wizard>
    {
        public bpm_WizardConfig()
            : this("bpm")
        {
        }

        public bpm_WizardConfig(string schema)
        {
            ToTable("Wizard", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.TenantId).HasColumnName(@"TenantId").HasColumnType("int").IsRequired();
            Property(x => x.WizardConfigurationId).HasColumnName(@"WizardConfigurationId").HasColumnType("int").IsRequired();
            Property(x => x.WizardStatus).HasColumnName(@"WizardStatusId").HasColumnType("int").IsRequired();
            Property(x => x.LinkedItemId).HasColumnName(@"LinkedItemId").HasColumnType("int").IsOptional();
            Property(x => x.Name).HasColumnName(@"Name").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(200);
            Property(x => x.Data).HasColumnName(@"Data").HasColumnType("varchar(max)").IsRequired().IsUnicode(false);
            Property(x => x.CurrentStepIndex).HasColumnName(@"CurrentStepIndex").HasColumnType("int").IsRequired();
            Property(x => x.LockedToUser).HasColumnName(@"LockedToUser").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.CustomStatus).HasColumnName(@"CustomStatus").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(100);
            Property(x => x.CustomRoutingRoleId).HasColumnName(@"CustomRoutingRoleId").HasColumnType("int").IsOptional();
            Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType("bit").IsRequired();
            Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.StartDateAndTime).HasColumnName(@"StartDateAndTime").HasColumnType("datetime").IsOptional();
            Property(x => x.EndDateAndTime).HasColumnName(@"EndDateAndTime").HasColumnType("datetime").IsOptional();

            // Foreign keys
            HasRequired(a => a.WizardConfiguration).WithMany(b => b.Wizards).HasForeignKey(c => c.WizardConfigurationId).WillCascadeOnDelete(false); // FK_Wizard_WizardConfiguration
        }
    }

}
