//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.BusinessProcessManager.Database.Entities;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;

namespace RMA.Service.Admin.BusinessProcessManager.Database.Configuration
{
    public class bpm_WizardConfigurationConfig : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<bpm_WizardConfiguration>
    {
        public bpm_WizardConfigurationConfig()
            : this("bpm")
        {
        }

        public bpm_WizardConfigurationConfig(string schema)
        {
            ToTable("WizardConfiguration", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Name).HasColumnName(@"Name").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.DisplayName).HasColumnName(@"DisplayName").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.Description).HasColumnName(@"Description").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(100);
            Property(x => x.SlaWarning).HasColumnName(@"SLAWarning").HasColumnType("int").IsOptional();
            Property(x => x.SlaEscalation).HasColumnName(@"SLAEscalation").HasColumnType("int").IsOptional();
            Property(x => x.UserSlaWarning).HasColumnName(@"UserSLAWarning").HasColumnType("int").IsOptional();
            Property(x => x.UserSlaEscalation).HasColumnName(@"UserSLAEscalation").HasColumnType("int").IsOptional();
            Property(x => x.AllowEditOnApproval).HasColumnName(@"AllowEditOnApproval").HasColumnType("bit").IsRequired();
            Property(x => x.IsOverridable).HasColumnName(@"IsOverridable").HasColumnType("bit").IsRequired();
            Property(x => x.IsNotification).HasColumnName(@"IsNotification").HasColumnType("bit").IsRequired();
            Property(x => x.CanReAssign).HasColumnName(@"CanReAssign").HasColumnType("bit").IsRequired();
        }
    }

}
