//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;

namespace RMA.Service.Billing.Database.Entities
{
    public partial class billing_InterBankTransferDetail : IAuditableEntity, ISoftDeleteEntity
    {
        public int InterBankTransferDetailId { get; set; } // InterBankTransferDetailId (Primary key)
        public int InterBankTransferId { get; set; } // InterBankTransferId
        public int? BankStatementEntryId { get; set; } // BankStatementEntryId
        public string StatementReference { get; set; } // StatementReference (length: 100)
        public decimal Amount { get; set; } // Amount
        public string CreatedBy { get; set; } // CreatedBy (length: 50)
        public System.DateTime CreatedDate { get; set; } // CreatedDate
        public string ModifiedBy { get; set; } // ModifiedBy (length: 50)
        public System.DateTime ModifiedDate { get; set; } // ModifiedDate
        public bool IsDeleted { get; set; } // IsDeleted
        public int? TransactionId { get; set; } // TransactionId

        // Foreign keys

        /// <summary>
        /// Parent billing_InterBankTransfer pointed by [InterBankTransferDetail].([InterBankTransferId]) (FK_InterBankTransferDetail_InterBankTransfer)
        /// </summary>
        public virtual billing_InterBankTransfer InterBankTransfer { get; set; } // FK_InterBankTransferDetail_InterBankTransfer

        /// <summary>
        /// Parent finance_BankStatementEntry pointed by [InterBankTransferDetail].([BankStatementEntryId]) (FK_InterBankTransferDetail_BankStatementEntry)
        /// </summary>
        public virtual finance_BankStatementEntry BankStatementEntry { get; set; } // FK_InterBankTransferDetail_BankStatementEntry

        public billing_InterBankTransferDetail()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
