//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;

namespace RMA.Service.Billing.Database.Entities
{
    public partial class billing_AdhocPaymentInstruction : IAuditableEntity, ILazyLoadSafeEntity
    {
        public int AdhocPaymentInstructionId { get; set; } // AdhocPaymentInstructionId (Primary key)
        public System.DateTime DateToPay { get; set; } // DateToPay
        public AdhocPaymentInstructionStatusEnum AdhocPaymentInstructionStatus { get; set; } // AdhocPaymentInstructionStatusId
        public string Reason { get; set; } // Reason (length: 50)
        public decimal Amount { get; set; } // Amount
        public int RolePlayerId { get; set; } // RolePlayerId
        public string RolePlayerName { get; set; } // RolePlayerName (length: 255)
        public System.DateTime CreatedDate { get; set; } // CreatedDate
        public System.DateTime ModifiedDate { get; set; } // ModifiedDate
        public string CreatedBy { get; set; } // CreatedBy (length: 50)
        public string ModifiedBy { get; set; } // ModifiedBy (length: 50)
        public string ErrorDescription { get; set; } // ErrorDescription (length: 150)
        public int? RolePlayerBankingId { get; set; } // RolePlayerBankingId

        // Reverse navigation

        /// <summary>
        /// Child billing_AdhocPaymentInstructionsTermArrangementSchedules where [AdhocPaymentInstructionsTermArrangementSchedule].[AdhocPaymentInstructionId] point to this entity (FK_AdhocPaymentInstructionsTermArrangementSchedule_AdhocPaymentInstructions)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<billing_AdhocPaymentInstructionsTermArrangementSchedule> AdhocPaymentInstructionsTermArrangementSchedules { get; set; } // AdhocPaymentInstructionsTermArrangementSchedule.FK_AdhocPaymentInstructionsTermArrangementSchedule_AdhocPaymentInstructions
        /// <summary>
        /// Child billing_Collections where [Collections].[AdhocPaymentInstructionId] point to this entity (FK_Collections_AdhocPaymentInstructions)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<billing_Collection> Collections { get; set; } // Collections.FK_Collections_AdhocPaymentInstructions
        /// <summary>
        /// Child billing_Transactions where [Transactions].[AdhocPaymentInstructionId] point to this entity (FK_Transactions_AdhocPaymentInstructions)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<billing_Transaction> Transactions { get; set; } // Transactions.FK_Transactions_AdhocPaymentInstructions

        // Foreign keys

        /// <summary>
        /// Parent client_RolePlayerBankingDetail pointed by [AdhocPaymentInstructions].([RolePlayerBankingId]) (FK_AdhocPaymentInstructions_RolePlayerBankingDetails)
        /// </summary>
        public virtual client_RolePlayerBankingDetail RolePlayerBankingDetail { get; set; } // FK_AdhocPaymentInstructions_RolePlayerBankingDetails

        public billing_AdhocPaymentInstruction()
        {
            AdhocPaymentInstructionsTermArrangementSchedules = new System.Collections.Generic.List<billing_AdhocPaymentInstructionsTermArrangementSchedule>();
            Collections = new System.Collections.Generic.List<billing_Collection>();
            Transactions = new System.Collections.Generic.List<billing_Transaction>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
