//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;

namespace RMA.Service.Billing.Database.Entities
{
    public partial class billing_UnallocatedPayment : IAuditableEntity, ISoftDeleteEntity, IEntityStatus
    {
        public int UnallocatedPaymentId { get; set; } // UnallocatedPaymentId (Primary key)
        public int BankStatementEntryId { get; set; } // BankStatementEntryId
        public AllocationProgressStatusEnum? AllocationProgressStatus { get; set; } // AllocationProgressStatusId
        public decimal UnallocatedAmount { get; set; } // UnallocatedAmount
        public bool IsActive { get; set; } // IsActive
        public bool IsDeleted { get; set; } // IsDeleted
        public string CreatedBy { get; set; } // CreatedBy (length: 50)
        public System.DateTime CreatedDate { get; set; } // CreatedDate
        public string ModifiedBy { get; set; } // ModifiedBy (length: 50)
        public System.DateTime ModifiedDate { get; set; } // ModifiedDate
        public int? RoleplayerId { get; set; } // RoleplayerId
        public int? PeriodId { get; set; } // PeriodId

        // Reverse navigation

        /// <summary>
        /// Child billing_AbilityTransactionsAudits where [AbilityTransactionsAudit].[UnallocatedPaymentId] point to this entity (FK_AbilityTransactionsAudit_UnallocatedPayment)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<billing_AbilityTransactionsAudit> AbilityTransactionsAudits { get; set; } // AbilityTransactionsAudit.FK_AbilityTransactionsAudit_UnallocatedPayment

        // Foreign keys

        /// <summary>
        /// Parent common_Period pointed by [UnallocatedPayment].([PeriodId]) (FK_UnallocatedPayment_Period)
        /// </summary>
        public virtual common_Period Period { get; set; } // FK_UnallocatedPayment_Period

        /// <summary>
        /// Parent finance_BankStatementEntry pointed by [UnallocatedPayment].([BankStatementEntryId]) (FK_UnallocatedPayment_BankStatementEntry)
        /// </summary>
        public virtual finance_BankStatementEntry BankStatementEntry { get; set; } // FK_UnallocatedPayment_BankStatementEntry

        public billing_UnallocatedPayment()
        {
            UnallocatedAmount = 0m;
            IsActive = true;
            IsDeleted = false;
            CreatedDate = System.DateTime.Now;
            ModifiedDate = System.DateTime.Now;
            AbilityTransactionsAudits = new System.Collections.Generic.List<billing_AbilityTransactionsAudit>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
