//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;

namespace RMA.Service.Billing.Database.Entities
{
    public partial class client_SchemeClassification : IAuditableEntity, ISoftDeleteEntity
    {
        public int RolePlayerId { get; set; } // RolePlayerId (Primary key)
        public UnderwrittenEnum Underwritten { get; set; } // UnderwrittenId (Primary key)
        public PolicyHolderTypeEnum PolicyHolderType { get; set; } // PolicyHolderTypeId (Primary key)
        public bool IsPartnership { get; set; } // IsPartnership (Primary key)
        public bool IsDeleted { get; set; } // IsDeleted (Primary key)
        public string CreatedBy { get; set; } // CreatedBy (Primary key) (length: 50)
        public System.DateTime CreatedDate { get; set; } // CreatedDate (Primary key)
        public string ModifiedBy { get; set; } // ModifiedBy (Primary key) (length: 50)
        public System.DateTime ModifiedDate { get; set; } // ModifiedDate (Primary key)

        // Foreign keys

        /// <summary>
        /// Parent client_Company pointed by [SchemeClassification].([RolePlayerId]) (FK_SchemeClassification_RolePlayerId)
        /// </summary>
        public virtual client_Company Company { get; set; } // FK_SchemeClassification_RolePlayerId

        public client_SchemeClassification()
        {
            IsDeleted = false;
            CreatedDate = System.DateTime.Now;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
