//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;

namespace RMA.Service.Billing.Database.Entities
{
    public partial class common_Referral : IAuditableEntity, ISoftDeleteEntity
    {
        public int ReferralId { get; set; } // ReferralId (Primary key)
        public string ReferralReferenceNumber { get; set; } // ReferralReferenceNumber (length: 50)
        public int SourceModuleTypeId { get; set; } // SourceModuleTypeId
        public ReferralTypeEnum ReferralType { get; set; } // ReferralTypeId
        public int ReferralNatureOfQueryId { get; set; } // ReferralNatureOfQueryId
        public ReferralItemTypeEnum? ReferralItemType { get; set; } // ReferralItemTypeId
        public long? ItemId { get; set; } // ItemId
        public string LinkUrl { get; set; } // LinkUrl (length: 255)
        public string Comment { get; set; } // Comment
        public ReferralStatusEnum ReferralStatus { get; set; } // ReferralStatusId
        public bool IsDeleted { get; set; } // IsDeleted
        public string ModifiedBy { get; set; } // ModifiedBy (length: 50)
        public System.DateTime ModifiedDate { get; set; } // ModifiedDate
        public string CreatedBy { get; set; } // CreatedBy (length: 50)
        public System.DateTime CreatedDate { get; set; } // CreatedDate
        public int? ReferralPerformanceRatingId { get; set; } // ReferralPerformanceRatingId
        public int? TargetModuleTypeId { get; set; } // TargetModuleTypeId
        public int? AssignedByUserId { get; set; } // AssignedByUserId
        public int? AssignedToRoleId { get; set; } // AssignedToRoleId
        public int? AssignedToUserId { get; set; } // AssignedToUserId
        public string ReferralItemTypeReference { get; set; } // ReferralItemTypeReference (length: 50)

        // Reverse navigation

        /// <summary>
        /// Child common_ReferralFeedbacks where [ReferralFeedback].[ReferralId] point to this entity (FK_ReferralFeedback_Referral)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<common_ReferralFeedback> ReferralFeedbacks { get; set; } // ReferralFeedback.FK_ReferralFeedback_Referral
        /// <summary>
        /// Child common_ReferralStatusChangeAudits where [ReferralStatusChangeAudit].[ReferralId] point to this entity (FK_ReferralStatusChangeAudit_Referral)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<common_ReferralStatusChangeAudit> ReferralStatusChangeAudits { get; set; } // ReferralStatusChangeAudit.FK_ReferralStatusChangeAudit_Referral

        // Foreign keys

        /// <summary>
        /// Parent common_ReferralNatureOfQuery pointed by [Referral].([ReferralNatureOfQueryId]) (FK_Referral_ReferralNatureOfQuery)
        /// </summary>
        public virtual common_ReferralNatureOfQuery ReferralNatureOfQuery { get; set; } // FK_Referral_ReferralNatureOfQuery

        /// <summary>
        /// Parent common_ReferralPerformanceRating pointed by [Referral].([ReferralPerformanceRatingId]) (FK_Referral_ReferralPerformanceRating)
        /// </summary>
        public virtual common_ReferralPerformanceRating ReferralPerformanceRating { get; set; } // FK_Referral_ReferralPerformanceRating

        public common_Referral()
        {
            ReferralFeedbacks = new System.Collections.Generic.List<common_ReferralFeedback>();
            ReferralStatusChangeAudits = new System.Collections.Generic.List<common_ReferralStatusChangeAudit>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
