//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;

namespace RMA.Service.Billing.Database.Entities
{
    public partial class common_AuthorityLimitConfiguration : IAuditableEntity, ISoftDeleteEntity
    {
        public int AuthorityLimitConfigurationId { get; set; } // AuthorityLimitConfigurationId (Primary key)
        public AuthorityLimitConfigurationTypeEnum AuthorityLimitConfigurationType { get; set; } // AuthorityLimitConfigurationTypeId
        public AuthorityLimitValueTypeEnum AuthorityLimitValueType { get; set; } // AuthorityLimitValueTypeId
        public AuthorityLimitItemTypeEnum AuthorityLimitItemType { get; set; } // AuthorityLimitItemTypeId
        public int Value { get; set; } // Value
        public string PermissionName { get; set; } // PermissionName (length: 50)
        public bool IsDeleted { get; set; } // IsDeleted
        public string ModifiedBy { get; set; } // ModifiedBy (length: 50)
        public System.DateTime ModifiedDate { get; set; } // ModifiedDate
        public string CreatedBy { get; set; } // CreatedBy (length: 50)
        public System.DateTime CreatedDate { get; set; } // CreatedDate

        // Reverse navigation

        /// <summary>
        /// Child common_AuthorityLimitConfigurationUserAudits where [AuthorityLimitConfigurationUserAudit].[AuthorityLimitConfigurationId] point to this entity (FK_AuthorityLimitConfigurationUserAudit_AuthorityLimitConfiguration)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<common_AuthorityLimitConfigurationUserAudit> AuthorityLimitConfigurationUserAudits { get; set; } // AuthorityLimitConfigurationUserAudit.FK_AuthorityLimitConfigurationUserAudit_AuthorityLimitConfiguration

        public common_AuthorityLimitConfiguration()
        {
            AuthorityLimitConfigurationUserAudits = new System.Collections.Generic.List<common_AuthorityLimitConfigurationUserAudit>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
