//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;

namespace RMA.Service.Billing.Database.Entities
{
    public partial class Load_InsuredLivesMessage : ILazyLoadSafeEntity
    {
        public System.Guid FileIdentifier { get; set; } // FileIdentifier (Primary key)
        public string Message { get; set; } // Message (length: 256)

        public Load_InsuredLivesMessage()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
