//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;

namespace RMA.Service.Billing.Database.Entities
{
    public partial class policy_PremiumPayback : IAuditableEntity, ISoftDeleteEntity
    {
        public int PremiumPaybackId { get; set; } // PremiumPaybackId (Primary key)
        public int PolicyId { get; set; } // PolicyId
        public PremiumPaybackStatusEnum PremiumPaybackStatus { get; set; } // PremiumPaybackStatusId
        public System.DateTime PaybackDate { get; set; } // PaybackDate
        public System.DateTime? NotificationSendDate { get; set; } // NotificationSendDate
        public string PaybackFailedReason { get; set; } // PaybackFailedReason (length: 512)
        public System.DateTime? PremiumPaidDate { get; set; } // PremiumPaidDate
        public decimal? PaybackAmount { get; set; } // PaybackAmount
        public bool IsDeleted { get; set; } // IsDeleted
        public string CreatedBy { get; set; } // CreatedBy (length: 50)
        public System.DateTime CreatedDate { get; set; } // CreatedDate
        public string ModifiedBy { get; set; } // ModifiedBy (length: 50)
        public System.DateTime ModifiedDate { get; set; } // ModifiedDate

        // Foreign keys

        /// <summary>
        /// Parent policy_Policy pointed by [PremiumPayback].([PolicyId]) (FK__PremiumPa__Polic__1AE14CA1)
        /// </summary>
        public virtual policy_Policy Policy { get; set; } // FK__PremiumPa__Polic__1AE14CA1

        public policy_PremiumPayback()
        {
            IsDeleted = false;
            CreatedDate = System.DateTime.Now;
            ModifiedDate = System.DateTime.Now;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
