//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;

namespace RMA.Service.Billing.Database.Entities
{
    public partial class policy_BenefitRateSplit : IAuditableEntity, ISoftDeleteEntity
    {
        public int BenefitRateSplitId { get; set; } // BenefitRateSplitId (Primary key)
        public int BenefitRateDetailId { get; set; } // BenefitRateDetailId
        public int PremiumComponentId { get; set; } // PremiumComponentId
        public int TreatyId { get; set; } // TreatyId
        public decimal RateSplitValue { get; set; } // RateSplitValue
        public bool IsDeleted { get; set; } // IsDeleted
        public string CreatedBy { get; set; } // CreatedBy (length: 50)
        public System.DateTime CreatedDate { get; set; } // CreatedDate
        public string ModifiedBy { get; set; } // ModifiedBy (length: 50)
        public System.DateTime ModifiedDate { get; set; } // ModifiedDate

        // Foreign keys

        /// <summary>
        /// Parent common_PremiumComponent pointed by [BenefitRateSplit].([PremiumComponentId]) (PremiumComponent_BenefitRateSplit)
        /// </summary>
        public virtual common_PremiumComponent PremiumComponent { get; set; } // PremiumComponent_BenefitRateSplit

        /// <summary>
        /// Parent policy_BenefitRateDetail pointed by [BenefitRateSplit].([BenefitRateDetailId]) (BenefitRateDetail_BenefitRateSplit)
        /// </summary>
        public virtual policy_BenefitRateDetail BenefitRateDetail { get; set; } // BenefitRateDetail_BenefitRateSplit

        public policy_BenefitRateSplit()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
