//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;

namespace RMA.Service.Billing.Database.Entities
{
    public partial class policy_PostRetirementMedicalAnnuityInvoiceHeader : IAuditableEntity, ISoftDeleteEntity
    {
        public int PostRetirementMedicalAnnuityInvoiceHeaderId { get; set; } // PostRetirementMedicalAnnuityInvoiceHeaderId (Primary key)
        public int MedicalAidRolePlayerId { get; set; } // MedicalAidRolePlayerId
        public InvoiceStatusEnum InvoiceStatus { get; set; } // InvoiceStatusId
        public System.DateTime InvoiceDate { get; set; } // InvoiceDate
        public string ReferenceNumber { get; set; } // ReferenceNumber (length: 50)
        public int NumberLines { get; set; } // NumberLines
        public decimal TotalBillAmount { get; set; } // TotalBillAmount
        public decimal TotalPaymentAmount { get; set; } // TotalPaymentAmount
        public string ValidatedBy { get; set; } // ValidatedBy (length: 50)
        public System.DateTime? ValidatedDate { get; set; } // ValidatedDate
        public string PaymentRequestedBy { get; set; } // PaymentRequestedBy (length: 50)
        public System.DateTime? PaymentRequestedDate { get; set; } // PaymentRequestedDate
        public bool IsDeleted { get; set; } // IsDeleted
        public string CreatedBy { get; set; } // CreatedBy (length: 50)
        public System.DateTime CreatedDate { get; set; } // CreatedDate
        public string ModifiedBy { get; set; } // ModifiedBy (length: 50)
        public System.DateTime ModifiedDate { get; set; } // ModifiedDate

        // Reverse navigation

        /// <summary>
        /// Child payment_Allocations where [Allocation].[PostRetirementMedicalAnnuityInvoiceHeaderId] point to this entity (FK_Allocation_PostRetirementMedicalAnnuityInvoiceHeader)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<payment_Allocation> Allocations { get; set; } // Allocation.FK_Allocation_PostRetirementMedicalAnnuityInvoiceHeader
        /// <summary>
        /// Child policy_PostRetirementMedicalAnnuityInvoiceDetails where [PostRetirementMedicalAnnuityInvoiceDetail].[PostRetirementMedicalAnnuityInvoiceHeaderId] point to this entity (FK_PostRetirementMedicalAidInvoiceDetail_PostRetirementMedicalAidInvoiceHeader)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<policy_PostRetirementMedicalAnnuityInvoiceDetail> PostRetirementMedicalAnnuityInvoiceDetails { get; set; } // PostRetirementMedicalAnnuityInvoiceDetail.FK_PostRetirementMedicalAidInvoiceDetail_PostRetirementMedicalAidInvoiceHeader

        // Foreign keys

        /// <summary>
        /// Parent client_Company pointed by [PostRetirementMedicalAnnuityInvoiceHeader].([MedicalAidRolePlayerId]) (FK_PostRetirementMedicalAidInvoiceHeader_RolePlayer)
        /// </summary>
        public virtual client_Company Company { get; set; } // FK_PostRetirementMedicalAidInvoiceHeader_RolePlayer

        /// <summary>
        /// Parent client_RolePlayer pointed by [PostRetirementMedicalAnnuityInvoiceHeader].([MedicalAidRolePlayerId]) (FK_PostRetirementMedicalAnnuityInvoiceHeader_RolePlayer)
        /// </summary>
        public virtual client_RolePlayer RolePlayer { get; set; } // FK_PostRetirementMedicalAnnuityInvoiceHeader_RolePlayer

        public policy_PostRetirementMedicalAnnuityInvoiceHeader()
        {
            IsDeleted = false;
            CreatedBy = "original_login()";
            CreatedDate = System.DateTime.Now;
            ModifiedBy = "original_login()";
            ModifiedDate = System.DateTime.Now;
            Allocations = new System.Collections.Generic.List<payment_Allocation>();
            PostRetirementMedicalAnnuityInvoiceDetails = new System.Collections.Generic.List<policy_PostRetirementMedicalAnnuityInvoiceDetail>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
