using System.ComponentModel.DataAnnotations;

namespace RMA.Service.MediCare.RuleTasks.Enums
{
    public enum UnderAssessReasonEnum
    {
        [Display(Name = "Invoice is a Duplicate")]
        invoiceIsADuplicate = 1,
        [Display(Name = "Line Item is a Duplicate")]
        lineItemIsADuplicate = 2,
        [Display(Name = "Line item rate exceeds the Agreed Tariff")]
        lineItemRateExceedsTheAgreedTariff = 3,
        [Display(Name = "Invoice Deleted by User, e.g. Capture Error")]
        invoiceDeletedByUser = 4,
        [Display(Name = "No Medical Cover")]
        noMedicalCover = 6,
        [Display(Name = "RMA does not have record of Dispensing Lic")]
        rmaDoesNotHaveRecordOfDispensingLic = 7,
        [Display(Name = "Claim Liability not accepted")]
        claimLiabilityNotAccepted = 1004,
        [Display(Name = "Employer liable, COIDA section 78")]
        employerLiableCOIDASection78 = 1016,
        [Display(Name = "Correct NHRPL Code Required")]
        correctNHRPLCodeRequired = 1029,
        [Display(Name = "Liability Pending claims documentation outstanding")]
        liabilityPendingClaimsDocumentationOutstanding = 1030,
        [Display(Name = "ICD10 code mismatch to claim ICD10")]
        icd10CodeMismatchToClaimICD10Reject = 1031,
        [Display(Name = "Service Date on Invoice is Future Dated")]
        serviceDateOnInvoiceIsFutureDated = 1035,
        [Display(Name = "Medical Report Required (First, Progress and Final)")]
        medicalReportRequiredFirstProgressAndFinal = 1037,
        [Display(Name = "HCP - Updated Registration Documents Required")]
        hcpUpdatedRegistrationDocumentsRequired = 1040,
        [Display(Name = "Correct COIDA Code Required")]
        correctCOIDACodeRequired = 1041,
        [Display(Name = "Reversal")]
        reversal = 1042,
        [Display(Name = "Treatment plan Required")]
        treatmentPlanRequired = 1043,
        [Display(Name = "Invoice Less than Franchised Amount contact the Employer")]
        invoiceLessThanFranchisedAmountContactTheEmployer = 1045,
        [Display(Name = "This Tariff Code is not covered under selected Preauthorization")]
        thisTariffCodeIsNotCoveredUnderSelectedPreauthorization = 1046,
        [Display(Name = "This Tariff Code is not covered under selected Preauthorization")]
        servicDateOnInvoiceIsPreAccidentDiagnoisDate = 1047,
        [Display(Name = "No Pre Auth Post 2 years of Injury")]
        noPreAuthPost2YearsOfInjury = 1051,
        [Display(Name = "No PreAuth and No Medical Report")]
        noPreAuthAndNoMedicalReport = 1054,
        [Display(Name = "The Quantity is not within authorised range")]
        theQuantityIsNotWithinAuthorisedRange = 1057,
        [Display(Name = "Medical Report not found for Treating Doctor")]
        medicalReportNotFoundForTreatingDoctor = 1058,
        [Display(Name = "Treating Doctor not authorised on PreAuthorisation")]
        treatingDoctorNotAuthorisedOnPreAuthorisation = 1059,
        [Display(Name = "Invoice is a statement")]
        InvoiceIsAStatement = 1060,
        [Display(Name = "No Pre-authorisation Obtained")]
        noPreAuthorisationObtained = 1061,
        [Display(Name = "Motivation Required")]
        motivationRequired = 1062,
        [Display(Name = "Medication Not Applicable to Treatment")]
        medicationNotApplicableToTreatment = 1063,
        [Display(Name = "Claim Repudiated")]
        claimRepudiated = 1068,
        [Display(Name = "Authorisation request Pending")]
        authorisationRequestPending = 1092,
        [Display(Name = "Service Date after Date of Death")]
        serviceDateAfterDateOfDeath = 2093,
        [Display(Name = "The practice is inactive")]
        thePracticeIsInactive = 2094,
        [Display(Name = "Invalid Tariff Code Submitted")]
        invalidTariffCodeSubmitted = 2096,
        [Display(Name = "Stale Invoice")]
        staleInvoice = 2097,
        [Display(Name = "Invoice under Review")]
        invoiceUnderReview = 2098,
        [Display(Name = "Technical Issue Logged")]
        technicalIssueLogged = 2100,
        [Display(Name = "This code will not be paid. It is mutually exclusive with another code for this date of service.")]
        thisCodeWillNotBePaidItIsMutuallyExclusiveWithAnotherCodeForThisDateOfService = 2101,
        [Display(Name = "ICD10Code not supplied on Invoice, ICD10Code is  mandatory.")]
        icd10CodeNotSuppliedOnInvoiceICD10CodeIsMandatory = 2102,
        [Display(Name = "ICD10Code supplied has invalid format.")]
        icd10CodeSuppliedHasInvalidFormat = 2103,
        [Display(Name = "ICD10Code supplied is not RMA Liability. (Inactive)")]
        icd10CodeSuppliedIsNotRMALiabilityInactive = 2104,
        [Display(Name = "Supplied ICD10 code does not match Claim ICD10 code")]
        icd10CodeMismatchToClaimICD10 = 2105,
        [Display(Name = "Claim/Person Event not found.")]
        claimPersonEventNotFound = 2106,
        [Display(Name = "ICD10 Codes exceeds the allowable length.")]
        icd10CodesExceedsTheAllowableLength = 2107,
        [Display(Name = "Treatment does not correlate with Injury reported")]
        treatmentDoesNotCorrelateWithInjuryReported = 2108,
        [Display(Name = "ICD10Code in same Category but different DRG on Claim.")]
        icd10CodeInSameCategoryButDifferentDRGOnClaim = 2109,
        [Display(Name = "Only external ICD10 cause code supplied.")]
        onlyExternalICD10CauseCodeSupplied = 2110,
        [Display(Name = "{0}")]
        ICD10Limit = 2111,
        [Display(Name = "The quantity on this line has been adjusted according to the authorised or approved quantity for this tariff code.")]
        theQuantityOnThisLineHasBeenAdjustedAccordingToTheAuthorisedOrApprovedQuantityForThisTariffCode = 2112,
        [Display(Name = "Line item quantity pay limit reached. Paid quantity is more than authorised pay limit.")]
        lineItemQuantityPayLimitReachedPaidQuantityIsMoreThanAuthorisedPayLimit = 2113,
        [Display(Name = "The invoice rejected for quantity on line has been adjusted to zero 0.00 according to the authorised or approved quantity.")]
        theInvoiceRejectedForQuantityOnLineHasBeenAdjustedToZeroAccordingToTheAuthorisedOrApprovedQuantity = 2114,
        [Display(Name = "Invoice has line items with different VAT percentages")]
        theInvoiceRejectedForDifferentVATPercentages = 2115,
        [Display(Name = "Invalid Date")]
        invalidDate = 2116,
        [Display(Name = "Service date before practice start date or after practice closed date")]
        serviceDateBeforePracticeStartDateOrAfterPracticeClosedDate = 2117,
        [Display(Name = "Medical Invoice is not active")]
        invoiceNotActive = 2118,
        [Display(Name = "Medical Invoice Requested Amount exceeds Allocated Amount")]
        invoiceAmountExceedsAllocatedAmount = 2119,
        [Display(Name = "Medical Invoice Payment Request failed")]
        invoicePaymentRequestFailed = 2120,
        [Display(Name = "Medical Invoice Amount Limit Reached")]
        TotAmtLimit = 2122,
        [Display(Name = "Medical Invoice Not STP")]
        IsNotSTP = 2123,
        [Display(Name = "Medical Invoice Totals not matching")]
        TotMisMatch = 2124,
        [Display(Name = "Medical Invoice does not have any line items")]
        InvNoLines = 2125,
        [Display(Name = "No Valid Lines captured on Invoice")]
        NoValidLines = 2129
    }
}
