//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.CampaignManager.Database.Entities;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;

namespace RMA.Service.Admin.CampaignManager.Database.Configuration
{
    public class campaign_SmsAuditConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<campaign_SmsAudit>
    {
        public campaign_SmsAuditConfiguration()
            : this("campaign")
        {
        }

        public campaign_SmsAuditConfiguration(string schema)
        {
            ToTable("SmsAudit", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.ItemType).HasColumnName(@"ItemType").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.ItemId).HasColumnName(@"ItemId").HasColumnType("int").IsOptional();
            Property(x => x.IsSuccess).HasColumnName(@"isSuccess").HasColumnType("bit").IsOptional();
            Property(x => x.SmsNumbers).HasColumnName(@"SmsNumbers").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
            Property(x => x.Message).HasColumnName(@"Message").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
            Property(x => x.ProcessDescription).HasColumnName(@"ProcessDescription").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
            Property(x => x.Department).HasColumnName(@"Department").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(100);
            Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType("bit").IsRequired();
            Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.SmsReference).HasColumnName(@"SmsReference").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.BusinessArea).HasColumnName(@"BusinessArea").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(100);
        }
    }

}
