//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.CampaignManager.Database.Entities;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;

namespace RMA.Service.Admin.CampaignManager.Database.Configuration
{
    public class campaign_SmsAuditDetailConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<campaign_SmsAuditDetail>
    {
        public campaign_SmsAuditDetailConfiguration()
            : this("campaign")
        {
        }

        public campaign_SmsAuditDetailConfiguration(string schema)
        {
            ToTable("SmsAuditDetail", schema);
            HasKey(x => x.SmsAuditDetailId);

            Property(x => x.SmsAuditDetailId).HasColumnName(@"SmsAuditDetailId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.RegistrationDate).HasColumnName(@"RegistrationDate").HasColumnType("datetime").IsRequired();
            Property(x => x.StatusReportDate).HasColumnName(@"StatusReportDate").HasColumnType("datetime").IsRequired();
            Property(x => x.SmsNumber).HasColumnName(@"SmsNumber").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(25);
            Property(x => x.SmsReference).HasColumnName(@"SmsReference").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.ErrorDescription).HasColumnName(@"ErrorDescription").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(250);
            Property(x => x.SmsAuditDetailStatusType).HasColumnName(@"SmsAuditDetailStatusTypeId").HasColumnType("int").IsOptional();
            Property(x => x.StatusDescription).HasColumnName(@"StatusDescription").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(250);
            Property(x => x.Operator).HasColumnName(@"Operator").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(20);
            Property(x => x.Campaign).HasColumnName(@"Campaign").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.Department).HasColumnName(@"Department").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.UserName).HasColumnName(@"UserName").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();
            Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.SmsAuditId).HasColumnName(@"SmsAuditId").HasColumnType("int").IsOptional();

            // Foreign keys
            HasOptional(a => a.SmsAudit).WithMany(b => b.SmsAuditDetails).HasForeignKey(c => c.SmsAuditId).WillCascadeOnDelete(false); // FK__SmsAuditD__SmsAu__6FAF37DE
        }
    }

}
