export enum AuthorityLimitItemTypeEnum {
    ClaimInvoiceOther = 1,
    ClaimInvoiceSundry = 2,
    ClaimInvoiceMedical = 3,
    ClaimInvoiceDaysOff = 4,
    ClaimInvoicePdAward = 5,
    ClaimInvoicePension = 6,
    ClaimInvoiceTravel = 7,
    ClaimInvoiceSpecialAllowance = 8,
    ClaimInvoiceSympathyAward = 9,
    ClaimInvoiceConstantAttendance = 10,
    ClaimInvoiceFamilyAllowance = 11,
	PreAuthorisationProsthetic = 12,
	PreAuthorisationChronicMedication = 13,
	PreAuthorisationTreatment = 14,
	PreAuthorisationHospitalization = 15,
	PreAuthorisationUnknown = 16,
	PreAuthorisationBulkTreatmentAuth = 17,
	PreAuthorisationTreatingDoctor = 18,
	PreAuthorisationPhysioOTAuth = 19,
	PreAuthorisationTravelAuth = 20
}
