//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.ScanCare.Database.Entities;

namespace RMA.Service.ScanCare.Database.Configuration
{
    public class documents_DocumentClassificationPatternConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<documents_DocumentClassificationPattern>
    {
        public documents_DocumentClassificationPatternConfiguration()
            : this("documents")
        {
        }

        public documents_DocumentClassificationPatternConfiguration(string schema)
        {
            ToTable("DocumentClassificationPattern", schema);
            HasKey(x => x.PatternId);

            Property(x => x.PatternId).HasColumnName(@"PatternId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Pattern).HasColumnName(@"Pattern").HasColumnType("nvarchar").IsRequired().HasMaxLength(400);
            Property(x => x.IsRegex).HasColumnName(@"IsRegex").HasColumnType("bit").IsRequired();
            Property(x => x.Weight).HasColumnName(@"Weight").HasColumnType("int").IsRequired();
            Property(x => x.DocumentSystemNameId).HasColumnName(@"DocumentSystemNameId").HasColumnType("int").IsRequired();
            Property(x => x.DocumentType).HasColumnName(@"DocumentTypeId").HasColumnType("int").IsRequired();
            Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType("bit").IsRequired();
            Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType("datetime2").IsOptional();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("nvarchar").IsOptional().HasMaxLength(256);
            Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime2").IsOptional();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("nvarchar").IsOptional().HasMaxLength(256);
            Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();

            // Foreign keys
            HasRequired(a => a.DocumentSystemName).WithMany(b => b.DocumentClassificationPatterns).HasForeignKey(c => c.DocumentSystemNameId).WillCascadeOnDelete(false); // FK_Pattern_DocumentSystemName
        }
    }

}
