//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.ScanCare.Database.Entities;

namespace RMA.Service.ScanCare.Database.Configuration
{
    public class documents_DocumentConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<documents_Document>
    {
        public documents_DocumentConfiguration()
            : this("documents")
        {
        }

        public documents_DocumentConfiguration(string schema)
        {
            ToTable("Document", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.DocTypeId).HasColumnName(@"DocTypeId").HasColumnType("int").IsRequired();
            Property(x => x.SystemName).HasColumnName(@"SystemName").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.DocumentUri).HasColumnName(@"DocumentUri").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(1024);
            Property(x => x.VerifiedBy).HasColumnName(@"verifiedBy").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.VerifiedByDate).HasColumnName(@"verifiedByDate").HasColumnType("datetime").IsOptional();
            Property(x => x.FileHash).HasColumnName(@"FileHash").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.FileName).HasColumnName(@"FileName").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(255);
            Property(x => x.FileExtension).HasColumnName(@"FileExtension").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.DocumentStatus).HasColumnName(@"DocumentStatusId").HasColumnType("int").IsOptional();
            Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.DocumentDescription).HasColumnName(@"DocumentDescription").HasColumnType("nvarchar").IsOptional().HasMaxLength(150);
            Property(x => x.IsMemberVisible).HasColumnName(@"IsMemberVisible").HasColumnType("bit").IsRequired();

            // Foreign keys
            HasRequired(a => a.DocumentType).WithMany(b => b.Documents).HasForeignKey(c => c.DocTypeId).WillCascadeOnDelete(false); // FK_Document_DocumentType
        }
    }

}
