CREATE TABLE [billing].[Transactions_bck] (
    [TransactionId]               INT             IDENTITY (1, 1) NOT NULL,
    [InvoiceId]                   INT             NULL,
    [RolePlayerId]                INT             NOT NULL,
    [BankStatementEntryId]        INT             NULL,
    [TransactionTypeLinkId]       INT             NOT NULL,
    [Amount]                      DECIMAL (18, 2) NOT NULL,
    [TransactionDate]             DATETIME        NOT NULL,
    [BankReference]               VARCHAR (50)    NULL,
    [TransactionTypeId]           INT             NOT NULL,
    [Reason]                      VARCHAR (255)   NULL,
    [RmaReference]                VARCHAR (100)   NULL,
    [LinkedTransactionId]         INT             NULL,
    [ClaimRecoveryInvoiceId]      INT             NULL,
    [IsLogged]                    BIT             NULL,
    [AdhocPaymentInstructionId]   INT             NULL,
    [IsReAllocation]              BIT             NULL,
    [Balance]                     DECIMAL (18, 2) NULL,
    [PremiumListingTransactionId] INT             NULL,
    [DeletedReasonId]             INT             NULL,
    [IsDeleted]                   BIT             NOT NULL,
    [CreatedDate]                 DATETIME        NOT NULL,
    [CreatedBy]                   VARCHAR (50)    NOT NULL,
    [ModifiedBy]                  VARCHAR (50)    NOT NULL,
    [ModifiedDate]                DATETIME        NOT NULL,
    [OpenPeriodPostingDate]       DATETIME        NULL,
    [TransactionReasonId]         INT             NULL,
    [IsBackDated]                 BIT             NULL,
    [TransactionEffectiveDate]    DATETIME        NULL
);

