export enum CommutationReasonEnum {
  OverpaymentbyTeba = 1,
  PurchaseHouse = 2,
  BuildingofHouse = 3,
  PurchaseofMotor = 4,
  Vehicle = 5,
  MotorVehicleRepairs = 6,
  SettlementofVehicle = 7,
  Finance = 8,
  ExtensionstoHouse = 9,
  RenovationsRepairstoHouse = 10,
  FuneralExpenses = 11,
  SchoolTertiary = 12,
  EducationFees = 13,
  SettlementofDebt = 14,
  SettlementofTax = 15,
  Liability = 16,
  MedicalExpenses = 17,
  SettlementofBond = 18,
  Other = 19
}
