import { RolePlayerTypeEnum } from './../../../../../../shared-models-lib/src/lib/enums/role-player-type-enum';
import { Person } from './person';
import { Note } from 'projects/shared-components-lib/src/lib/notes/note';
import { RolePlayerAddress } from './role-player-address';
import { RolePlayerPolicy } from './role-player-policy';
import { RolePlayerRelation } from './roleplayer-relation';
import { RolePlayerBenefit } from './role-player-benefit';
import { BodyCollector } from './body-collector';
import { FuneralParlor } from './funeral-parlor';
import { Company } from './company';
import { ForensicPathologist } from './forensic-pathologist';
import { InformantModel } from 'projects/claimcare/src/app/claim-manager/shared/entities/funeral/informant.model';
import { ClaimantModel } from 'projects/claimcare/src/app/claim-manager/shared/entities/funeral/claimant.model';
import { PreviousInsurerRolePlayer } from './previous-insurer-roleplayer';
import { RolePlayerContact } from '../../../member-manager/models/roleplayer-contact';
import { FinPayee } from './fin-payee';
import { NatureOfBusiness } from '../../../member-manager/models/nature-of-business';
import { RolePlayerIdentificationTypeEnum } from 'projects/shared-models-lib/src/lib/enums/roleplayer-identification-type-enum';
import { RolePlayerBenefitWaitingPeriodEnum } from '../enums/roleplayer-benefit-waiting-period.enum';
import { ClientVopdResponse } from './vopd-response';
import { ClientTypeEnum } from '../enums/client-type-enum';
import { RolePlayerBankingDetail } from 'projects/shared-components-lib/src/lib/models/banking-details.model';
import { Undertaker } from './undertaker';
import { MemberStatusEnum } from 'projects/shared-models-lib/src/lib/enums/member-status-enum';
import { HealthCareProviderModel } from './healthare-provider-model';

export class RolePlayer {
  rolePlayerId: number;
  displayName: string;
  tellNumber: string;
  cellNumber: string;
  emailAddress: string;
  preferredCommunicationTypeId: number;
  rolePlayerIdentificationType: RolePlayerIdentificationTypeEnum;
  isDeleted: boolean;
  createdBy: string;
  createdDate: Date;
  modifiedBy: string;
  modifiedDate: Date;
  policy: RolePlayerPolicy = new RolePlayerPolicy();
  caseTypeId: number;
  representativeId: number;
  accountExecutiveId: number;
  productId: number;
  company: Company;
  rolePlayerBankingDetails: RolePlayerBankingDetail[];
  rolePlayerAddresses: RolePlayerAddress[];
  person: Person;
  claimant: ClaimantModel;
  informant: InformantModel;
  healthCareProvider: HealthCareProviderModel;
  forensicPathologist: ForensicPathologist;
  funeralParlor: FuneralParlor;
  undertaker: Undertaker;
  bodyCollector: BodyCollector;
  rolePlayerNotes: Note[];
  fromRolePlayers: RolePlayerRelation[] = [];
  toRolePlayers: RolePlayerRelation[] = [];
  benefits: RolePlayerBenefit[];
  policies: RolePlayerPolicy[];
  policyPayees: RolePlayerPolicy[];
  rolePlayerPolicy: RolePlayerPolicy;
  isVopdRequired: boolean;
  insuredLifeRemovalReason: number;
  endDate: Date;
  keyRoleTypeId: number;
  keyRoleType: string;
  joinDate: Date;
  rolePlayerTypeId: number;
  rolePlayerType: RolePlayerTypeEnum;
  previousInsurerRolePlayers: PreviousInsurerRolePlayer[] = [];
  rolePlayerContacts: RolePlayerContact[] = [];
  finPayee: FinPayee;
  natureOfBusiness: NatureOfBusiness = new NatureOfBusiness();
  policyNumber: string;
  rolePlayerBenefitWaitingPeriod: RolePlayerBenefitWaitingPeriodEnum;
  clientVopdResponse: ClientVopdResponse;
  clientType: ClientTypeEnum;
  memberStatus: MemberStatusEnum;

  hasActiveCoidPolicies: boolean;
  hasActiveFuneralPolicies: boolean;
  hasActiveVapsPolicies: boolean;
}
