//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.Admin.SecurityManager.Contracts.Enums;

namespace RMA.Service.Admin.SecurityManager.Database.Entities
{
    public partial class security_Application : ILazyLoadSafeEntity
    {
        public string ApplicationId { get; set; } // ApplicationID (Primary key) (length: 128)
        public string DisplayName { get; set; } // DisplayName
        public string RedirectUri { get; set; } // RedirectUri
        public string LogoutRedirectUri { get; set; } // LogoutRedirectUri
        public string Secret { get; set; } // Secret
        public int ApplicationType { get; set; } // ApplicationType
        public bool IntrospectionAllowed { get; set; } // IntrospectionAllowed

        public security_Application()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
