CREATE TABLE [medical].[Address_Temp] (
    [AddressId]         INT           IDENTITY (1, 1) NOT NULL,
    [AddressTypeId]     INT           NOT NULL,
    [OwnerId]           INT           NOT NULL,
    [OwnerType]         TINYINT       NOT NULL,
    [IsSouthAfrican]    BIT           NULL,
    [CareOff]           VARCHAR (100) NULL,
    [Address1]          VARCHAR (255) NULL,
    [Address2]          VARCHAR (255) NULL,
    [Address3]          VARCHAR (255) NULL,
    [Address4]          VARCHAR (255) NULL,
    [City]              VARCHAR (255) NULL,
    [Suburb]            VARCHAR (255) NULL,
    [ForeignPostalCode] VARCHAR (20)  NULL,
    [ForeignCityId]     INT           NULL,
    [CountryId]         INT           NULL,
    [IsAuthorised]      BIT           NULL,
    [PostalCode]        VARCHAR (12)  NULL,
    [IsActive]          BIT           NOT NULL,
    [IsDeleted]         BIT           NOT NULL,
    [CreatedBy]         VARCHAR (50)  NOT NULL,
    [CreatedDate]       DATETIME      NOT NULL,
    [ModifiedBy]        VARCHAR (50)  NOT NULL,
    [ModifiedDate]      DATETIME      NOT NULL,
    CONSTRAINT [PK_Medical_Address_Temp_AddressId] PRIMARY KEY CLUSTERED ([AddressId] ASC) WITH (FILLFACTOR = 90, PAD_INDEX = ON),
    CONSTRAINT [FK_Medical_Address_Temp_AddressTypeId] FOREIGN KEY ([AddressTypeId]) REFERENCES [common].[AddressType] ([Id]),
    CONSTRAINT [FK_Medical_Address_Temp_CountryId] FOREIGN KEY ([CountryId]) REFERENCES [common].[Country] ([Id])
);

