CREATE TABLE [medical].[BHFSource_Temp] (
    [Practice_No]              VARCHAR (255) NULL,
    [Reg_Country_Code]         VARCHAR (255) NULL,
    [Partner_No]               VARCHAR (255) NULL,
    [Personal_Practice_No]     VARCHAR (255) NULL,
    [Practice_Discipline]      VARCHAR (255) NULL,
    [Practice_Sub_Discipline]  VARCHAR (255) NULL,
    [Provider_Discipline]      VARCHAR (255) NULL,
    [Provider_Sub_Discipline]  VARCHAR (255) NULL,
    [Practice_Type]            VARCHAR (255) NULL,
    [Num_Partners]             VARCHAR (255) NULL,
    [Practice_Name]            VARCHAR (255) NULL,
    [Title]                    VARCHAR (255) NULL,
    [Surname]                  VARCHAR (255) NULL,
    [Initials]                 VARCHAR (255) NULL,
    [First_Name]               VARCHAR (255) NULL,
    [Id_No]                    VARCHAR (255) NULL,
    [Number_Type]              VARCHAR (255) NULL,
    [Inc_Co]                   VARCHAR (255) NULL,
    [Trading Name]             VARCHAR (255) NULL,
    [Co_Reg_No]                VARCHAR (255) NULL,
    [Dispensing]               VARCHAR (255) NULL,
    [Dispensing Date]          VARCHAR (255) NULL,
    [Active_Flag]              VARCHAR (255) NULL,
    [Council_No]               VARCHAR (255) NULL,
    [Registration_Date]        VARCHAR (255) NULL,
    [Date_Effective]           VARCHAR (255) NULL,
    [Last_Update]              VARCHAR (255) NULL,
    [Last_Action]              VARCHAR (255) NULL,
    [Change_Code]              VARCHAR (255) NULL,
    [Reason_Code]              VARCHAR (255) NULL,
    [Reason_Xref]              VARCHAR (255) NULL,
    [Reason_Code1]             VARCHAR (255) NULL,
    [Change_Code1]             VARCHAR (255) NULL,
    [Tel_No]                   VARCHAR (255) NULL,
    [Emergency_Tel_No]         VARCHAR (255) NULL,
    [Fax_Number]               VARCHAR (255) NULL,
    [E_Mail_Adr]               VARCHAR (255) NULL,
    [Post_Addr1]               VARCHAR (255) NULL,
    [Post_Addr2]               VARCHAR (255) NULL,
    [Post_Addr3]               VARCHAR (255) NULL,
    [Post_Town]                VARCHAR (255) NULL,
    [Post_Code]                VARCHAR (255) NULL,
    [Postal_Province_Code]     VARCHAR (255) NULL,
    [Post_CountryCode]         VARCHAR (255) NULL,
    [Phys_Addr1]               VARCHAR (255) NULL,
    [Phys_Addr2]               VARCHAR (255) NULL,
    [Phys_Addr3]               VARCHAR (255) NULL,
    [Phys_Town]                VARCHAR (255) NULL,
    [Physical_Province_Code]   VARCHAR (255) NULL,
    [Phys_CountryCode]         VARCHAR (255) NULL,
    [EDI_User]                 VARCHAR (255) NULL,
    [EDI_VAN]                  VARCHAR (255) NULL,
    [Bank_Code]                VARCHAR (255) NULL,
    [Bank_Branch]              VARCHAR (255) NULL,
    [Bank_Branch_Code]         VARCHAR (255) NULL,
    [Bank_Account No]          VARCHAR (255) NULL,
    [Account_Type]             VARCHAR (255) NULL,
    [Pay_Method]               VARCHAR (255) NULL,
    [Cancelled_Cheque]         VARCHAR (255) NULL,
    [DB_Id]                    VARCHAR (255) NULL,
    [Sect22A_Permit_ExpDate]   VARCHAR (255) NULL,
    [Sect22A_Permit]           VARCHAR (255) NULL,
    [Hosp_Insp_ExpDate]        VARCHAR (255) NULL,
    [Hosp_Insp]                VARCHAR (255) NULL,
    [Account_Name]             VARCHAR (255) NULL,
    [VAT_Reg]                  VARCHAR (255) NULL,
    [VAT_No]                   VARCHAR (255) NULL,
    [Prev_Status]              VARCHAR (255) NULL,
    [MedicalServiceProviderID] INT           NULL,
    [IsActive]                 BIT           NOT NULL,
    [IsDeleted]                BIT           NOT NULL,
    [CreatedBy]                VARCHAR (50)  NOT NULL,
    [CreatedDate]              DATETIME      NOT NULL,
    [ModifiedBy]               VARCHAR (50)  NOT NULL,
    [ModifiedDate]             DATETIME      NOT NULL
);

