CREATE TABLE [medical].[ChronicMedicationFormRenewal] (
    [ChronicMedicationFormRenewalId]   INT            IDENTITY (1, 1) NOT NULL,
    [ClaimId]                          INT            NOT NULL,
    [MedicalServiceProviderId]         INT            NOT NULL,
    [Description]                      VARCHAR (2048) NOT NULL,
    [IsNeurogenicPain]                 BIT            NULL,
    [IsMechanicalPain]                 BIT            NULL,
    [IsDegenerativePain]               BIT            NULL,
    [IsPsychogenicPain]                BIT            NULL,
    [IsMuslcespasmPain]                BIT            NULL,
    [IsFibromialgiaPain]               BIT            NULL,
    [PainEvaluation]                   TINYINT        NOT NULL,
    [ContinuousDuration]               TINYINT        NOT NULL,
    [IsLifeStyleChanges]               BIT            NULL,
    [IsPhysiotherapy]                  BIT            NULL,
    [IsNerveBlock]                     BIT            NULL,
    [IsArthroplasty]                   BIT            NULL,
    [IsPsychotherapy]                  BIT            NULL,
    [IsAccupuncture]                   BIT            NULL,
    [DateSubmitted]                    DATETIME       NULL,
    [DateConsulted]                    DATETIME       NULL,
    [IsActive]                         BIT            NOT NULL,
    [Hobbies]                          VARCHAR (50)   NULL,
    [DeliveryMethod]                   TINYINT        NULL,
    [PreAuthId]                        INT            NULL,
    [DeliveryAddress]                  VARCHAR (1000) NULL,
    [IsSignedByHCP]                    BIT            NULL,
    [DateSignedByHCP]                  DATETIME       NULL,
    [AuthorisedChronicAuthorisationId] INT            NULL,
    [IsDeleted]                        BIT            NOT NULL,
    [CreatedBy]                        VARCHAR (50)   NOT NULL,
    [CreatedDate]                      DATETIME       NOT NULL,
    [ModifiedBy]                       VARCHAR (50)   NOT NULL,
    [ModifiedDate]                     DATETIME       NOT NULL,
    CONSTRAINT [PK_ChronicMedicationFormRenewal] PRIMARY KEY CLUSTERED ([ChronicMedicationFormRenewalId] ASC) WITH (FILLFACTOR = 90, PAD_INDEX = ON),
    CONSTRAINT [FK_Medical_ChronicMedicationFormRenewal_Claim] FOREIGN KEY ([ClaimId]) REFERENCES [claim].[Claim] ([ClaimId]),
    CONSTRAINT [FK_Medical_ChronicMedicationFormRenewal_HealthCareProvider] FOREIGN KEY ([MedicalServiceProviderId]) REFERENCES [medical].[HealthCareProvider] ([RolePlayerId]),
    CONSTRAINT [FK_Medical_ChronicMedicationFormRenewal_PreAuthId] FOREIGN KEY ([PreAuthId]) REFERENCES [medical].[PreAuthorisation] ([PreAuthId])
);

