CREATE TABLE [medical].[ChronicMedicationForm] (
    [ChronicMedicationFormId]  INT            IDENTITY (1, 1) NOT NULL,
    [ClaimId]                  INT            NOT NULL,
    [IsSignedByApplicant]      BIT            NULL,
    [Height]                   DECIMAL (5, 2) NULL,
    [Weight]                   DECIMAL (5, 2) NULL,
    [BloodPressure]            VARCHAR (6)    NULL,
    [Urine]                    VARCHAR (50)   NULL,
    [Allergies]                VARCHAR (50)   NULL,
    [HIVStatus]                VARCHAR (50)   NULL,
    [Description]              VARCHAR (2048) NULL,
    [DateFormFilled]           DATETIME       NULL,
    [DateSubmitted]            DATETIME       NULL,
    [DateConsulted]            DATETIME       NULL,
    [MedicalServiceProviderId] INT            NULL,
    [IsActive]                 BIT            DEFAULT ((1)) NOT NULL,
    [DeliveryMethod]           TINYINT        NULL,
    [Hobbies]                  VARCHAR (50)   NULL,
    [PreAuthId]                INT            NULL,
    [DeliveryAddress]          VARCHAR (1000) NULL,
    [IsSignedByHCP]            BIT            NULL,
    [DateSignedByHCP]          DATETIME       NULL,
    [IsDeleted]                BIT            DEFAULT ((0)) NOT NULL,
    [CreatedBy]                VARCHAR (50)   NOT NULL,
    [CreatedDate]              DATETIME       DEFAULT (getdate()) NOT NULL,
    [ModifiedBy]               VARCHAR (50)   NOT NULL,
    [ModifiedDate]             DATETIME       NOT NULL,
    CONSTRAINT [PK_ChronicMedicationForm] PRIMARY KEY CLUSTERED ([ChronicMedicationFormId] ASC) WITH (FILLFACTOR = 90, PAD_INDEX = ON),
    CONSTRAINT [FK_Medical_ChronicMedicationForm_PreAuthId] FOREIGN KEY ([PreAuthId]) REFERENCES [medical].[PreAuthorisation] ([PreAuthId])
);

