CREATE TABLE [medical].[ClinicBooking] (
    [ClinicBookingId]  INT            IDENTITY (1, 1) NOT NULL,
    [ClinicScheduleId] INT            NULL,
    [PersonId]         INT            NOT NULL,
    [ClaimId]          INT            NULL,
    [Confirmed]        BIT            NOT NULL,
    [FileSent]         BIT            NOT NULL,
    [HasAttended]      BIT            NOT NULL,
    [FileReturned]     BIT            NOT NULL,
    [BookingReason]    VARCHAR (2000) NULL,
    [BookingForStatus] TINYINT        NULL,
    [BookingStatus]    TINYINT        NULL,
    [IsActive]         INT            NOT NULL,
    [IsApproved]       BIT            CONSTRAINT [DF_ClinicBooking_Temp_IsApproved] DEFAULT ((0)) NULL,
    [ApprovedBy]       VARCHAR (30)   NULL,
    [IsRejected]       BIT            CONSTRAINT [DF_ClinicBooking_Temp_IsRejected] DEFAULT ((0)) NULL,
    [RejectedBy]       VARCHAR (30)   NULL,
    [RejectedReason]   VARCHAR (2000) NULL,
    [IsAuthorised]     BIT            NULL,
    [IsDeleted]        BIT            NOT NULL,
    [CreatedBy]        VARCHAR (50)   NOT NULL,
    [CreatedDate]      DATETIME       NOT NULL,
    [ModifiedBy]       VARCHAR (50)   NOT NULL,
    [ModifiedDate]     DATETIME       NOT NULL,
    CONSTRAINT [PK_Medical_ClinicBooking_Temp_ClinicBookingId] PRIMARY KEY CLUSTERED ([ClinicBookingId] ASC) WITH (FILLFACTOR = 90, PAD_INDEX = ON),
    CONSTRAINT [FK_Medical_ClinicBooking_Temp_ClinicScheduleId] FOREIGN KEY ([ClinicScheduleId]) REFERENCES [medical].[ClinicSchedule] ([ClinicScheduleId]),
    CONSTRAINT [FK_Medical_ClinicBooking_Temp_PersonId] FOREIGN KEY ([PersonId]) REFERENCES [client].[RolePlayer] ([RolePlayerId])
);

