CREATE TABLE [medical].[InvoiceAllocation_Temp] (
    [InvoiceAllocationID]  INT           IDENTITY (1, 1) NOT NULL,
    [ClaimID]              INT           NOT NULL,
    [SundryInvoiceID]      INT           NULL,
    [MedicalInvoiceID]     INT           NULL,
    [DaysOffInvoiceID]     INT           NULL,
    [PDAwardID]            INT           NULL,
    [BeneficiaryPensionID] INT           NULL,
    [OtherBenefitAwardID]  INT           NULL,
    [PayeeID]              INT           NOT NULL,
    [PayeeTypeID]          INT           NOT NULL,
    [PaymentMethodID]      INT           NOT NULL,
    [PayeeName]            VARCHAR (200) NULL,
    [PercentageAllocation] DECIMAL (18)  NULL,
    [AssessedAmount]       DECIMAL (18)  NOT NULL,
    [AssessedVAT]          DECIMAL (18)  NOT NULL,
    [AssessedDays]         DECIMAL (18)  NULL,
    [AssessedAwardPerc]    DECIMAL (18)  NULL,
    [VATPercentage]        DECIMAL (18)  NULL,
    [ClaimFileRefNumber]   VARCHAR (50)  NULL,
    [ProductCodeID]        INT           NULL,
    [BenefitCodeID]        INT           NULL,
    [VatCodeID]            INT           NOT NULL,
    [AllocationStatusID]   INT           NOT NULL,
    [InvoiceTypeID]        INT           NOT NULL,
    [InvoiceID]            INT           NOT NULL,
    [Description]          VARCHAR (200) NULL,
    [Processed]            BIT           NULL,
    [CalcOperands]         VARCHAR (200) NULL,
    [AssessedAmountIncl]   AS            ([AssessedAmount]+[AssessedVAT]),
    [IsActive]             BIT           NOT NULL,
    [IsDeleted]            BIT           NOT NULL,
    [CreatedBy]            VARCHAR (50)  NOT NULL,
    [CreatedDate]          DATETIME      NOT NULL,
    [ModifiedBy]           VARCHAR (50)  NOT NULL,
    [ModifiedDate]         DATETIME      NOT NULL,
    CONSTRAINT [PK_Medical_InvoiceAllocation_InvoiceAllocationID] PRIMARY KEY CLUSTERED ([InvoiceAllocationID] ASC) WITH (FILLFACTOR = 95),
    CONSTRAINT [FK_InvoiceAllocation_PDAward] FOREIGN KEY ([PDAwardID]) REFERENCES [claim].[PDAward] ([PDAwardId]),
    CONSTRAINT [FK_Medical_InvoiceAllocation_AllocationStatusID] FOREIGN KEY ([AllocationStatusID]) REFERENCES [common].[AllocationProgressStatus] ([Id]),
    CONSTRAINT [FK_Medical_InvoiceAllocation_BenefitCodeID] FOREIGN KEY ([BenefitCodeID]) REFERENCES [product].[Benefit] ([Id]),
    CONSTRAINT [FK_Medical_InvoiceAllocation_ClaimID] FOREIGN KEY ([ClaimID]) REFERENCES [claim].[Claim] ([ClaimId]),
    CONSTRAINT [FK_Medical_InvoiceAllocation_PaymentMethodID] FOREIGN KEY ([PaymentMethodID]) REFERENCES [common].[PaymentMethod] ([Id]),
    CONSTRAINT [FK_Medical_InvoiceAllocation_ProductCodeID] FOREIGN KEY ([ProductCodeID]) REFERENCES [product].[Product] ([Id]),
    CONSTRAINT [FK_Medical_InvoiceAllocation_VATCodeID] FOREIGN KEY ([VatCodeID]) REFERENCES [common].[VatCode] ([Id])
);


GO
ALTER TABLE [medical].[InvoiceAllocation_Temp] NOCHECK CONSTRAINT [FK_Medical_InvoiceAllocation_ClaimID];

