CREATE TABLE [medical].[Invoice_POPI] (
    [InvoiceId]                INT             IDENTITY (1, 1) NOT NULL,
    [ClaimId]                  INT             NULL,
    [PersonEventId]            INT             NULL,
    [HealthCareProviderId]     INT             NOT NULL,
    [HCPInvoiceNumber]         VARCHAR (50)    NULL,
    [HCPAccountNumber]         VARCHAR (50)    NULL,
    [InvoiceNumber]            VARCHAR (50)    NULL,
    [InvoiceDate]              DATETIME        NOT NULL,
    [DateSubmitted]            DATETIME        NULL,
    [DateReceived]             DATETIME        NULL,
    [DateAdmitted]             DATETIME        NULL,
    [DateDischarged]           DATETIME        NULL,
    [PreAuthId]                INT             NULL,
    [InvoiceStatusId]          INT             NOT NULL,
    [InvoiceAmount]            DECIMAL (18, 2) NOT NULL,
    [InvoiceVAT]               DECIMAL (18, 2) NOT NULL,
    [InvoiceTotalInclusive]    DECIMAL (19, 2) NULL,
    [AuthorisedAmount]         DECIMAL (18, 2) NOT NULL,
    [AuthorisedVAT]            DECIMAL (18, 2) NOT NULL,
    [AuthorisedTotalInclusive] DECIMAL (19, 2) NULL,
    [PayeeID]                  INT             NOT NULL,
    [PayeeTypeID]              INT             NOT NULL,
    [UnderAssessedComments]    VARCHAR (2048)  NULL,
    [SwitchBatchInvoiceID]     INT             NULL,
    [HoldingKey]               VARCHAR (50)    NULL,
    [IsPaymentDelay]           BIT             NOT NULL,
    [IsPreauthorised]          BIT             NOT NULL,
    [PreAuthXML]               XML             NULL,
    [Comments]                 VARCHAR (2000)  NULL,
    [IsActive]                 BIT             NOT NULL,
    [IsDeleted]                BIT             NOT NULL,
    [CreatedBy]                VARCHAR (50)    NOT NULL,
    [CreatedDate]              DATETIME        NOT NULL,
    [ModifiedBy]               VARCHAR (50)    NOT NULL,
    [ModifiedDate]             DATETIME        NOT NULL
);

