CREATE TABLE [medical].[MedicalServiceProviderBFBHFBackup_Temp] (
    [MedicalServiceProviderId]       INT            IDENTITY (1, 1) NOT NULL,
    [Name]                           VARCHAR (80)   NOT NULL,
    [Description]                    VARCHAR (2048) NULL,
    [PracticeNo]                     VARCHAR (50)   NOT NULL,
    [DatePracticeStarted]            DATETIME       NULL,
    [DatePracticeClosed]             DATETIME       NULL,
    [PractitionerTypeID]             INT            NOT NULL,
    [IsVat]                          TINYINT        NOT NULL,
    [VATRegNumber]                   VARCHAR (50)   NULL,
    [ConsultingPartnerType]          INT            NULL,
    [IsPreferred]                    TINYINT        NOT NULL,
    [IsMedInvTreatmentInfoProvided]  TINYINT        NOT NULL,
    [IsMedInvInjuryInfoProvided]     TINYINT        NOT NULL,
    [IsMineHospital]                 TINYINT        NOT NULL,
    [IsNeedTreatments]               TINYINT        NOT NULL,
    [ArmType]                        INT            NULL,
    [ArmCode]                        VARCHAR (12)   NULL,
    [CreateTime]                     DATETIME       NOT NULL,
    [FinSystemSynchStatusID]         INT            NOT NULL,
    [MSPGroupID]                     INT            NOT NULL,
    [DispensingLicenseNo]            VARCHAR (50)   NULL,
    [AcuteMedicalAuthNeededTypeID]   INT            NULL,
    [ChronicMedicalAuthNeededTypeID] INT            NULL,
    [IsAllowSameDayTreatment]        TINYINT        NOT NULL,
    [LastChangedBy]                  VARCHAR (30)   NOT NULL,
    [LastChangedDate]                DATETIME       NOT NULL,
    [AgreementEndDate]               DATETIME       NULL,
    [AgreementStartDate]             DATETIME       NULL,
    [IsAuthorised]                   TINYINT        NULL,
    [AgreementType]                  TINYINT        NULL,
    [IsActive]                       BIT            DEFAULT ((1)) NOT NULL,
    [IsDeleted]                      BIT            DEFAULT ((0)) NOT NULL,
    [CreatedBy]                      VARCHAR (50)   NOT NULL,
    [CreatedDate]                    DATETIME       DEFAULT (getdate()) NOT NULL,
    [ModifiedBy]                     VARCHAR (50)   NOT NULL,
    [ModifiedDate]                   DATETIME       NOT NULL
);

