CREATE TABLE [medical].[PMPRegionTransfer] (
    [PMPRegionTransferId]      INT                                                 IDENTITY (1, 1) NOT NULL,
    [ClaimId]                  INT                                                 NOT NULL,
    [HealthCareProviderId] INT                                                 NOT NULL,
    [IsUDS]                    BIT                                                 NULL,
    [IsSpousalTraining]        BIT                                                 NULL,
    [DateOfTransfer]           DATETIME                                            NULL,
    [ExpDateOfArrival]         DATETIME                                            NOT NULL,
    [DateOfReferral]           DATETIME                                            NULL,
    [PassportVisaRenewalDate]  DATETIME                                            NULL,
    [ConfDateOfArrival]        DATETIME                                            NULL,
    [ReferringMCAId]           INT                                                 NOT NULL,
    [ReceivingMCAId]           INT                                                 NOT NULL,
    [ReferringPAId]            INT                                                 NOT NULL,
    [ReceivingPAId]            INT                                                 NOT NULL,
    [ReferringPMPRegionId]     INT                                                 NOT NULL,
    [ReceivingPMPRegionId]     INT                                                 NOT NULL,
    [Comments]                 VARCHAR (2048) MASKED WITH (FUNCTION = 'default()') NOT NULL,
    [ReasonForReferral]        VARCHAR (2048) MASKED WITH (FUNCTION = 'default()') NULL,
    [TreatmentReceived]        VARCHAR (2048) MASKED WITH (FUNCTION = 'default()') NULL,
    [Daigonsis]                VARCHAR (2048) MASKED WITH (FUNCTION = 'default()') NULL,
    [MedicationSundriesIssued] VARCHAR (2048) MASKED WITH (FUNCTION = 'default()') NULL,
    [IssuedDate]               VARCHAR (2048)                                      NULL,
    [IssuedMonth]              SMALLINT                                            NULL,
    [IsAcute]                  BIT                                                 DEFAULT ((0)) NOT NULL,
    [IsActive]                 BIT                                                 DEFAULT ((1)) NOT NULL,
    [IsDeleted]                BIT                                                 DEFAULT ((0)) NOT NULL,
    [CreatedBy]                VARCHAR (50)                                        NOT NULL,
    [CreatedDate]              DATETIME                                            DEFAULT (getdate()) NOT NULL,
    [ModifiedBy]               VARCHAR (50)                                        NOT NULL,
    [ModifiedDate]             DATETIME                                            NOT NULL,
    CONSTRAINT [PK_medical_PMPRegionTransfer] PRIMARY KEY CLUSTERED ([PMPRegionTransferId] ASC) WITH (FILLFACTOR = 90, PAD_INDEX = ON),
    CONSTRAINT [FK_PMPRegionTransfer_Claim] FOREIGN KEY ([ClaimId]) REFERENCES [claim].[Claim] ([ClaimId]),
    CONSTRAINT [FK_PMPRegionTransfer_HealthCareProvider] FOREIGN KEY ([HealthCareProviderId]) REFERENCES [medical].[HealthCareProvider] ([RolePlayerId])
);

