CREATE TABLE [medical].[ProsthetistQuote] (
    [ProsthetistQuoteId]      INT                                                 IDENTITY (1, 1) NOT NULL,
    [RolePlayerId]            INT                                                 NOT NULL,
    [ProsthetistId]           INT                                                 NULL,
    [PensionCaseId]           INT                                                 NULL,
    [ClaimId]                 INT                                                 NOT NULL,
    [QuotationAmount]         MONEY MASKED WITH (FUNCTION = 'default()')          NULL,
    [Comments]                VARCHAR (2000) MASKED WITH (FUNCTION = 'default()') NULL,
    [ProstheticTypeId]        INT                                                 NOT NULL,
    [ProsTypeSpecification]   VARCHAR (200)                                       NULL,
    [IsApproved]              BIT                                                 NULL,
    [ReviewedBy]              INT MASKED WITH (FUNCTION = 'default()')            NULL,
    [ReviewedDateTime]        DATETIME                                            NULL,
    [ReviewedComments]        VARCHAR (200) MASKED WITH (FUNCTION = 'default()')  NULL,
    [SignedBy]                INT                                                 NULL,
    [IsSentForReview]         BIT                                                 NULL,
    [QuotationTypeID]         INT                                                 NULL,
    [IsRejected]              BIT                                                 NULL,
    [IsAutoApproved]          BIT                                                 NULL,
    [IsRequestInfo]           BIT                                                 NULL,
    [IsActive]                BIT                                                 NOT NULL,
    [IsDeleted]               BIT                                                 NOT NULL,
    [CreatedBy]               VARCHAR (50)                                        NOT NULL,
    [CreatedDate]             DATETIME                                            NOT NULL,
    [ModifiedBy]              VARCHAR (50)                                        NOT NULL,
    [ModifiedDate]            DATETIME                                            NOT NULL,
    [ProstheticQuoteStatusId] INT                                                 NULL,
    [PreAuthId]               INT                                                 NULL,
    CONSTRAINT [PK_ProsthetistQuote_Temp] PRIMARY KEY CLUSTERED ([ProsthetistQuoteId] ASC) WITH (FILLFACTOR = 90, PAD_INDEX = ON),
    CONSTRAINT [FK_Medical_ProsthetistQuote_Temp_ProsthetistType] FOREIGN KEY ([ProstheticTypeId]) REFERENCES [medical].[ProsthetistType] ([ProsthetistTypeId]),
    CONSTRAINT [FK_Medical_ProsthetistQuote_Temp_SignedBy] FOREIGN KEY ([SignedBy]) REFERENCES [security].[User] ([Id]),
    CONSTRAINT [FK_Medical_ProsthetistQuote_Temp_User] FOREIGN KEY ([ReviewedBy]) REFERENCES [security].[User] ([Id]),
    CONSTRAINT [FK_Medical_ProsthetistQuote_Temp_User1] FOREIGN KEY ([ProsthetistId]) REFERENCES [security].[User] ([Id]),
    CONSTRAINT [FK_ProsthetistQuote_PreAuthorisation_PreAuthId] FOREIGN KEY ([PreAuthId]) REFERENCES [medical].[PreAuthorisation] ([PreAuthId]),
    CONSTRAINT [FK_ProsthetistQuote_ProstheticQuotationType_Id] FOREIGN KEY ([QuotationTypeID]) REFERENCES [common].[ProstheticQuotationType] ([Id]),
    CONSTRAINT [FK_ProsthetistQuote_ProstheticQuoteStatus_Id] FOREIGN KEY ([ProstheticQuoteStatusId]) REFERENCES [common].[ProstheticQuoteStatus] ([Id]),
    CONSTRAINT [FK_ProsthetistQuote_ProstheticType_Id] FOREIGN KEY ([ProstheticTypeId]) REFERENCES [common].[ProstheticType] ([Id])
);

