CREATE TABLE [medical].[TEBASwitchBatch_Temp] (
    [TEBASwitchBatchID]   INT            IDENTITY (1, 1) NOT NULL,
    [Description]         VARCHAR (2048) NULL,
    [SwitchBatchNo]       VARCHAR (50)   NULL,
    [SwitchFileName]      VARCHAR (127)  NULL,
    [DateSubmitted]       DATETIME       NULL,
    [DateSwitched]        DATETIME       NULL,
    [DateReceived]        DATETIME       NULL,
    [DateCompleted]       DATETIME       NULL,
    [InvoicesStated]      DECIMAL (18)   NOT NULL,
    [InvoicesCounted]     DECIMAL (18)   NOT NULL,
    [InvoicesProcessed]   DECIMAL (18)   NOT NULL,
    [AmountStatedIncl]    DECIMAL (18)   NOT NULL,
    [AmountCountedIncl]   DECIMAL (18)   NOT NULL,
    [AmountProcessedIncl] DECIMAL (18)   NOT NULL,
    [AssignedUserID]      INT            NOT NULL,
    [DateCaptured]        DATETIME       NULL,
    [SwitchID]            INT            NOT NULL,
    [LinesStated]         DECIMAL (18)   NOT NULL,
    [LinesCounted]        DECIMAL (18)   NOT NULL,
    [LinesProcessed]      DECIMAL (18)   NOT NULL,
    [DataXML]             XML            NULL,
    [isBulk]              BIT            CONSTRAINT [DF_TEBASwitchBatch_isBulk] DEFAULT ((0)) NULL,
    [AssignedRoleId]      INT            NULL,
    [IsActive]            BIT            CONSTRAINT [DF__TebaSwitchBat__IsAct__44A27C43] DEFAULT ((1)) NOT NULL,
    [IsDeleted]           BIT            CONSTRAINT [DF__TebaSwitchBat__IsDel__4596A07C] DEFAULT ((0)) NOT NULL,
    [CreatedBy]           VARCHAR (50)   NOT NULL,
    [CreatedDate]         DATETIME       CONSTRAINT [DF__TebaSwitchBat__Creat__468AC4B5] DEFAULT (getdate()) NOT NULL,
    [ModifiedBy]          VARCHAR (50)   NOT NULL,
    [ModifiedDate]        DATETIME       NOT NULL,
    CONSTRAINT [PK_Medical_TEBASwitchBatch_TEBASwitchBatchID] PRIMARY KEY CLUSTERED ([TEBASwitchBatchID] ASC) WITH (FILLFACTOR = 95),
    CONSTRAINT [FK_TEBASwitchBatch_Temp_Switch] FOREIGN KEY ([SwitchID]) REFERENCES [medical].[Switch] ([SwitchId]),
    CONSTRAINT [FK_TEBASwitchBatch_Temp_User] FOREIGN KEY ([AssignedUserID]) REFERENCES [security].[User] ([Id])
);

