CREATE TABLE [medical].[TebaInvoiceLine] (
    [TebaInvoiceLineId]				INT IDENTITY(1,1) NOT NULL,
	[TebaInvoiceId]					INT NOT NULL,
	[ServiceDate]					DATETIME NOT NULL,
	[RequestedQuantity]				DECIMAL(7, 2) NULL,
	[AuthorisedQuantity]			DECIMAL(7, 2) NOT NULL,
	[RequestedAmount]				DECIMAL(18, 2) NOT NULL,
	[RequestedVAT]					DECIMAL(18, 2) NOT NULL,
	[RequestedAmountInclusive]		AS (ISNULL([RequestedAmount],(0))+ISNULL([RequestedVAT],(0))),
	[AuthorisedAmount]				DECIMAL(18, 2) NULL,
	[AuthorisedVAT]					DECIMAL(18, 2) NULL,
	[AuthorisedAmountInclusive]		AS (ISNULL([AuthorisedAmount],(0))+ISNULL([AuthorisedVAT],(0))),		
	[TariffId]						INT NOT NULL,
	[TotalTariffAmount]				DECIMAL(18, 2) NOT NULL,
	[TotalTariffVAT]				DECIMAL(18, 2) NOT NULL,
	[TotalTariffAmountInclusive]	AS ([TotalTariffAmount]+[TotalTariffVAT]),
	[TariffAmount]					AS (((ISNULL([TotalTariffAmount],(0))+ISNULL([CreditAmount],(0)))+ISNULL([TotalTariffVAT],(0)))/CASE WHEN [AuthorisedQuantity]=(0) THEN (1) ELSE [AuthorisedQuantity] END),
	[CreditAmount]					DECIMAL(18, 2) NOT NULL,
	[VatCodeId]						INT NOT NULL,
	[VATPercentage]					DECIMAL(7, 2) NULL,
	[TreatmentCodeId]				INT NOT NULL,	
	[MedicalItemId]					INT NOT NULL,
	[HCPTariffCode]					VARCHAR(12) NULL,
	[TariffBaseUnitCostTypeId]		INT NULL,	
	[Description]					VARCHAR(200) NULL,
	[SummaryInvoiceLineId]			INT NULL,	
	[IsPerDiemCharge]				BIT NOT NULL,
	[IsDuplicate]					BIT NOT NULL,
	[DuplicateTebaInvoiceLineId]	INT NOT NULL,
	[CalculateOperands]				VARCHAR(200) NULL,
	[IsActive]						BIT NOT NULL,
	[IsDeleted]						BIT NOT NULL,
	[CreatedBy]						VARCHAR(50) NOT NULL,
	[CreatedDate]					DATETIME NOT NULL,
	[ModifiedBy]					VARCHAR(50) NOT NULL,
	[ModifiedDate]					DATETIME NOT NULL,
    CONSTRAINT [PK_Medical_TebaInvoiceLine_TebaInvoiceLineId] PRIMARY KEY CLUSTERED ([TebaInvoiceLineId] ASC) WITH (FILLFACTOR = 90, PAD_INDEX = ON),
    CONSTRAINT [FK_TebaInvoiceBreakdown_TebaInvoice] FOREIGN KEY ([TebaInvoiceId]) REFERENCES [medical].[TebaInvoice] ([TebaInvoiceId]),
    CONSTRAINT [FK_Medical_TebaInvoiceLine_VatCodeId] FOREIGN KEY ([VatCodeId]) REFERENCES [common].[VatCode] ([Id])
);

