CREATE TABLE [medical].[TebaSwitchBatchInvoice_Temp] (
    [TebaSwitchBatchInvoiceId] INT           IDENTITY (1, 1) NOT NULL,
    [TebaSwitchBatchId]        INT           NULL,
    [BatchSequenceNumber]      INT           NULL,
    [SwitchBatchNo]            VARCHAR (255) NULL,
    [SwitchTransactionNo]      VARCHAR (255) NULL,
    [PracticeNumber]           VARCHAR (255) NULL,
    [ServiceProviderName]      VARCHAR (255) NULL,
    [InvoiceDate]              DATETIME      NULL,
    [DateSubmitted]            DATETIME      NULL,
    [DateReceived]             DATETIME      NULL,
    [PInvoiceNo]               VARCHAR (255) NULL,
    [PInvoiceReference]        VARCHAR (255) NULL,
    [TotalInvoiceAmountExcl]   VARCHAR (50)  NULL,
    [TotalInvoiceVAT]          VARCHAR (50)  NULL,
    [TotalInvoiceAmountIncl]   VARCHAR (50)  NULL,
    [DateAdmitted]             DATETIME      NULL,
    [DateDischarged]           DATETIME      NULL,
    [ClaimFileRefNo]           VARCHAR (255) NULL,
    [EventDate]                DATETIME      NULL,
    [Surname]                  VARCHAR (255) NULL,
    [FirstName]                VARCHAR (255) NULL,
    [Initials]                 VARCHAR (255) NULL,
    [DateOfBirth]              DATETIME      NULL,
    [PreAuthNumber]            VARCHAR (255) NULL,
    [PossiblePEV]              INT           NULL,
    [PossibleEvent]            INT           NULL,
    [MedicalServiceProviderId] INT           NULL,
    [PreAuthId]                INT           NULL,
    [IsActive]                 BIT           NULL,
    [IsDeleted]                BIT           NOT NULL,
    [CreatedBy]                VARCHAR (50)  NOT NULL,
    [CreatedDate]              DATETIME      NOT NULL,
    [ModifiedBy]               VARCHAR (50)  NOT NULL,
    [ModifiedDate]             DATETIME      NOT NULL,
    [Status]                   VARCHAR (255) NULL,
    [DeleteReasonId]           INT           NULL,
    CONSTRAINT [PK_MISwitchBatchInvoice_Temp] PRIMARY KEY CLUSTERED ([TebaSwitchBatchInvoiceId] ASC) WITH (FILLFACTOR = 90, PAD_INDEX = ON),
    CONSTRAINT [FK_TebaSwitchBatchInvoice_Temp_TebaSwitchBatch_Temp] FOREIGN KEY ([TebaSwitchBatchId]) REFERENCES [medical].[TEBASwitchBatch_Temp] ([TEBASwitchBatchID])
);

