CREATE TABLE [medical].[TreatmentAuth_Temp] (
    [TreatmentAuthID]             INT           IDENTITY (1, 1) NOT NULL,
    [PersonEventID]               INT           NOT NULL,
    [AuthorisedAmount]            DECIMAL (18)  NULL,
    [AuthorisedPractitionerID]    INT           NOT NULL,
    [Description]                 VARCHAR (200) NOT NULL,
    [AuthorisedNumberTreatments]  DECIMAL (18)  NOT NULL,
    [IsPreAuthorisation]          BIT           NOT NULL,
    [PreAuthNumber]               VARCHAR (50)  NULL,
    [DateAuthorisedFrom]          DATETIME      NULL,
    [DateAuthorisedTo]            DATETIME      NULL,
    [TreatmentCodeID]             INT           NULL,
    [DateCaptured]                DATETIME      NOT NULL,
    [MedicalItemID]               INT           NULL,
    [ActualAmount]                DECIMAL (18)  NOT NULL,
    [OutstandingAmount]           AS            (isnull([AuthorisedAmount],(0))-isnull([ActualAmount],(0))),
    [ActualNumberTreatments]      DECIMAL (18)  NOT NULL,
    [OutstandingNumberTreatments] AS            (isnull([AuthorisedNumberTreatments],(0))-isnull([ActualNumberTreatments],(0))),
    [IsActive]                    BIT           NOT NULL,
    [IsDeleted]                   BIT           NOT NULL,
    [CreatedBy]                   VARCHAR (50)  NOT NULL,
    [CreatedDate]                 DATETIME      NOT NULL,
    [ModifiedBy]                  VARCHAR (50)  NOT NULL,
    [ModifiedDate]                DATETIME      NOT NULL,
    CONSTRAINT [PK_Compensation_TreatmentAuth_TreatmentAuthID] PRIMARY KEY CLUSTERED ([TreatmentAuthID] ASC) WITH (FILLFACTOR = 95),
    CONSTRAINT [FK_Medical_TreatmentAuth_AuthorisedPractitionerID] FOREIGN KEY ([AuthorisedPractitionerID]) REFERENCES [medical].[HealthCareProvider] ([RolePlayerId]),
    CONSTRAINT [FK_Medical_TreatmentAuth_PersonEventID] FOREIGN KEY ([PersonEventID]) REFERENCES [claim].[PersonEvent] ([PersonEventId]),
    CONSTRAINT [FK_Medical_TreatmentAuth_TreatmentCodeID] FOREIGN KEY ([TreatmentCodeID]) REFERENCES [medical].[TreatmentCode] ([TreatmentCodeId])
);

