//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;

namespace RMA.Service.Admin.BusinessProcessManager.Database.Entities
{
    public partial class bpm_WizardConfigurationRouteSetting : IAuditableEntity, ISoftDeleteEntity
    {
        public int Id { get; set; } // Id (Primary key)
        public int WizardConfigurationId { get; set; } // WizardConfigurationId
        public string Name { get; set; } // Name (length: 100)
        public string Description { get; set; } // Description (length: 1000)
        public int? RoutingUserId { get; set; } // RoutingUserId
        public int? RoutingRoleId { get; set; } // RoutingRoleId
        public int? SendForReviewUserId { get; set; } // SendForReviewUserId
        public int? SendForReviewRoleId { get; set; } // SendForReviewRoleId
        public string MessageTemplate { get; set; } // MessageTemplate (length: 1000)
        public bool IsDeleted { get; set; } // IsDeleted
        public string CreatedBy { get; set; } // CreatedBy (length: 50)
        public System.DateTime CreatedDate { get; set; } // CreatedDate
        public string ModifiedBy { get; set; } // ModifiedBy (length: 50)
        public System.DateTime ModifiedDate { get; set; } // ModifiedDate
        public string WorkflowType { get; set; } // WorkflowType (length: 50)
        public string WorkflowTypeDescription { get; set; } // WorkflowTypeDescription (length: 100)
        public string ActionLink { get; set; } // ActionLink (length: 255)
        public string NotificationTitle { get; set; } // NotificationTitle (length: 50)

        // Foreign keys

        /// <summary>
        /// Parent bpm_WizardConfiguration pointed by [WizardConfigurationRouteSetting].([WizardConfigurationId]) (FK_WizardConfigurationRouteSetting_WizardConfiguration)
        /// </summary>
        public virtual bpm_WizardConfiguration WizardConfiguration { get; set; } // FK_WizardConfigurationRouteSetting_WizardConfiguration

        public bpm_WizardConfigurationRouteSetting()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
