//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.Admin.SecurityManager.Contracts.Enums;
using RMA.Service.Admin.SecurityManager.Database.Entities;

namespace RMA.Service.Admin.SecurityManager.Database.Configuration
{
    public class security_LoginHistoryConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<security_LoginHistory>
    {
        public security_LoginHistoryConfiguration()
            : this("security")
        {
        }

        public security_LoginHistoryConfiguration(string schema)
        {
            ToTable("LoginHistory", schema);
            HasKey(x => x.LoginHistoryId);

            Property(x => x.LoginHistoryId).HasColumnName(@"LoginHistoryId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Logged).HasColumnName(@"Logged").HasColumnType("datetime").IsRequired();
            Property(x => x.RemoteIpAddress).HasColumnName(@"RemoteIpAddress").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(20);
            Property(x => x.Username).HasColumnName(@"Username").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.State).HasColumnName(@"State").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(100);
            Property(x => x.Reason).HasColumnName(@"Reason").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(100);
        }
    }

}
