//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.Admin.SecurityManager.Contracts.Enums;
using RMA.Service.Admin.SecurityManager.Database.Entities;

namespace RMA.Service.Admin.SecurityManager.Database.Configuration
{
    public class security_UserAmountLimitConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<security_UserAmountLimit>
    {
        public security_UserAmountLimitConfiguration()
            : this("security")
        {
        }

        public security_UserAmountLimitConfiguration(string schema)
        {
            ToTable("UserAmountLimit", schema);
            HasKey(x => x.UserAmountLimitId);

            Property(x => x.UserAmountLimitId).HasColumnName(@"UserAmountLimitId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.AmountLimitType).HasColumnName(@"AmountLimitTypeId").HasColumnType("int").IsRequired();
            Property(x => x.UserId).HasColumnName(@"UserId").HasColumnType("int").IsRequired();
            Property(x => x.AmountLimit).HasColumnName(@"AmountLimit").HasColumnType("money").IsOptional().HasPrecision(19,4);
            Property(x => x.DaysLimit).HasColumnName(@"DaysLimit").HasColumnType("decimal").IsOptional().HasPrecision(7,2);
            Property(x => x.PdExtentLimit).HasColumnName(@"PDExtentLimit").HasColumnType("decimal").IsOptional().HasPrecision(7,2);
            Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();

            // Foreign keys
            HasRequired(a => a.User).WithMany(b => b.UserAmountLimits).HasForeignKey(c => c.UserId).WillCascadeOnDelete(false); // FK_UserAmountLimit_User
        }
    }

}
