//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.Admin.SecurityManager.Contracts.Enums;
using RMA.Service.Admin.SecurityManager.Database.Entities;

namespace RMA.Service.Admin.SecurityManager.Database.Configuration
{
    public class security_UserPermission2Configuration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<security_UserPermission2>
    {
        public security_UserPermission2Configuration()
            : this("security")
        {
        }

        public security_UserPermission2Configuration(string schema)
        {
            ToTable("UserPermission2", schema);
            HasKey(x => new { x.UserId, x.PermissionId });

            Property(x => x.UserId).HasColumnName(@"UserId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.PermissionId).HasColumnName(@"PermissionId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType("bit").IsRequired();
            Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();

            // Foreign keys
            HasRequired(a => a.Permission).WithMany(b => b.UserPermission2).HasForeignKey(c => c.PermissionId).WillCascadeOnDelete(false); // FK_UserPermission2_Permission
            HasRequired(a => a.User).WithMany(b => b.UserPermission2).HasForeignKey(c => c.UserId).WillCascadeOnDelete(false); // FK_UserPermission2_User
        }
    }

}
