//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.Admin.SecurityManager.Contracts.Enums;
using RMA.Service.Admin.SecurityManager.Database.Entities;

namespace RMA.Service.Admin.SecurityManager.Database.Configuration
{
    public class security_PasswordResetAuthorisationConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<security_PasswordResetAuthorisation>
    {
        public security_PasswordResetAuthorisationConfiguration()
            : this("security")
        {
        }

        public security_PasswordResetAuthorisationConfiguration(string schema)
        {
            ToTable("PasswordResetAuthorisation", schema);
            HasKey(x => new { x.EmailAddress, x.Token });

            Property(x => x.EmailAddress).HasColumnName(@"EmailAddress").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Token).HasColumnName(@"Token").HasColumnType("nvarchar").IsRequired().HasMaxLength(300).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.CreationDate).HasColumnName(@"CreationDate").HasColumnType("datetime").IsRequired();
            Property(x => x.HasExpired).HasColumnName(@"HasExpired").HasColumnType("bit").IsRequired();
        }
    }

}
