
using System;

namespace RMA.Service.Billing.Contracts.Entities
{
    public class CollectionsAgeing
    {
        public string Class { get; set; }
        public string DR_YYYY { get; set; }
        public string ControlNumber { get; set; }
        public string Product { get; set; }
        public string DR_NO { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string DocumentNo { get; set; }
        public DateTime? PolicyInceptionDate { get; set; }
        public string ProductOptions { get; set; }
        public string ProductType { get; set; }
        public string BrokerName { get; set; }
        public string PolicyHolderName { get; set; }
        public string Group { get; set; }
        public double DocBalance { get; set; }
        public double JAN_Invoice { get; set; }
        public double JAN_Raised { get; set; }
        public double JAN_Collect { get; set; }
        public double JAN_Credit { get; set; }
        public double FEB_Invoice { get; set; }
        public double FEB_Raised { get; set; }
        public double FEB_Collect { get; set; }
        public double FEB_Credit { get; set; }
        public double MAR_Invoice { get; set; }
        public double MAR_Raised { get; set; }
        public double MAR_Collect { get; set; }
        public double MAR_Credit { get; set; }
        public double APR_Invoice { get; set; }
        public double APR_Raised { get; set; }
        public double APR_Collect { get; set; }
        public double APR_Credit { get; set; }
        public double MAY_Invoice { get; set; }
        public double MAY_Raised { get; set; }
        public double MAY_Collect { get; set; }
        public double MAY_Credit { get; set; }
        public double JUN_Invoice { get; set; }
        public double JUN_Raised { get; set; }
        public double JUN_Collect { get; set; }
        public double JUN_Credit { get; set; }
        public double JUL_Invoice { get; set; }
        public double JUL_Raised { get; set; }
        public double JUL_Collect { get; set; }
        public double JUL_Credit { get; set; }
        public double AUG_Invoice { get; set; }
        public double AUG_Raised { get; set; }
        public double AUG_Collect { get; set; }
        public double AUG_Credit { get; set; }
        public double SEP_Invoice { get; set; }
        public double SEP_Raised { get; set; }
        public double SEP_Collect { get; set; }
        public double SEP_Credit { get; set; }
        public double OCT_Invoice { get; set; }
        public double OCT_Raised { get; set; }
        public double OCT_Collect { get; set; }
        public double OCT_Credit { get; set; }
        public double NOV_Invoice { get; set; }
        public double NOV_Raised { get; set; }
        public double NOV_Collect { get; set; }
        public double NOV_Credit { get; set; }
        public double DEC_Invoice { get; set; }
        public double DEC_Raised { get; set; }
        public double DEC_Collect { get; set; }
        public double DEC_Credit { get; set; }
        public double Year1_Jan_Collect { get; set; }
        public double Year1_Jan_Credit { get; set; }
        public double Year1_Feb_Collect { get; set; }
        public double Year1_Feb_Credit { get; set; }
        public double Year1_Mar_Collect { get; set; }
        public double Year1_Mar_Credit { get; set; }
        public double Year1_Apr_Collect { get; set; }
        public double Year1_Apr_Credit { get; set; }
        public double Year1_May_Collect { get; set; }
        public double Year1_May_Credit { get; set; }
        public double Year1_Jun_Collect { get; set; }
        public double Year1_Jun_Credit { get; set; }
        public double Year1_Jul_Collect { get; set; }
        public double Year1_Jul_Credit { get; set; }
        public double Year1_Aug_Collect { get; set; }
        public double Year1_Aug_Credit { get; set; }
        public double Year1_Sep_Collect { get; set; }
        public double Year1_Sep_Credit { get; set; }
        public double Year1_Oct_Collect { get; set; }
        public double Year1_Oct_Credit { get; set; }
        public double Year1_Nov_Collect { get; set; }
        public double Year1_Nov_Credit { get; set; }
        public double Year1_Dec_Collect { get; set; }
        public double Year1_Dec_Credit { get; set; }
        public double Year2_Jan_Collect { get; set; }
        public double Year2_Jan_Credit { get; set; }
        public double Year2_Feb_Collect { get; set; }
        public double Year2_Feb_Credit { get; set; }
        public double Year2_Mar_Collect { get; set; }
        public double Year2_Mar_Credit { get; set; }
        public double Year2_Apr_Collect { get; set; }
        public double Year2_Apr_Credit { get; set; }
        public double Year2_May_Collect { get; set; }
        public double Year2_May_Credit { get; set; }
        public double Year2_Jun_Collect { get; set; }
        public double Year2_Jun_Credit { get; set; }
        public double Year2_Jul_Collect { get; set; }
        public double Year2_Jul_Credit { get; set; }
        public double Year2_Aug_Collect { get; set; }
        public double Year2_Aug_Credit { get; set; }
        public double Year2_Sep_Collect { get; set; }
        public double Year2_Sep_Credit { get; set; }
        public double Year2_Oct_Collect { get; set; }
        public double Year2_Oct_Credit { get; set; }
        public double Year2_Nov_Collect { get; set; }
        public double Year2_Nov_Credit { get; set; }
        public double Year2_Dec_Collect { get; set; }
        public double Year2_Dec_Credit { get; set; }
        public double Year3_Collect { get; set; }
        public double Year3_Credit { get; set; }
        public double Year4_Plus_Collect { get; set; }
        public double Year4_Plus_Credit { get; set; }
    }
}
