export enum DebtorNoteTypeEnum {
    TermsArrangement = 1,
    UnsuccessfulTerm = 2,
    TermMissedPayment = 3,
    TermInadquatePayment = 4,
    TermArrears = 5,
    CreditNote = 6,
    GeneralBilling = 7,
    Refund = 8,
    ReAllocation = 9,
    InterDebtorTransfer = 10,
    InterBankTransfer = 11,
    Email = 12,
    InterestReversal = 13,
    InterestAdjustment = 14,
    BadDebtWriteOff = 15,
    BadDebtReinstate = 16,
    InterestReinstate = 17,
    InterestWriteOff = 18,
    PremiumAdjustment = 19,
    PaymentReversal = 20,
    PaymentAllocation = 21,
    AdhocInterest = 22,
    PremiumWriteOff = 23,
    Collection=30
}
