export enum PaymentFilterTypeEnum {
		PolicyNo = 1,
		ClaimNo = 2,
		PayeeAccountNo = 3,
		Payee = 4,
		IdNo = 5,
		PaymentNo = 6,
		PensionReferenceNo = 7,
		InvoiceNo = 8,
		Surname = 9,
		PayeeNo = 10,
		EftNo = 11,
		MemberNo = 12,
		TransactionNo = 13,
		BankReferenceNo = 14,
		MspPracticeNo = 15,
		Name = 16,
		MemberName = 17,
		RegistrationNo = 18,
		BankAccountNo = 19
 }
