/** @description THe different types of rules available in the app. */
export enum BeneficiaryTypeEnum {
    MainMember = 1,
    Spouse = 2,
    Daughter = 3,
    DaughterInLaw = 4,
    SonInLaw = 5,
    Son = 6,
    Parent = 7,
    ParentInLaw = 8,
    Grandparent = 9,
    Mother = 10,
    MotherInLaw = 11,
    Father = 12,
    FatherInLaw = 13,
    Brother = 14,
    BrotherInLaw = 15,
    Sister = 16,
    SisterInLaw = 17,
    Aunt = 18,
    Niece = 19,
    Nephew = 20,
    Husband = 21,
    Wife = 22,
    Child = 23,
    SpecialChild = 24,
    Other = 25,
    GuardianRecipient = 26,
    PersonIndividual = 27,
    Pensioner = 28,
    Extended = 29,
    DisabledChild = 30,
    GrandChild = 31,
    Friend = 32
}
