export enum ClaimInvoiceTypeEnum {
    SundryInvoice = 1,
    MedicalInvoice = 2,
    DaysOffInvoice = 3,
    PDAward = 4,
    Pension = 5,
    OtherBenefitAwd = 6,
    TravelAward = 7,
    WidowLumpSumAward = 8,
    FuneralExpenses = 9,
    SpecialAllowance = 10,
    SympathyAward = 11,
    ConstantAttendanceAllowance = 12,
    FamilyAllowance = 13,
    FatalLumpSumAward = 14,
    PartialDependencyLumpsum = 15,
}
