export enum ClaimInvoiceStatusEnum {
    Paid = 1,
    Unpaid = 2,
    Pending = 3,
    Partially = 4,
    Captured = 5,
    Validated = 6,
    Assessed = 7,
    Allocated = 8,
    PaymentRequested = 9,
    Rejected = 10,
    FinallyRejected = 11,
    Deleted = 12,
    Rejected3rdparty = 13,
    ReInstated = 14,
    Queued = 15,
    RequestedForApproval = 16,
    ApprovedBySCA = 17,
    Referred = 18,
    PendingAuthorization = 19,
    ConvertedToPension = 20,
    WrittenOff = 21,
    PaymentRecalled = 22,
    PaymentReversed = 23,
    PaymentRejected = 24,
}
