export enum ClientItemTypeEnum {
    Address = 1,
    BankAccount = 2,
    Branch = 3,
    Client = 4,
    Department = 5,
    Contact = 6,
    ClientCoverDetail = 7,
    Enquiry = 8,
    Group = 9,
    CallbackRequest = 10,
    ClientBankAccount = 11,
    Brokerage = 12,
    Representative = 13,
    Beneficiary = 14,
    Company = 15,
    Person = 16,
    PersonEmployment = 17,
    RolePlayerPolicyDeclaration = 18,
    RolePlayerPolicyTransaction = 19,
    RolePlayerPolicyDeclarationDetail = 20,
    LetterOfGoodStanding = 21,
    RolePlayerPolicyOnlineSubmission = 22,
    RolePlayerPolicyOnlineSubmissionDetail = 23
}
