export enum ContactInformationTypeEnum {
    Invoices = 1,
    Declarations = 2,
    Claims = 3,
    PolicyInformation = 4,
    Finance = 5,
    Management = 6,
    HR = 7,
    Medical = 8,
    Safety = 9,
    Intermediary = 10,
    IntermediaryAssistant = 11,
    Insurance = 12,
    CompCare = 13,
    PensCare = 14,
    OnlineAdministrator = 15,
    OnlineFinanceAdministrator = 16,
    OnlineClaimsAdministrator = 17,
    OnlineDirector = 18,
}
