export enum EstimateTypeEnum {
    DaysOff = 1,
    Medical = 2,
    PDLumpSum = 3,
    FtlPenPrimry = 4,
    ThirdPartyRecovery = 5,
    RIRecovery = 6,
    Sundry = 7,
    WidowsLumpSum = 8,
    PartialDependants = 9,
    FamilyAllow2 = 10,
    SympathyAward = 11,
    ConstantAttendance = 12,
    TravelExpenses = 13,
    Sectn56 = 14,
    LumpSumAward = 15,
    PDPension = 16,
    Funeral = 17,
    TotPartDeps = 18,
    FatPenChld4 = 19,
    Ftotd = 20,
    FamilyAllow3 = 21,
    FtlLumpSum = 22,
    ExGratia = 23,
    ShiftLoss = 24,
    TPD = 25,
    TTD = 26
}