export enum PaymentMethodEnum {
    ACB = 1,
    AdvanceCheque = 2,
    BankCheque = 3,
    BankDraft = 4,
    Cash = 5,
    CompanyCheque = 6,
    EFT = 7,
    Malawi = 8,
    Metacais = 9,
    RSACheque = 10,
    DebitOrder = 11,
    GovernmentSalaryDeduction = 12,
    Unknown = 13,
    PersonalCheque = 14,
    TEBA = 15,
    Zimbabwe = 16,
    VAT = 17,
    BalanceControl = 18,
    CorporateStopOrder = 19,
}
