export enum PaymentTypeEnum {
  Claim = 1,
  Commission = 2,
  Refund = 3,
  TracingFee = 4,
  EuropeAssistFee = 5,
  MedicalInvoice = 6,
  Pension = 7,
  Tribunal = 8,
  Commutation = 9,
  CapitalValue = 10,
  CorrectiveEntry = 11,
  OverPayment = 12,
  Tax = 13,
  Other = 15,
  PremiumPayback = 16,
  InterBankTransfer = 17,
  VAT = 18,
  WidowsLumpSum = 19,
  Unknown = 20,
  OverpaymentBalance = 21,
  PRMA = 22,
  TebaInvoice = 23,
	Recovery = 24
}