CREATE TABLE [pension].[Commutation] (
    [Id]                         INT            IDENTITY (1, 1) NOT NULL,
    [LedgerId]                   INT            NOT NULL,
    [Reference]                  VARCHAR (30)   NOT NULL,
    [RequestedDate]              DATETIME       NOT NULL,
    [CommutationStatusId]        INT            NOT NULL,
    [CommutationReasonId]        INT            NOT NULL,
    [CommutedAmount]             MONEY          NOT NULL,
    [CommutationAmount]          MONEY          NOT NULL,
    [CCStatusId]                 INT            NULL,
    [CCApprovalDate]             DATETIME       NULL,
    [CCSchedule]                 INT            NULL,
    [CalcStatusId]               SMALLINT       NULL,
    [EntryStatusId]              INT            NOT NULL,
    [CommutationAmountRequested] MONEY          NULL,
    [IsRecommended]              BIT            NULL,
    [Comment]                    VARCHAR (1000) NULL,
    [MPFPension]                 MONEY          NULL,
    [Salary]                     MONEY          NULL,
    [OtherIncome]                MONEY          NULL,
    [CommutationPAYE]            MONEY          NOT NULL,
    [FraudComment]               VARCHAR (2000) NULL,
    [IsActive]                   BIT            CONSTRAINT [DF_Commutation_IsActive] DEFAULT ((1)) NOT NULL,
    [IsDeleted]                  BIT            CONSTRAINT [DF_Commutation_IsDeleted] DEFAULT ((0)) NOT NULL,
    [CreatedBy]                  VARCHAR (50)   NOT NULL,
    [CreatedDate]                DATETIME       NOT NULL,
    [ModifiedBy]                 VARCHAR (50)   NOT NULL,
    [ModifiedDate]               DATETIME       NOT NULL,
    CONSTRAINT [PK_Commutation] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Commutation_CCStatus] FOREIGN KEY ([CCStatusId]) REFERENCES [common].[CCStatus] ([Id]),
    CONSTRAINT [FK_Commutation_CommutationReason] FOREIGN KEY ([CommutationReasonId]) REFERENCES [common].[CommutationReason] ([Id]),
    CONSTRAINT [FK_Commutation_CommutationSchedule] FOREIGN KEY ([CCSchedule]) REFERENCES [common].[CommutationSchedule] ([Id]),
    CONSTRAINT [FK_Commutation_CommutationStatus] FOREIGN KEY ([CommutationStatusId]) REFERENCES [common].[CommutationStatus] ([Id]),
    CONSTRAINT [FK_Commutation_EntryStatus] FOREIGN KEY ([EntryStatusId]) REFERENCES [common].[EntryStatus] ([Id]),
    CONSTRAINT [FK_Commutation_Ledger] FOREIGN KEY ([LedgerId]) REFERENCES [pension].[Ledger] ([PensionLedgerId])
);

