CREATE TABLE [pension].[Ledger] (
    [PensionLedgerId]                      INT            IDENTITY (1, 1) NOT NULL,
    [PensionClaimMapId]                    INT            NOT NULL,
    [LedgerStatusChangeReasonId]           INT            NOT NULL,
    [PensionLedgerStatusId]                INT            NOT NULL,
    [StartAmount]                          MONEY          NOT NULL,
    [StartDate]                            DATETIME       NOT NULL,
    [ExpectedEndDate]                      DATETIME       NULL,
    [EffectiveDate]                        DATETIME       NOT NULL DEFAULT(DATEADD(DAY, 1, EOMONTH(GETDATE(), -1))),
    [ProductNumber]                        NVARCHAR (100) NULL,
    [NormalMonthlyPension]                 DECIMAL (18)   NULL,
    [CurrentMonthlyPension]                DECIMAL (18)   NULL,
    [CapitalValue]                         DECIMAL (18)   NULL,
    [Earnings]                             DECIMAL (18)   NULL,
    [BeneficiaryPercentage]                DECIMAL (18)   NULL,
    [EarningsAllocation]                   DECIMAL (18)   NULL,
    [AV]                                   DECIMAL (18)   NULL,
    [ProductClassName]                     VARCHAR (50)   NULL,
    [ProductOptionName]                    VARCHAR (50)   NULL,
    [BenefitCode]                          VARCHAR (50)   NULL,
    [ProductCode]                          VARCHAR (50)   NULL,
    [DateOfAccident]                       DATETIME       NULL,
    [DateOfStabilisation]                  DATETIME       NOT NULL,
    [IndustryNumber]                       VARCHAR (50)   NULL,
    [IsAutoLedger]                         BIT            NOT NULL,
    [CurrentMonthlyPensionPaye]            DECIMAL (18)   NULL,
    [CurrentMonthlyPensionExcludingTax]    DECIMAL (18)   NULL,
    [NormalMonthlyPensionPaye]             DECIMAL (18)   NULL,
    [NormalMonthlyPensionPayeExcludingTax] DECIMAL (18)   NULL,
    [AdditionalTax]                        DECIMAL (18)   NULL,
    [LastPaymentDate]                      DATETIME       NULL,
    [OverPayment]                          BIT            CONSTRAINT [DF_Ledger_OverPayment] DEFAULT ((0)) NULL,
    [BeneficiaryId]                        INT            NULL,
    [DateOfBirth]                          DATETIME       NULL,
    [IsActive]                             BIT            CONSTRAINT [DF_PensionLedger__IsActive] DEFAULT ((1)) NOT NULL,
    [IsDeleted]                            BIT            CONSTRAINT [DF_PensionLedger__IsDeleted] DEFAULT ((0)) NOT NULL,
    [CreatedBy]                            VARCHAR (50)   NOT NULL,
    [CreatedDate]                          DATETIME       CONSTRAINT [DF_PensionLedger__CreatedDate] DEFAULT (getdate()) NOT NULL,
    [ModifiedBy]                           VARCHAR (50)   NOT NULL,
    [ModifiedDate]                         DATETIME       CONSTRAINT [DF_PensionLedger__ModifiedDate] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK1__PensionLedger] PRIMARY KEY CLUSTERED ([PensionLedgerId] ASC),
    CONSTRAINT [FK__PensionLedger_PensionClaimMap] FOREIGN KEY ([PensionClaimMapId]) REFERENCES [pension].[PensionClaimMap] ([PensionClaimMapId]),
    CONSTRAINT [FK_Ledger_Beneficiary] FOREIGN KEY ([BeneficiaryId]) REFERENCES [pension].[Beneficiary] ([BeneficiaryId]),
    CONSTRAINT [FK_Ledger_LedgerStatusChangeReasons] FOREIGN KEY ([LedgerStatusChangeReasonId]) REFERENCES [common].[LedgerStatusChangeReasons] ([Id]),
    CONSTRAINT [FK_Ledger_PensionLedgerStatus] FOREIGN KEY ([PensionLedgerStatusId]) REFERENCES [common].[PensionLedgerStatus] ([Id])
);



