CREATE TABLE [pension].[MonthlyPensionLedger] (
    [MonthlyPensionLedgerId] INT          IDENTITY (1, 1) NOT NULL,
    [MonthlyPensionId]       INT          NULL,
    [PaymentMethodId]        INT          NULL,
    [PaymentTypeId]          INT          NULL,
    [Amount]                 DECIMAL (18) NOT NULL,
    [AdditionalTax]          DECIMAL (18) NOT NULL,
    [VAT]                    DECIMAL (18) NOT NULL,
    [PAYE]                   DECIMAL (18) NOT NULL,
    [LedgerId]               INT          NOT NULL,
    [PaymentStatusId]        INT          NOT NULL,
    [BatchStatusId]          INT          NOT NULL,
    [Reference]              VARCHAR (50) NOT NULL,
    [ChangeReasonId]         INT          NULL,
    [BeneficiayId]           INT          NOT NULL,
    [IsActive]               BIT          NOT NULL,
    [IsDeleted]              BIT          NOT NULL,
    [CreatedBy]              VARCHAR (50) NOT NULL,
    [CreatedDate]            DATETIME     NOT NULL,
    [ModifiedBy]             VARCHAR (50) NOT NULL,
    [ModifiedDate]           DATETIME     NOT NULL,
    [AgencyBranchId]         INT          NULL,
    CONSTRAINT [PK__MonthlyP__7A3EA77C81CCA9B9] PRIMARY KEY CLUSTERED ([MonthlyPensionLedgerId] ASC),
    CONSTRAINT [FK_MonthlyPensionLedger_BatchStatus] FOREIGN KEY ([BatchStatusId]) REFERENCES [common].[BatchStatus] ([Id]),
    CONSTRAINT [FK_MonthlyPensionLedger_ChangeReason] FOREIGN KEY ([ChangeReasonId]) REFERENCES [common].[ChangeReason] ([Id]),
    CONSTRAINT [FK_MonthlyPensionLedger_Ledger] FOREIGN KEY ([LedgerId]) REFERENCES [pension].[Ledger] ([PensionLedgerId]),
    CONSTRAINT [FK_MonthlyPensionLedger_MonthlyPension] FOREIGN KEY ([MonthlyPensionId]) REFERENCES [pension].[MonthlyPension] ([MonthlyPensionId]),
    CONSTRAINT [FK_MonthlyPensionLedger_PaymentMethod] FOREIGN KEY ([PaymentMethodId]) REFERENCES [common].[PaymentMethod] ([Id]),
    CONSTRAINT [FK_MonthlyPensionLedger_PaymentStatus] FOREIGN KEY ([PaymentStatusId]) REFERENCES [common].[PaymentStatus] ([Id]),
    CONSTRAINT [FK_MonthlyPensionLedger_PaymentType] FOREIGN KEY ([PaymentTypeId]) REFERENCES [common].[PaymentType] ([Id]),
    CONSTRAINT [FK_MonthlyPensionLedger_PensionBeneficiary] FOREIGN KEY ([BeneficiayId]) REFERENCES [pension].[PensionBeneficiary] ([PensionBeneficiaryId])
);

