CREATE TABLE [pension].[PensionPayment] (
    [PensionPaymentID]   INT              IDENTITY (1, 1) NOT NULL,
    [Year]               SMALLINT         NOT NULL,
    [Month]              TINYINT          NOT NULL,
    [Amount]             MONEY            NOT NULL,
    [PaymentStatusID]    INT              NOT NULL,
    [PaymentDate]        DATETIME         NOT NULL,
    [DocumentNumber]     VARCHAR (30)     NULL,
    [AbilityDate]        DATETIME         NULL,
    [BankReference]      VARCHAR (30)     NULL,
    [ReconReference]     VARCHAR (30)     NULL,
    [ReversalReason]     VARCHAR (255)    NULL,
    [OnBankStatement]    TINYINT          NULL,
    [AbilityTransaction] VARCHAR (30)     NULL,
    [PaymentType]        INT              NULL,
    [IsGenerateTax]      BIT              NOT NULL,
    [IsGenerateVat]      BIT              NOT NULL,
    [IsActive]           BIT              CONSTRAINT [DF__PensionPa__IsAct__66F85F9E] DEFAULT ((1)) NOT NULL,
    [IsDeleted]          BIT              NOT NULL,
    [CreatedBy]          VARCHAR (50)     NOT NULL,
    [CreatedDate]        DATETIME         NOT NULL,
    [ModifiedBy]         VARCHAR (50)     NOT NULL,
    [ModifiedDate]       DATETIME         NOT NULL,
    [oldID]              UNIQUEIDENTIFIER NULL,
    CONSTRAINT [PK_Pension_Payment_PaymentID] PRIMARY KEY CLUSTERED ([PensionPaymentID] ASC) WITH (FILLFACTOR = 95),
    CONSTRAINT [FK_PensionPayment_PaymentStatus] FOREIGN KEY ([PaymentStatusID]) REFERENCES [common].[PaymentStatus] ([Id]),
    CONSTRAINT [FK_PensionPayment_PaymentType] FOREIGN KEY ([PaymentType]) REFERENCES [common].[PaymentType] ([Id])
);

