//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.MediCare.Database.Entities;

namespace RMA.Service.MediCare.Database.Configuration
{
    public class medical_PreAuthTreatmentBasketConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<medical_PreAuthTreatmentBasket>
    {
        public medical_PreAuthTreatmentBasketConfiguration()
            : this("medical")
        {
        }

        public medical_PreAuthTreatmentBasketConfiguration(string schema)
        {
            ToTable("PreAuthTreatmentBasket", schema);
            HasKey(x => x.PreAuthTreatmentBasketId);

            Property(x => x.PreAuthTreatmentBasketId).HasColumnName(@"PreAuthTreatmentBasketId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.PreAuthId).HasColumnName(@"PreAuthId").HasColumnType("int").IsRequired();
            Property(x => x.TreatmentBasketId).HasColumnName(@"TreatmentBasketId").HasColumnType("int").IsRequired();
            Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.IsAuthorised).HasColumnName(@"IsAuthorised").HasColumnType("bit").IsOptional();
            Property(x => x.IsClinicalUpdate).HasColumnName(@"IsClinicalUpdate").HasColumnType("bit").IsRequired();
            Property(x => x.UpdateSequenceNo).HasColumnName(@"UpdateSequenceNo").HasColumnType("smallint").IsOptional();
            Property(x => x.ClinicalUpdateId).HasColumnName(@"ClinicalUpdateId").HasColumnType("int").IsOptional();

            // Foreign keys
            HasOptional(a => a.ClinicalUpdate).WithMany(b => b.PreAuthTreatmentBaskets).HasForeignKey(c => c.ClinicalUpdateId).WillCascadeOnDelete(false); // FK_PreAuthTreatmentBasket_ClinicalUpdate
            HasRequired(a => a.PreAuthorisation).WithMany(b => b.PreAuthTreatmentBaskets).HasForeignKey(c => c.PreAuthId).WillCascadeOnDelete(false); // FK_PreAuthTreatmentBasket_PreAuthorisation
        }
    }

}
