//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.MediCare.Database.Entities;

namespace RMA.Service.MediCare.Database.Configuration
{
    public class medical_PreAuthPractitionerTypeSettingConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<medical_PreAuthPractitionerTypeSetting>
    {
        public medical_PreAuthPractitionerTypeSettingConfiguration()
            : this("medical")
        {
        }

        public medical_PreAuthPractitionerTypeSettingConfiguration(string schema)
        {
            ToTable("PreAuthPractitionerTypeSetting", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.PreAuthType).HasColumnName(@"PreAuthTypeId").HasColumnType("int").IsRequired();
            Property(x => x.PractitionerTypeId).HasColumnName(@"PractitionerTypeId").HasColumnType("int").IsRequired();
            Property(x => x.IsHospital).HasColumnName(@"IsHospital").HasColumnType("bit").IsRequired();
            Property(x => x.IsTreatingDoctor).HasColumnName(@"IsTreatingDoctor").HasColumnType("bit").IsRequired();
            Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();

            // Foreign keys
            //HasRequired(a => a.PractitionerType).WithMany(b => b.PreAuthPractitionerTypeSettings).HasForeignKey(c => c.PractitionerType).WillCascadeOnDelete(false); // FK_PreAuthPractitionerTypeSetting_PractitionerType
        }
    }

}
