//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.FinCare.Contracts.Enums;
using RMA.Service.FinCare.Database.Entities;

namespace RMA.Service.FinCare.Database.Configuration
{
    public class billing_UnallocatedPaymentConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<billing_UnallocatedPayment>
    {
        public billing_UnallocatedPaymentConfiguration()
            : this("billing")
        {
        }

        public billing_UnallocatedPaymentConfiguration(string schema)
        {
            ToTable("UnallocatedPayment", schema);
            HasKey(x => x.UnallocatedPaymentId);

            Property(x => x.UnallocatedPaymentId).HasColumnName(@"UnallocatedPaymentId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.BankStatementEntryId).HasColumnName(@"BankStatementEntryId").HasColumnType("int").IsRequired();
            Property(x => x.AllocationProgressStatus).HasColumnName(@"AllocationProgressStatusId").HasColumnType("int").IsOptional();
            Property(x => x.UnallocatedAmount).HasColumnName(@"UnallocatedAmount").HasColumnType("decimal").IsRequired().HasPrecision(18,2);
            Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType("bit").IsRequired();
            Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.RoleplayerId).HasColumnName(@"RoleplayerId").HasColumnType("int").IsOptional();
            Property(x => x.PeriodId).HasColumnName(@"PeriodId").HasColumnType("int").IsOptional();

            // Foreign keys
            HasRequired(a => a.BankStatementEntry).WithMany(b => b.UnallocatedPayments).HasForeignKey(c => c.BankStatementEntryId).WillCascadeOnDelete(false); // FK_UnallocatedPayment_BankStatementEntry
        }
    }

}
