//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.FinCare.Contracts.Enums;
using RMA.Service.FinCare.Database.Entities;

namespace RMA.Service.FinCare.Database.Configuration
{
    public class billing_AbilityTransactionsAuditConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<billing_AbilityTransactionsAudit>
    {
        public billing_AbilityTransactionsAuditConfiguration()
            : this("billing")
        {
        }

        public billing_AbilityTransactionsAuditConfiguration(string schema)
        {
            ToTable("AbilityTransactionsAudit", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Reference).HasColumnName(@"Reference").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.TransactionId).HasColumnName(@"TransactionId").HasColumnType("int").IsOptional();
            Property(x => x.Item).HasColumnName(@"Item").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.ItemReference).HasColumnName(@"ItemReference").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(100);
            Property(x => x.Amount).HasColumnName(@"Amount").HasColumnType("decimal").IsOptional().HasPrecision(18,2);
            Property(x => x.OnwerDetails).HasColumnName(@"OnwerDetails").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(100);
            Property(x => x.Bank).HasColumnName(@"Bank").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(100);
            Property(x => x.BankBranch).HasColumnName(@"BankBranch").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(100);
            Property(x => x.AccountDetails).HasColumnName(@"AccountDetails").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(100);
            Property(x => x.IsProcessed).HasColumnName(@"IsProcessed").HasColumnType("bit").IsOptional();
            Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType("bit").IsRequired();
            Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.BankAccountId).HasColumnName(@"BankAccountId").HasColumnType("int").IsOptional();
            Property(x => x.BsChart).HasColumnName(@"BSChart").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.IsChart).HasColumnName(@"ISChart").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.UnallocatedPaymentId).HasColumnName(@"UnallocatedPaymentId").HasColumnType("int").IsOptional();
            Property(x => x.Level1).HasColumnName(@"Level1").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.Level2).HasColumnName(@"Level2").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.Level3).HasColumnName(@"Level3").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.EarnedPremiumId).HasColumnName(@"EarnedPremiumId").HasColumnType("int").IsOptional();

            // Foreign keys
            HasOptional(a => a.EarnedPremium).WithMany(b => b.AbilityTransactionsAudits).HasForeignKey(c => c.EarnedPremiumId).WillCascadeOnDelete(false); // FK_AbilityTransactionsAudit_EarnedPremium
            HasOptional(a => a.UnallocatedPayment).WithMany(b => b.AbilityTransactionsAudits).HasForeignKey(c => c.UnallocatedPaymentId).WillCascadeOnDelete(false); // FK_AbilityTransactionsAudit_UnallocatedPayment
        }
    }

}
