//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.FinCare.Contracts.Enums;
using RMA.Service.FinCare.Database.Entities;

namespace RMA.Service.FinCare.Database.Configuration
{
    public class billing_PolicyPaymentAllocationConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<billing_PolicyPaymentAllocation>
    {
        public billing_PolicyPaymentAllocationConfiguration()
            : this("billing")
        {
        }

        public billing_PolicyPaymentAllocationConfiguration(string schema)
        {
            ToTable("PolicyPaymentAllocation", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.TransactionId).HasColumnName(@"TransactionId").HasColumnType("int").IsRequired();
            Property(x => x.PolicyId).HasColumnName(@"PolicyId").HasColumnType("int").IsRequired();
            Property(x => x.BillingMonth).HasColumnName(@"BillingMonth").HasColumnType("date").IsRequired();
            Property(x => x.Amount).HasColumnName(@"Amount").HasColumnType("decimal").IsRequired().HasPrecision(18,2);
            Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.TransactionTypeLinkId).HasColumnName(@"TransactionTypeLinkId").HasColumnType("int").IsRequired();
            Property(x => x.BillingAllocationType).HasColumnName(@"BillingAllocationTypeId").HasColumnType("int").IsRequired();
            Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();
            Property(x => x.LinkedPolicyPaymentAllocationId).HasColumnName(@"LinkedPolicyPaymentAllocationId").HasColumnType("int").IsOptional();

            // Foreign keys
            HasOptional(a => a.LinkedPolicyPaymentAllocation).WithMany(b => b.PolicyPaymentAllocations).HasForeignKey(c => c.LinkedPolicyPaymentAllocationId).WillCascadeOnDelete(false); // FK_PolicyPaymentAllocation_PolicyPaymentAllocation
            HasRequired(a => a.Transaction).WithMany(b => b.PolicyPaymentAllocations).HasForeignKey(c => c.TransactionId).WillCascadeOnDelete(false); // FK__PolicyPay__Trans__19CEC385
            HasRequired(a => a.TransactionTypeLink).WithMany(b => b.PolicyPaymentAllocations).HasForeignKey(c => c.TransactionTypeLinkId).WillCascadeOnDelete(false); // FK__PolicyPay__Trans__1BB70BF7
        }
    }

}
