//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.FinCare.Contracts.Enums;
using RMA.Service.FinCare.Database.Entities;

namespace RMA.Service.FinCare.Database.Configuration
{
    public class billing_AdhocPaymentInstructionConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<billing_AdhocPaymentInstruction>
    {
        public billing_AdhocPaymentInstructionConfiguration()
            : this("billing")
        {
        }

        public billing_AdhocPaymentInstructionConfiguration(string schema)
        {
            ToTable("AdhocPaymentInstructions", schema);
            HasKey(x => x.AdhocPaymentInstructionId);

            Property(x => x.AdhocPaymentInstructionId).HasColumnName(@"AdhocPaymentInstructionId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.DateToPay).HasColumnName(@"DateToPay").HasColumnType("date").IsRequired();
            Property(x => x.AdhocPaymentInstructionStatus).HasColumnName(@"AdhocPaymentInstructionStatusId").HasColumnType("int").IsRequired();
            Property(x => x.Reason).HasColumnName(@"Reason").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.Amount).HasColumnName(@"Amount").HasColumnType("money").IsRequired().HasPrecision(19,4);
            Property(x => x.RolePlayerId).HasColumnName(@"RolePlayerId").HasColumnType("int").IsRequired();
            Property(x => x.RolePlayerName).HasColumnName(@"RolePlayerName").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(255);
            Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.ErrorDescription).HasColumnName(@"ErrorDescription").HasColumnType("nvarchar").IsOptional().HasMaxLength(150);
            Property(x => x.RolePlayerBankingId).HasColumnName(@"RolePlayerBankingId").HasColumnType("int").IsOptional();
        }
    }

}
