//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.FinCare.Contracts.Enums;
using RMA.Service.FinCare.Database.Entities;

namespace RMA.Service.FinCare.Database.Configuration
{
    public class billing_EmailedDocumentConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<billing_EmailedDocument>
    {
        public billing_EmailedDocumentConfiguration()
            : this("billing")
        {
        }

        public billing_EmailedDocumentConfiguration(string schema)
        {
            ToTable("EmailedDocument", schema);
            HasKey(x => x.EmailedDocumentId);

            Property(x => x.EmailedDocumentId).HasColumnName(@"EmailedDocumentId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.SendGridRequestId).HasColumnName(@"SendGridRequestId").HasColumnType("uniqueidentifier").IsRequired();
            Property(x => x.SendGridStatus).HasColumnName(@"SendGridStatusId").HasColumnType("int").IsOptional();
            Property(x => x.DocumentType).HasColumnName(@"DocumentTypeId").HasColumnType("int").IsRequired();
            Property(x => x.TransactionId).HasColumnName(@"TransactionId").HasColumnType("int").IsRequired();
            Property(x => x.NumberOfRetries).HasColumnName(@"NumberOfRetries").HasColumnType("int").IsOptional();
            Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.SendGridMessage).HasColumnName(@"SendGridMessage").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);

            // Foreign keys
            HasRequired(a => a.Transaction).WithMany(b => b.EmailedDocuments).HasForeignKey(c => c.TransactionId).WillCascadeOnDelete(false); // FK_EmailedDocumentStatus_Transactions
        }
    }

}
