//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.FinCare.Contracts.Enums;
using RMA.Service.FinCare.Database.Entities;

namespace RMA.Service.FinCare.Database.Configuration
{
    public class Load_StageGroupRiskErrorConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Load_StageGroupRiskError>
    {
        public Load_StageGroupRiskErrorConfiguration()
            : this("Load")
        {
        }

        public Load_StageGroupRiskErrorConfiguration(string schema)
        {
            ToTable("StageGroupRiskError", schema);
            HasKey(x => x.StageGroupRiskErrorId);

            Property(x => x.StageGroupRiskErrorId).HasColumnName(@"StageGroupRiskErrorId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.StageGroupRiskId).HasColumnName(@"StageGroupRiskId").HasColumnType("int").IsOptional();
            Property(x => x.ErrorMessage).HasColumnName(@"ErrorMessage").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
            Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();
            Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.ByPassError).HasColumnName(@"ByPassError").HasColumnType("bit").IsRequired();

            // Foreign keys
            HasOptional(a => a.StageGroupRisk).WithMany(b => b.StageGroupRiskErrors).HasForeignKey(c => c.StageGroupRiskId).WillCascadeOnDelete(false); // FK__StageGrou__Stage__74277233
        }
    }

}
