//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.FinCare.Contracts.Enums;
using RMA.Service.FinCare.Database.Entities;

namespace RMA.Service.FinCare.Database.Configuration
{
    public class payment_PaymentAccountConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<payment_PaymentAccount>
    {
        public payment_PaymentAccountConfiguration()
            : this("payment")
        {
        }

        public payment_PaymentAccountConfiguration(string schema)
        {
            ToTable("PaymentAccounts", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType("bit").IsRequired();
            Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.AccountNumber).HasColumnName(@"AccountNumber").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(17);
            Property(x => x.AccountNumberDesc).HasColumnName(@"AccountNumberDesc").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(100);
            Property(x => x.TransactionType).HasColumnName(@"TransactionType").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(5);
            Property(x => x.DocType).HasColumnName(@"DocType").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(2);
            Property(x => x.PaymentType).HasColumnName(@"PaymentTypeId").HasColumnType("int").IsRequired();
            Property(x => x.ClaimType).HasColumnName(@"ClaimTypeId").HasColumnType("int").IsOptional();
            Property(x => x.CanEdit).HasColumnName(@"CanEdit").HasColumnType("bit").IsRequired();
            Property(x => x.Group).HasColumnName(@"Group").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(20);
            Property(x => x.ClientType).HasColumnName(@"ClientTypeId").HasColumnType("int").IsOptional();
            Property(x => x.IndustryClass).HasColumnName(@"IndustryClassId").HasColumnType("int").IsOptional();
        }
    }

}
