CREATE TABLE [claim].[ClaimEstimate] (
    [ClaimEstimateId]       INT             IDENTITY (1, 1) NOT NULL,
    [PersonEventId]         INT             NOT NULL,
    [EstimateTypeID]        INT             NOT NULL,
    [BenefitID]             INT             NULL,
    [EstimatedExtent]       DECIMAL (18, 2) NULL,
    [EstimatedValue]        DECIMAL (18, 2) NULL,
    [EstimatedDaysOff]      DECIMAL (18, 2) NULL,
    [AllocatedExtent]       DECIMAL (18, 2) NULL,
    [AllocatedValue]        DECIMAL (18, 2) NULL,
    [AllocatedDaysOff]      DECIMAL (18, 2) NULL,
    [AuthorisedExtent]      DECIMAL (18, 2) NULL,
    [AuthorisedValue]       DECIMAL (18, 2) NULL,
    [AuthorisedDaysOff]     DECIMAL (18, 2) NULL,
    [SettledExtent]         DECIMAL (18, 2) NULL,
    [SettledValue]          DECIMAL (18, 2) NULL,
    [SettledDaysOff]        DECIMAL (18, 2) NULL,
    [EarningsID]            INT             NULL,
    [IsOverrideExtent]      BIT             DEFAULT ((0)) NOT NULL,
    [IsOverrideValue]       BIT             DEFAULT ((0)) NOT NULL,
    [IsOverrideDaysOff]     BIT             DEFAULT ((0)) NOT NULL,
    [IsFinalised]           BIT             DEFAULT ((0)) NOT NULL,
    [CalcOperands]          VARCHAR (7800)  NULL,
    [OutstandingValue]      AS              (isnull([EstimatedValue],(0))-isnull([AuthorisedValue],(0))),
    [OutstandingExtent]     AS              (isnull([EstimatedExtent],(0))-isnull([AuthorisedExtent],(0))),
    [OutstandingDaysOff]    AS              (isnull([EstimatedDaysOff],(0))-isnull([AuthorisedDaysOff],(0))),
    [AutoIncreasedAmount]   DECIMAL (18, 2) NULL,
    [OutstandingReserved]   DECIMAL (18, 2) NULL,
    [AutomatedSTPProcess]   BIT             NULL,
    [Notes]                 VARCHAR (MAX)   NULL,
    [EstimatedValueExclVAT] DECIMAL (18, 2) NULL,
    [EstimatedValueVAT]     DECIMAL (18, 2) NULL,
    [IsDeleted]             BIT             NOT NULL,
    [CreatedBy]             VARCHAR (50)    NOT NULL,
    [CreatedDate]           DATETIME        NOT NULL,
    [ModifiedBy]            VARCHAR (50)    NOT NULL,
    [ModifiedDate]          DATETIME        NOT NULL,
    [OutstandingPD]         INT             DEFAULT ((0)) NOT NULL,
    [AuthorisedPD]          INT             DEFAULT ((0)) NOT NULL,
    [EstimatePD]            INT             DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_ClaimEstimate] PRIMARY KEY CLUSTERED ([ClaimEstimateId] ASC),
    CONSTRAINT [FK_ClaimEstimate_Earnings] FOREIGN KEY ([EarningsID]) REFERENCES [claim].[Earnings] ([EarningId]),
    CONSTRAINT [FK_ClaimEstimate_EstimateTypes] FOREIGN KEY ([EstimateTypeID]) REFERENCES [claim].[EstimateTypes] ([EstimateTypeId]),
    CONSTRAINT [FK_ClaimEstimate_PersonEvent] FOREIGN KEY ([PersonEventId]) REFERENCES [claim].[PersonEvent] ([PersonEventId])
);

