
CREATE PROCEDURE [policy].[ExpenseBasedPolicyScheduleJSON]
	@WizardId INT 
	AS

--Declare @WizardId INT 
--Set @WizardId = 54439 -- 46534


BEGIN

DECLARE
	@jsonData NVARCHAR(MAX),
	@policyId INT,
	@tenantId INT,
	@quoteId INT,
	@productOptionId INT,
	@policyOwnerId INT,
	@policyOwner VARCHAR(50),
	@clientName VARCHAR(50),
	@policyPayeeId INT,
	@paymentFrequency INT,  
	@paymentMethod INT, 
	@policyNumber VARCHAR(50), 
	@policyInceptionDate DATETIME, 
	@expiryDate DATETIME,
	@cancellationDate DATETIME, 
	@firstInstallmentDate DATETIME, 
	@lastInstallmentDate DATETIME, 
	@regularInstallmentDayOfMonth INT, 
	@decemberInstallmentDayOfMonth INT, 
	@policyStatus INT,
	@annualPremium DECIMAL(18,2), 
	@installmentPremium DECIMAL(18,2),
	@adminPercentage DECIMAL(18,2), 
	@commissionPercentage DECIMAL(18,2), 
	@binderFeePercentage DECIMAL(18,2), 
	@isDeleted BIT,
	@createdBy VARCHAR(50),
	@createdDate DATETIME, 
	@modifiedBy VARCHAR(50), 
	@modifiedDate DATETIME, 
	@policyCancelReasonId INT, 
	@clientReference VARCHAR(100), 
	@lastLapsedDate DATETIME, 
	@lapsedCount INT, 
	@lastReinstateDate DATETIME, 
	@canEdit BIT,
	@canAdd BIT, 
	@canRemove BIT, 
	@policyBrokers VARCHAR(50), 
	@productOption INT, 
	@policyMovementId INT, 
	@representativeId INT,
	@juristicRepresentativeId INT, 
	@brokerageId INT, 
	@policyInsuredLives INT, 
	@parentPolicyId INT, 
	@paymentFrequencyId INT,
	@paymentMethodId INT, 
	@policyStatusId INT, 
	@canLapse BIT,
	@RolePlayerBenefitWaitingPeriodId VARCHAR(50)

SELECT @jsonData = [Data] FROM bpm.Wizard WHERE Id = @WizardId

SELECT
	@policyId = CONVERT(INT, json_value(WIZARD.[Data], '$[0].policyId')),
	@tenantId = CONVERT(INT, json_value(WIZARD.[Data], '$[0].tenantId')),
	@quoteId = CONVERT(INT, json_value(WIZARD.[Data], '$[0].quoteId')),
	@productOptionId = CONVERT(INT, json_value(WIZARD.[Data], '$[0].productOptionId')),
	@policyOwnerId = CONVERT(INT, json_value(WIZARD.[Data], '$[0].policyOwnerId')),
	@policyOwner = CONVERT(VARCHAR, json_value(WIZARD.[Data], '$[0].policyOwner')),
	@clientName = CONVERT(VARCHAR, json_value(WIZARD.[Data], '$[0].clientName')),
	@policyPayeeId = CONVERT(INT, json_value(WIZARD.[Data], '$[0].policyPayeeId')),
	@paymentFrequency = CONVERT(INT, json_value(WIZARD.[Data], '$[0].paymentFrequency')),
	@paymentMethod = CONVERT(INT, json_value(WIZARD.[Data], '$[0].paymentMethod')),
	@policyNumber = CONVERT(VARCHAR, json_value(WIZARD.[Data], '$[0].policyNumber')),
	@policyInceptionDate = CONVERT(DATETIME, json_value(WIZARD.[Data], '$[0].policyInceptionDate')),
	--@policyInceptionDate = GETDATE(),
	@expiryDate = CONVERT(DATETIME, json_value(WIZARD.[Data], '$[0].expiryDate')),
	@cancellationDate = CONVERT(DATETIME, json_value(WIZARD.[Data], '$[0].cancellationDate')),
	--@firstInstallmentDate = CONVERT(DATETIME, json_value(WIZARD.[Data], '$[0].firstInstallmentDate')),
	--@firstInstallmentDate = GETDATE(),
	@lastInstallmentDate = CONVERT(DATETIME, json_value(WIZARD.[Data], '$[0].lastInstallmentDate')),
	@regularInstallmentDayOfMonth = CONVERT(INT, json_value(WIZARD.[Data], '$[0].regularInstallmentDayOfMonth')),
	@decemberInstallmentDayOfMonth = CONVERT(INT, json_value(WIZARD.[Data], '$[0].decemberInstallmentDayOfMonth')),
	@policyStatus = CONVERT(INT, json_value(WIZARD.[Data], '$[0].policyStatus')),
	@annualPremium = CONVERT(DECIMAL, json_value(WIZARD.[Data], '$[0].annualPremium')),
	@installmentPremium = CONVERT(DECIMAL, json_value(WIZARD.[Data], '$[0].installmentPremium')),
	@adminPercentage = CONVERT(DECIMAL, json_value(WIZARD.[Data], '$[0].adminPercentage')),
	@commissionPercentage = CONVERT(DECIMAL, json_value(WIZARD.[Data], '$[0].commissionPercentage')),
	@binderFeePercentage = CONVERT(DECIMAL(18,2), json_value(WIZARD.[Data], '$[0].binderFeePercentage')),
	@isDeleted = CONVERT(BIT, json_value(WIZARD.[Data], '$[0].isDeleted')), 
	@createdBy = CONVERT(VARCHAR(50), json_value(WIZARD.[Data], '$[0].createdBy')), 
	--@createdDate = CONVERT(DATETIME, json_value(WIZARD.[Data], '$[0].createdDate')), 
	@createdDate = GETDATE(), 
	@modifiedBy = CONVERT(VARCHAR(50), json_value(WIZARD.[Data], '$[0].modifiedBy')), 
	--@modifiedDate = CONVERT(DATETIME, json_value(WIZARD.[Data], '$[0].modifiedDate')), 
	@modifiedDate = GETDATE(), 
	@policyCancelReasonId = CONVERT(INT, json_value(WIZARD.[Data], '$[0].policyCancelReasonId')),
	@clientReference = CONVERT(VARCHAR(100), json_value(WIZARD.[Data], '$[0].clientReference')), 
	@lastLapsedDate = CONVERT(DATETIME, json_value(WIZARD.[Data], '$[0].lastLapsedDate')), 
	@lapsedCount = CONVERT(INT, json_value(WIZARD.[Data], '$[0].lapsedCount')), 
	@lastReinstateDate = CONVERT(DATETIME, json_value(WIZARD.[Data], '$[0].lastReinstateDate')), 
	@canEdit = CONVERT(BIT, json_value(WIZARD.[Data], '$[0].canEdit')), 
	@canAdd = CONVERT(BIT, json_value(WIZARD.[Data], '$[0].canAdd')), 
	@canRemove = CONVERT(BIT, json_value(WIZARD.[Data], '$[0].canRemove')), 
	@policyBrokers = CONVERT(VARCHAR(50), json_value(WIZARD.[Data], '$[0].policyBrokers')),
	@productOption = CONVERT(INT, json_value(WIZARD.[Data], '$[0].productOption')), 
	@policyMovementId = CONVERT(INT, json_value(WIZARD.[Data], '$[0].policyMovementId')), 
	@representativeId = CONVERT(INT, json_value(WIZARD.[Data], '$[0].representativeId')), 
	@juristicRepresentativeId = CONVERT(INT, json_value(WIZARD.[Data], '$[0].juristicRepresentativeId')), 
	@brokerageId = CONVERT(INT, json_value(WIZARD.[Data], '$[0].brokerageId')), 
	@policyInsuredLives = CONVERT(INT, json_value(WIZARD.[Data], '$[0].policyInsuredLives')), 
	@parentPolicyId = CONVERT(INT, json_value(WIZARD.[Data], '$[0].parentPolicyId')), 
	@paymentFrequencyId = CONVERT(INT, json_value(WIZARD.[Data], '$[0].paymentFrequencyId')), 
	@paymentMethodId = CONVERT(INT, json_value(WIZARD.[Data], '$[0].paymentMethodId')), 
	@policyStatusId = CONVERT(INT, json_value(WIZARD.[Data], '$[0].policyStatusId')), 
	@canLapse = CONVERT(BIT, json_value(WIZARD.[Data], '$[0].canLapse'))
	FROM [bpm].[Wizard] WIZARD
	WHERE WIZARD.[Id] = @WizardId

	SELECT TOP 1 
	@RolePlayerBenefitWaitingPeriodId = (Select [Name] from [azd-mcc].[common].RolePlayerBenefitWaitingPeriod where Id = crp.RolePlayerBenefitWaitingPeriodId)
	from [client].[Company] cc
	Inner Join [common].[Industry] ci on ci.Id = cc.IndustryId
	Inner Join [common].[IndustryClass] cic on cic.Id = cc.IndustryClassId
	left Join [client].[RolePlayerContact] crc on cc.RolePlayerId = crc.RolePlayerId
	Inner Join [client].[RolePlayer] crp On crp.RolePlayerId = cc.RolePlayerId
	where cc.RolePlayerId = @policyOwnerId

SELECT
	@policyId AS PolicyId,
	@tenantId AS TenantId,
	@quoteId As QuoteId,
	@productOptionId AS ProductOptionId,
	@policyOwnerId AS PolicyOwnerId,
	@policyOwner AS PolicyOwner,
	@clientName AS ClientName,
	@policyPayeeId AS PolicyPayeeId,
	@paymentFrequency AS PaymentFrequency,
	@paymentMethod AS PaymentMethod,
	@policyNumber AS PolicyNumber,
	@policyInceptionDate AS PolicyInceptionDate,
	@expiryDate AS ExpiryDate,
	@cancellationDate AS CancellationDate,
	@firstInstallmentDate AS FirstInstallmentDate,
	@lastInstallmentDate AS LastInstallmentDate,
	@regularInstallmentDayOfMonth AS RegularInstallmentDayOfMonth,
	@decemberInstallmentDayOfMonth AS DdecemberInstallmentDayOfMonth,
	@policyStatus AS PolicyStatus,
	@annualPremium AS AnnualPremium,
	@installmentPremium AS InstallmentPremium,
	@adminPercentage AS AdminPercentage,
	@commissionPercentage AS CommissionPercentage,
	@binderFeePercentage AS BinderFeePercentage,
	@isDeleted AS IsDeleted,
	@createdBy AS CreatedBy,
	@createdDate AS CreatedDate,
	@modifiedBy AS ModifiedBy,
	@modifiedDate AS ModifiedDate,
	@policyCancelReasonId AS PolicyCancelReasonId,
	@clientReference AS ClientReference,
	@lastLapsedDate AS LastLapsedDate,
	@lapsedCount AS LapsedCount,
	@lastReinstateDate AS LastReinstateDate, 
	@canEdit AS CanEdit,
	@canAdd AS CanAdd,
	@canRemove AS CanRemove,
	@policyBrokers AS PolicyBrokers,
	@productOption AS ProductOption,
	@policyMovementId AS PolicyMovementId,
	@representativeId AS RepresentativeId,
	@juristicRepresentativeId AS JuristicRepresentativeId,
	@brokerageId AS BrokerageId,
	@policyInsuredLives AS PolicyInsuredLives,
	@parentPolicyId AS ParentPolicyId,
	@paymentFrequencyId AS PaymentFrequencyId,
	@paymentMethodId AS PaymentMethodId,
	@policyStatusId AS PolicyStatusId,
	@canLapse AS CanLapse,
	@RolePlayerBenefitWaitingPeriodId AS RolePlayerBenefitWaitingPeriodId
END