using Microsoft.ServiceFabric.Services.Remoting;

using RMA.Common.Entities;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace RMA.Service.Admin.MasterDataManager.Contracts.Interfaces
{
    public interface ILookupService : IService
    {
        Task<List<Lookup>> GetAddressTypes();
        Task<List<Lookup>> GetApprovalTypes();
        Task<List<Lookup>> GetBankAccountServiceTypes();
        Task<List<Lookup>> GetBankAccountTypes();
        Task<List<Lookup>> GetBeneficiaryTypes();
        Task<List<Lookup>> GetBeneficiaryTypesById(List<int> ids);
        Task<List<Lookup>> GetBenefitTypes();
        Task<List<Lookup>> GetCampaignAudienceTypes();
        Task<List<Lookup>> GetCampaignCategories();
        Task<List<Lookup>> GetCampaignItemTypes();
        Task<List<Lookup>> GetCampaignStatuses();
        Task<List<Lookup>> GetCampaignTypes();
        Task<List<Lookup>> GetCancellationReasons();
        Task<List<Lookup>> CoidPolicyCancelReason();
        Task<List<Lookup>> GetCaseStatuses();
        Task<List<Lookup>> GetClaimTypes();
        Task<List<Lookup>> GetClientItemTypes();
        Task<List<Lookup>> GetClientStatuses();
        Task<List<Lookup>> GetClientTypes();
        Task<List<Lookup>> GetCommunicationTypes();
        Task<List<Lookup>> GetContactTypes();
        Task<List<Lookup>> GetCoverMemberTypes();
        Task<List<Lookup>> GetCoverTypes();
        Task<List<Lookup>> GetDeathTypes();
        Task<List<Lookup>> GetDebitOrderRejectionReasons();
        Task<List<Lookup>> GetDebitOrderStatuses();
        Task<List<Lookup>> GetDecisions();
        Task<List<Lookup>> GetDeclarationStatuses();
        Task<List<Lookup>> GetDeclarationTypes();
        Task<List<Lookup>> GetDocumentCategories();
        Task<List<Lookup>> GetDocumentCategoryTypes();
        Task<List<Lookup>> GetDocumentTypes();
        Task<List<Lookup>> GetEarningStatuses();
        Task<List<Lookup>> GetEarningsTypes();
        Task<List<Lookup>> GetEarningsTypesById(List<int> ids);
        Task<List<Lookup>> GetEnquiryQueryTypes();
        Task<List<Lookup>> GetEventTypes();
        Task<List<Lookup>> GetFormLetterTypes();
        Task<List<Lookup>> GetIdTypes();
        Task<List<Lookup>> GetImportStatuses();
        Task<List<Lookup>> GetImportTypes();
        Task<List<Lookup>> GetIndustryClasses();
        Task<List<Lookup>> GetIndustries();
        Task<List<Lookup>> GetInsureLifeCancelReasons();
        Task<List<Lookup>> GetItemTypes();
        Task<List<Lookup>> GetLanguages();
        Task<List<Lookup>> GetLeadClientStatuses();
        Task<List<Lookup>> GetLeadItemTypes();
        Task<List<Lookup>> GetMedicalReportTypes();
        Task<List<Lookup>> GetMedicalReportTypesById(List<int> ids);
        Task<List<Lookup>> GetMembershipTypes();
        Task<List<Lookup>> GetNotificationTemplateTypes();
        Task<List<Lookup>> GetPaymentAllocationStatuses();
        Task<List<Lookup>> GetPaymentArrangementStatuses();
        Task<List<Lookup>> GetPaymentFrequencies();
        Task<List<Lookup>> GetPaymentMethods();
        Task<List<Lookup>> GetPaymentRejectionTypes();
        Task<List<Lookup>> GetPaymentStatuses();
        Task<List<Lookup>> GetPaymentTypes();
        Task<List<Lookup>> GetPhoneTypes();
        Task<List<Lookup>> GetPolicyItemTypes();
        Task<List<Lookup>> GetPolicyStatuses();
        Task<List<Lookup>> GetProductClasses();
        Task<List<Lookup>> GetProductItemTypes();
        Task<List<Lookup>> GetProductStatuses();
        Task<List<Lookup>> GetQuoteStatuses();
        Task<List<Lookup>> GetRateStatuses();
        Task<List<Lookup>> GetRateTypes();
        Task<List<Lookup>> GetRecipientTypes();
        Task<List<Lookup>> GetRegions();
        Task<List<Lookup>> GetRepRoles();
        Task<List<Lookup>> GetRepTypes();
        Task<List<Lookup>> GetRulesItemTypes();
        Task<List<Lookup>> GetRuleTypes();
        Task<List<Lookup>> GetSecurityItemTypes();
        Task<List<Lookup>> GetServiceTypes();
        Task<List<Lookup>> GetSkillSubCategories();
        Task<List<Lookup>> GetTaskScheduleFrequencies();
        Task<List<Lookup>> GetTemplateTypes();
        Task<List<Lookup>> GetTitles();
        Task<List<Lookup>> GetTransactionTypes();
        Task<List<Lookup>> GetAuthenticationTypes();
        Task<List<Lookup>> GetWizardPermissionTypes();
        Task<List<Lookup>> GetWizardStatuses();
        Task<List<Lookup>> GetWordProcessingDocumentTypes();
        Task<List<Lookup>> GetWorkPools();
        Task<List<Lookup>> GetCities();
        Task<List<Lookup>> GetInvoiceStatuses();
        Task<List<Lookup>> GetInsuredLifeStatuses();
        Task<List<Lookup>> GetRolePlayerTypes();
        Task<List<Lookup>> GetCommissionWithholdingReason();
        Task<List<Lookup>> GetCommissionActionType();
        Task<List<Lookup>> GetRefundReason();
        Task<List<Lookup>> GetPreviousInsurers();
        Task<List<Lookup>> GetBodySideAffected();
        Task<List<Lookup>> GetWorkOptions();
        Task<List<Lookup>> GetProductType();
        Task<List<Lookup>> CoverOptionTypes();
        Task<List<Lookup>> GetPortalTypes();
        Task<List<Lookup>> GetUserProfileTypes();
        Task<List<Lookup>> GetInjurySeverity();
        Task<List<Lookup>> GetMedicalFormReportType();
        Task<List<Lookup>> GetMedicalReportCategory();
        Task<List<Lookup>> GetWorkItemState();
        Task<List<Lookup>> GetPreAuthTypes();
        Task<List<Lookup>> GetPreAuthStatuses();
        Task<List<Lookup>> GetReInstateReason();
        Task<List<Lookup>> GetLocationCategory();
        Task<List<Lookup>> GetContactDesignationType();
        Task<List<Lookup>> GetContactInformationType();
        Task<List<Lookup>> GetGenders();
        Task<List<Lookup>> GetMaritalStatus();
        Task<List<Lookup>> GetNationalities();
        Task<List<Lookup>> GetDaysOffWork();
        Task<List<Lookup>> GetDebitOrderTypes();
        Task<List<Lookup>> GetPensionTypes();
        Task<List<Lookup>> GetClaimTypesByEventAndParentInsuranceType(EventTypeEnum eventType, int parentInsuranceTypeId);
        Task<List<Lookup>> GetClaimTypesByEvent(EventTypeEnum eventType);
        Task<List<Lookup>> GetSuspiciousTransactionTypes();
        Task<List<Lookup>> GetClaimLiabilityStatuses();
        Task<List<Lookup>> GetUploadedFileProcessingStatuses();
        Task<List<Lookup>> GetLedgerStatusChangeReasons();
        Task<List<Lookup>> GetLedgerStatuses();
        Task<List<Lookup>> GetInterestProvisionedStatuses();
        Task<List<Lookup>> GetEntryTypes();
        Task<List<Lookup>> GetScheduleTypes();
        Task<List<Lookup>> EntryStatuses();
        Task<List<Lookup>> EntryChangeReasons();
        Task<List<Lookup>> GetMarriageTypes();
        Task<List<Lookup>> GetPopulationGroups();
        Task<List<Lookup>> IncreaseTypes();
        Task<List<Lookup>> IncreaseLegislativeValues();
        Task<List<Lookup>> GetMedicalInvoiceStatuses();
        Task<List<Lookup>> GetMedicalPractitionerTypes();
        Task<List<Lookup>> GetAdditionalTaxTypes();
        Task<List<Lookup>> GetDebtorStatuses();
        Task<List<Lookup>> GetCommissionStatuses();
        Task<List<Lookup>> GetClaimInvoiceTypes();
        Task<List<Lookup>> GetPeriodChangeReasons();
        Task<List<Lookup>> GetCompanyIdTypes();
        Task<List<Lookup>> GetCompanyLevelTypes();
        Task<List<Lookup>> GetDesignationTypes(string filter);
        Task<List<Lookup>> GetProductCategory();
        Task<List<Lookup>> GetDisabilityBenefitTerms();
        Task<List<Lookup>> GetGroupCoverAmountOptions();
        Task<List<Lookup>> CommutationReasons();
        Task<List<Lookup>> CommutationSchedules();
        Task<List<Lookup>> GetUnderwrittenOptions();
        Task<List<Lookup>> GetPolicyHolderOptions();
        Task<List<Lookup>> GetPersonInsuredCategoryStatuses();
        Task<List<Lookup>> GetOptionTypes(string brokerageType, DateTime? effectiveDate);
        Task<List<Lookup>> GetPolicyOnboardOptions();
        Task<List<Lookup>> GetClaimTypesByEventAndProductCategory(EventTypeEnum eventType, int parentInsuranceTypeId, ProductCategoryTypeEnum productCategoryType);
        Task<List<Lookup>> GetPMPRegions();
        Task<LookupValue> GetLookUpValueByLookupTypeEnum(LookupTypeEnum lookupType, DateTime serviceDate);
        Task<List<Lookup>> GetDocumentRefreshReasons();
        Task<List<Lookup>> GetRolePlayerItemQueryTypes();
        Task<List<Lookup>> GetRolePlayerQueryItemTypes();
        Task<List<Lookup>> GetRolePlayerItemQueryCategories();
        Task<List<Lookup>> GetRolePlayerItemQueryStatuses();
    }
}
