export enum ClientTypeEnum {
	Individual = 1,
	Group = 2,
	Company = 3,
	Affinity = 4,
	Goldwage = 5,
	GroupIndividual = 6,
	Corporate = 7,
	Senna = 8,
	HealthCareProvider = 9,
	All = 10,
	Parlour = 11,
	AffinityUnion = 12,
	Scheme = 13,
	Municipality = 14,
	SoleProprietor = 15,
	Trust = 16,
	Reinsurer = 17,
	RetirementUmbrellaFund = 18
}