
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Autofac;
using RMA.Common.Constants;
using RMA.Common.Service.Extensions;

namespace RMA.Service.Admin.ScheduledTaskManager
{
    public partial class ContainerConfiguration
    {
        private static void HostOurServicesPartial(ContainerBuilder builder)
        {
            builder.HostServiceBusListener<RMA.Service.Admin.ScheduledTaskManager.Contracts.Interfaces.IScheduledTaskHost, RMA.Service.Admin.ScheduledTaskManager.Services.ScheduledTaskHost>(AppPrefix.ScheduledTaskManager);
            builder.HostStatelessService<RMA.Service.Admin.ScheduledTaskManager.Contracts.Interfaces.IScheduledTaskService, RMA.Service.Admin.ScheduledTaskManager.Services.ScheduledTaskFacade>(AppNames.Admin, AppPrefix.ScheduledTaskManager);
        }
    }
}
