//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;

namespace RMA.Service.ClientCare.Database.Entities
{
    public partial class broker_BrokerageProductOption : ILazyLoadSafeEntity
    {
        public int Id { get; set; } // Id (Primary key)
        public int BrokerageId { get; set; } // BrokerageId
        public int ProductOptionId { get; set; } // ProductOptionId
        public System.DateTime StartDate { get; set; } // StartDate
        public System.DateTime? EndDate { get; set; } // EndDate

        // Foreign keys

        /// <summary>
        /// Parent broker_Brokerage pointed by [BrokerageProductOption].([BrokerageId]) (FK_BrokerageProductOption_Brokerage)
        /// </summary>
        public virtual broker_Brokerage Brokerage { get; set; } // FK_BrokerageProductOption_Brokerage

        /// <summary>
        /// Parent product_ProductOption pointed by [BrokerageProductOption].([ProductOptionId]) (FK_BrokerageProductOption_ProductOption)
        /// </summary>
        public virtual product_ProductOption ProductOption { get; set; } // FK_BrokerageProductOption_ProductOption

        public broker_BrokerageProductOption()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
