//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;

namespace RMA.Service.ClientCare.Database.Entities
{
    public partial class client_MaxAverageEarning : ILazyLoadSafeEntity
    {
        public int MaxAverageEarningsId { get; set; } // MaxAverageEarningsId (Primary key)
        public int IndustryClassDeclarationConfigurationId { get; set; } // IndustryClassDeclarationConfigurationId
        public decimal MaxAverageEarnings { get; set; } // MaxAverageEarnings
        public System.DateTime EffectiveFrom { get; set; } // EffectiveFrom
        public System.DateTime? EffectiveTo { get; set; } // EffectiveTo
        public decimal? MinAverageEarnings { get; set; } // MinAverageEarnings

        // Foreign keys

        /// <summary>
        /// Parent client_IndustryClassDeclarationConfiguration pointed by [MaxAverageEarnings].([IndustryClassDeclarationConfigurationId]) (FK_MaxAverageEarnings_IndustryClassDeclarationConfiguration)
        /// </summary>
        public virtual client_IndustryClassDeclarationConfiguration IndustryClassDeclarationConfiguration { get; set; } // FK_MaxAverageEarnings_IndustryClassDeclarationConfiguration

        public client_MaxAverageEarning()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
