//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;

namespace RMA.Service.ClientCare.Database.Entities
{
    public partial class client_QlinkReservationTransaction : IAuditableEntity, ISoftDeleteEntity
    {
        public int QlinkReservationTransactionId { get; set; } // QlinkReservationTransactionId (Primary key)
        public int QlinkParentTransactionId { get; set; } // QlinkParentTransactionId
        public int? QlinkChildTransactionId { get; set; } // QlinkChildTransactionId
        public bool ReservationActivated { get; set; } // ReservationActivated
        public bool IsDeleted { get; set; } // IsDeleted
        public System.DateTime CreatedDate { get; set; } // CreatedDate
        public string CreatedBy { get; set; } // CreatedBy (length: 50)
        public System.DateTime ModifiedDate { get; set; } // ModifiedDate
        public string ModifiedBy { get; set; } // ModifiedBy (length: 50)
        public string Comment { get; set; } // Comment (length: 300)

        // Foreign keys

        /// <summary>
        /// Parent client_QlinkTransaction pointed by [QlinkReservationTransaction].([QlinkChildTransactionId]) (FK__QlinkRese__Qlink__1AE2E34F)
        /// </summary>
        public virtual client_QlinkTransaction QlinkChildTransaction { get; set; } // FK__QlinkRese__Qlink__1AE2E34F

        /// <summary>
        /// Parent client_QlinkTransaction pointed by [QlinkReservationTransaction].([QlinkParentTransactionId]) (FK__QlinkRese__Qlink__19EEBF16)
        /// </summary>
        public virtual client_QlinkTransaction QlinkParentTransaction { get; set; } // FK__QlinkRese__Qlink__19EEBF16

        public client_QlinkReservationTransaction()
        {
            ReservationActivated = false;
            IsDeleted = false;
            CreatedDate = System.DateTime.Now;
            ModifiedDate = System.DateTime.Now;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
