//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;

namespace RMA.Service.ClientCare.Database.Entities
{
    public partial class client_FinPayee : IAuditableEntity, ISoftDeleteEntity
    {
        public int RolePlayerId { get; set; } // RolePlayerId (Primary key)
        public string FinPayeNumber { get; set; } // FinPayeNumber (length: 50)
        public bool IsAuthorised { get; set; } // IsAuthorised
        public string AuthroisedBy { get; set; } // AuthroisedBy (length: 50)
        public System.DateTime? AuthorisedDate { get; set; } // AuthorisedDate
        public bool IsDeleted { get; set; } // IsDeleted
        public string CreatedBy { get; set; } // CreatedBy (length: 50)
        public System.DateTime CreatedDate { get; set; } // CreatedDate
        public string ModifiedBy { get; set; } // ModifiedBy (length: 50)
        public System.DateTime ModifiedDate { get; set; } // ModifiedDate
        public int? IndustryId { get; set; } // IndustryId
        public DebtorStatusEnum? DebtorStatus { get; set; } // DebtorStatusId

        // Foreign keys

        /// <summary>
        /// Parent client_RolePlayer pointed by [FinPayee].([RolePlayerId]) (FK_RolePlayerFinPaye_RolePlayer)
        /// </summary>
        public virtual client_RolePlayer RolePlayer { get; set; } // FK_RolePlayerFinPaye_RolePlayer

        public client_FinPayee()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
