//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;

namespace RMA.Service.ClientCare.Database.Entities
{
    public partial class client_RolePlayerAddress : IAuditableEntity, ISoftDeleteEntity
    {
        public int RolePlayerId { get; set; } // RolePlayerId
        public AddressTypeEnum AddressType { get; set; } // AddressTypeId
        public string AddressLine1 { get; set; } // AddressLine1 (length: 50)
        public string AddressLine2 { get; set; } // AddressLine2 (length: 50)
        public string PostalCode { get; set; } // PostalCode (length: 15)
        public string City { get; set; } // City (length: 50)
        public string Province { get; set; } // Province (length: 50)
        public int CountryId { get; set; } // CountryId
        public bool IsDeleted { get; set; } // IsDeleted
        public string CreatedBy { get; set; } // CreatedBy (length: 50)
        public System.DateTime CreatedDate { get; set; } // CreatedDate
        public string ModifiedBy { get; set; } // ModifiedBy (length: 50)
        public System.DateTime ModifiedDate { get; set; } // ModifiedDate
        public int RolePlayerAddressId { get; set; } // RolePlayerAddressId (Primary key)
        public System.DateTime EffectiveDate { get; set; } // EffectiveDate
        public bool? IsPrimary { get; set; } // IsPrimary

        // Foreign keys

        /// <summary>
        /// Parent client_RolePlayer pointed by [RolePlayerAddress].([RolePlayerId]) (FK_RolePlayerAddress_RolePlayer)
        /// </summary>
        public virtual client_RolePlayer RolePlayer { get; set; } // FK_RolePlayerAddress_RolePlayer

        public client_RolePlayerAddress()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
