//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;

namespace RMA.Service.ClientCare.Database.Entities
{
    public partial class client_UserVopdResponse : ILazyLoadSafeEntity
    {
        public int UserVopdResponseId { get; set; } // UserVopdResponseId (Primary key)
        public VopdStatusEnum VopdStatus { get; set; } // VopdStatusId
        public string Reason { get; set; } // Reason (length: 255)
        public bool? Identity { get; set; } // Identity
        public bool? MaritalStatus { get; set; } // MaritalStatus
        public bool? Death { get; set; } // Death
        public System.DateTime? DateVerified { get; set; } // DateVerified
        public string IdNumber { get; set; } // IdNumber (length: 13)
        public bool? IsProcessed { get; set; } // IsProcessed

        public client_UserVopdResponse()
        {
            IsProcessed = false;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
