//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;

namespace RMA.Service.ClientCare.Database.Entities
{
    public partial class common_ReferralFeedback : IAuditableEntity, ISoftDeleteEntity
    {
        public int ReferralFeedbackId { get; set; } // ReferralFeedbackId (Primary key)
        public int ReferralId { get; set; } // ReferralId
        public string Comment { get; set; } // Comment
        public bool IsDeleted { get; set; } // IsDeleted
        public string ModifiedBy { get; set; } // ModifiedBy (length: 50)
        public System.DateTime ModifiedDate { get; set; } // ModifiedDate
        public string CreatedBy { get; set; } // CreatedBy (length: 50)
        public System.DateTime CreatedDate { get; set; } // CreatedDate

        // Foreign keys

        /// <summary>
        /// Parent common_Referral pointed by [ReferralFeedback].([ReferralId]) (FK_ReferralFeedback_Referral)
        /// </summary>
        public virtual common_Referral Referral { get; set; } // FK_ReferralFeedback_Referral

        public common_ReferralFeedback()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
