//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;

namespace RMA.Service.ClientCare.Database.Entities
{
    public partial class common_SlaItemTypeConfiguration : IAuditableEntity, ISoftDeleteEntity
    {
        public int SlaItemTypeConfigurationId { get; set; } // SLAItemTypeConfigurationId (Primary key)
        public SLAItemTypeEnum SLAItemType { get; set; } // SLAItemTypeId
        public int? NumberOfDaysAmberSla { get; set; } // NumberOfDaysAmberSLA
        public int? NumberOfDaysRedSla { get; set; } // NumberOfDaysRedSLA
        public string RedSlaNotificationPermission { get; set; } // RedSLANotificationPermission (length: 50)
        public bool IsDeleted { get; set; } // IsDeleted
        public string CreatedBy { get; set; } // CreatedBy (length: 50)
        public System.DateTime CreatedDate { get; set; } // CreatedDate
        public string ModifiedBy { get; set; } // ModifiedBy (length: 50)
        public System.DateTime ModifiedDate { get; set; } // ModifiedDate
        public string AmberSlaNotificationPermission { get; set; } // AmberSLANotificationPermission (length: 50)
        public bool? IncludeEmailNotificationAmberSla { get; set; } // IncludeEmailNotificationAmberSLA
        public bool? IncludeEmailNotificationRedSla { get; set; } // IncludeEmailNotificationRedSLA

        public common_SlaItemTypeConfiguration()
        {
            IncludeEmailNotificationAmberSla = false;
            IncludeEmailNotificationRedSla = false;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
