//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;

namespace RMA.Service.ClientCare.Database.Entities
{
    public partial class Load_ClientClass13Rates : ILazyLoadSafeEntity
    {
        public int Id { get; set; } // Id (Primary key)
        public System.Guid FileIdentifier { get; set; } // FileIdentifier
        public string RefNo { get; set; } // RefNo (length: 32)
        public string CompanyName { get; set; } // CompanyName (length: 256)
        public string Industry { get; set; } // Industry (length: 256)
        public string IndustryGroup { get; set; } // IndustryGroup (length: 32)
        public string EmpCategory { get; set; } // EmpCategory (length: 32)
        public decimal? IndRate { get; set; } // IndRate
        public decimal? PremRate { get; set; } // PremRate
        public decimal? GpLimited { get; set; } // GPLimited
        public decimal? FinalRate { get; set; } // FinalRate
        public decimal? DiscountOrLoading { get; set; } // DiscountOrLoading
        public string DiscountOrLoadingStatus { get; set; } // DiscountOrLoadingStatus (length: 32)
        public string RatingYear { get; set; } // RatingYear (length: 32)
        public System.DateTime? LoadDate { get; set; } // LoadDate
        public string Product { get; set; } // Product (length: 32)
        public string ExcelRowNumber { get; set; } // ExcelRowNumber (length: 50)
        public bool? IsExisting { get; set; } // IsExisting
        public int? UploadVersion { get; set; } // UploadVersion
        public int? UploadVersionCounter { get; set; } // UploadVersionCounter

        public Load_ClientClass13Rates()
        {
            IsExisting = false;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
