//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;

namespace RMA.Service.ClientCare.Database.Entities
{
    public partial class Load_LeadsUploadErrorAudit : ILazyLoadSafeEntity
    {
        public int Id { get; set; } // Id (Primary key)
        public string FileIdentifier { get; set; } // FileIdentifier (length: 128)
        public string FileName { get; set; } // FileName (length: 100)
        public string MemberName { get; set; } // MemberName (length: 128)
        public string ErrorCategory { get; set; } // ErrorCategory (length: 128)
        public string ErrorMessage { get; set; } // ErrorMessage (length: 256)
        public string ExcelRowNumber { get; set; } // ExcelRowNumber (length: 50)
        public System.DateTime? CreatedDate { get; set; } // CreatedDate

        public Load_LeadsUploadErrorAudit()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
