//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;

namespace RMA.Service.ClientCare.Database.Entities
{
    public partial class Load_PremiumListingCompany : IAuditableEntity
    {
        public System.Guid FileIdentifier { get; set; } // FileIdentifier (Primary key)
        public int PolicyId { get; set; } // PolicyId
        public string PolicyNumber { get; set; } // PolicyNumber (length: 32)
        public int PolicyOwnerId { get; set; } // PolicyOwnerId
        public string CompanyName { get; set; } // CompanyName (length: 64)
        public int ProductOptionId { get; set; } // ProductOptionId
        public System.DateTime PolicyInceptionDate { get; set; } // PolicyInceptionDate
        public decimal CommissionPercentage { get; set; } // CommissionPercentage
        public decimal AdminPercentage { get; set; } // AdminPercentage
        public decimal BinderFeePercentage { get; set; } // BinderFeePercentage
        public decimal PremiumAdjustmentPercentage { get; set; } // PremiumAdjustmentPercentage
        public PaymentFrequencyEnum PaymentFrequency { get; set; } // PaymentFrequencyId
        public bool IsDeleted { get; set; } // IsDeleted
        public string CreatedBy { get; set; } // CreatedBy (length: 64)
        public System.DateTime CreatedDate { get; set; } // CreatedDate
        public string ModifiedBy { get; set; } // ModifiedBy (length: 64)
        public System.DateTime ModifiedDate { get; set; } // ModifiedDate
        public bool IsEuropAssist { get; set; } // IsEuropAssist

        public Load_PremiumListingCompany()
        {
            PremiumAdjustmentPercentage = 0m;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
