//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;

namespace RMA.Service.ClientCare.Database.Entities
{
    public partial class medical_HealthCareProvider : ILazyLoadSafeEntity, IAuditableEntity, ISoftDeleteEntity, IEntityStatus
    {
        public int RolePlayerId { get; set; } // RolePlayerId (Primary key)
        public string Name { get; set; } // Name (length: 80)
        public string Description { get; set; } // Description (length: 2048)
        public string PracticeNumber { get; set; } // PracticeNumber (length: 50)
        public System.DateTime? DatePracticeStarted { get; set; } // DatePracticeStarted
        public System.DateTime? DatePracticeClosed { get; set; } // DatePracticeClosed
        public int ProviderTypeId { get; set; } // ProviderTypeId
        public bool IsVat { get; set; } // IsVat
        public string VatRegNumber { get; set; } // VATRegNumber (length: 50)
        public int? ConsultingPartnerType { get; set; } // ConsultingPartnerType
        public bool IsPreferred { get; set; } // IsPreferred
        public bool IsMedInvTreatmentInfoProvided { get; set; } // IsMedInvTreatmentInfoProvided
        public bool IsMedInvInjuryInfoProvided { get; set; } // IsMedInvInjuryInfoProvided
        public bool IsMineHospital { get; set; } // IsMineHospital
        public bool IsNeedTreatments { get; set; } // IsNeedTreatments
        public int? ArmType { get; set; } // ArmType
        public string ArmCode { get; set; } // ArmCode (length: 12)
        public int FinSystemSynchStatusId { get; set; } // FinSystemSynchStatusId
        public int HealthCareProviderGroupId { get; set; } // HealthCareProviderGroupId
        public string DispensingLicenseNo { get; set; } // DispensingLicenseNo (length: 50)
        public int? AcuteMedicalAuthNeededTypeId { get; set; } // AcuteMedicalAuthNeededTypeId
        public int? ChronicMedicalAuthNeededTypeId { get; set; } // ChronicMedicalAuthNeededTypeId
        public bool IsAllowSameDayTreatment { get; set; } // IsAllowSameDayTreatment
        public System.DateTime? AgreementEndDate { get; set; } // AgreementEndDate
        public System.DateTime? AgreementStartDate { get; set; } // AgreementStartDate
        public bool? IsAuthorised { get; set; } // IsAuthorised
        public byte? AgreementType { get; set; } // AgreementType
        public bool IsActive { get; set; } // IsActive
        public bool IsDeleted { get; set; } // IsDeleted
        public string CreatedBy { get; set; } // CreatedBy (length: 50)
        public System.DateTime CreatedDate { get; set; } // CreatedDate
        public string ModifiedBy { get; set; } // ModifiedBy (length: 50)
        public System.DateTime ModifiedDate { get; set; } // ModifiedDate
        public string Hash { get; set; } // Hash (length: 66)
        public bool IsExcludeAutoPay { get; set; } // IsExcludeAutoPay

        // Foreign keys

        /// <summary>
        /// Parent client_RolePlayer pointed by [HealthCareProvider].([RolePlayerId]) (FK_HealthCareProvider_RolePlayer_RolePlayerId)
        /// </summary>
        public virtual client_RolePlayer RolePlayer { get; set; } // FK_HealthCareProvider_RolePlayer_RolePlayerId

        public medical_HealthCareProvider()
        {
            IsExcludeAutoPay = false;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
