//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;

namespace RMA.Service.ClientCare.Database.Entities
{
    public partial class policy_PolicyInvoiceDetail : IAuditableEntity, ISoftDeleteEntity
    {
        public int PolicyInvoiceDetailId { get; set; } // PolicyInvoiceDetailId (Primary key)
        public int PolicyInvoiceid { get; set; } // PolicyInvoiceid
        public decimal? LineAmount { get; set; } // LineAmount
        public decimal LineVat { get; set; } // LineVat
        public int NumberOfLives { get; set; } // NumberOfLives
        public decimal? Earnings { get; set; } // Earnings
        public decimal? Rate { get; set; } // Rate
        public bool IsDeleted { get; set; } // IsDeleted
        public string CreatedBy { get; set; } // CreatedBy (length: 50)
        public System.DateTime CreatedDate { get; set; } // CreatedDate
        public string ModifiedBy { get; set; } // ModifiedBy (length: 50)
        public System.DateTime ModifiedDate { get; set; } // ModifiedDate

        // Foreign keys

        /// <summary>
        /// Parent policy_PolicyInvoice pointed by [PolicyInvoiceDetail].([PolicyInvoiceid]) (FK_PolicyInvoiceDetail_PolicyInvoice)
        /// </summary>
        public virtual policy_PolicyInvoice PolicyInvoice { get; set; } // FK_PolicyInvoiceDetail_PolicyInvoice

        public policy_PolicyInvoiceDetail()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
