//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;

namespace RMA.Service.ClientCare.Database.Entities
{
    public partial class policy_PolicyBenefitOption : IAuditableEntity, ISoftDeleteEntity
    {
        public int BenefitOptionId { get; set; } // BenefitOptionId (Primary key)
        public int BenefitDetailId { get; set; } // BenefitDetailId
        public int BenefitOptionItemValueId { get; set; } // BenefitOptionItemValueId
        public System.DateTime EffectiveDate { get; set; } // EffectiveDate
        public decimal? OverrideValue { get; set; } // OverrideValue
        public bool IsDeleted { get; set; } // IsDeleted
        public string CreatedBy { get; set; } // CreatedBy (length: 50)
        public System.DateTime CreatedDate { get; set; } // CreatedDate
        public string ModifiedBy { get; set; } // ModifiedBy (length: 50)
        public System.DateTime ModifiedDate { get; set; } // ModifiedDate

        // Foreign keys

        /// <summary>
        /// Parent policy_PolicyBenefitDetail pointed by [PolicyBenefitOption].([BenefitDetailId]) (PolicyBenefitDetail_PolicyBenefitOption)
        /// </summary>
        public virtual policy_PolicyBenefitDetail PolicyBenefitDetail { get; set; } // PolicyBenefitDetail_PolicyBenefitOption

        /// <summary>
        /// Parent product_BenefitOptionItemValue pointed by [PolicyBenefitOption].([BenefitOptionItemValueId]) (BenefitOptionItemValue_PolicyBenefitOption)
        /// </summary>
        public virtual product_BenefitOptionItemValue BenefitOptionItemValue { get; set; } // BenefitOptionItemValue_PolicyBenefitOption

        public policy_PolicyBenefitOption()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
