//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;

namespace RMA.Service.ClientCare.Database.Entities
{
    public partial class policy_Insurer : IAuditableEntity, ISoftDeleteEntity, IEntityStatus
    {
        public int Id { get; set; } // Id (Primary key)
        public string Code { get; set; } // Code (length: 7)
        public string Name { get; set; } // Name (length: 100)
        public bool IsActive { get; set; } // IsActive
        public bool IsDeleted { get; set; } // IsDeleted
        public string CreatedBy { get; set; } // CreatedBy (length: 50)
        public System.DateTime CreatedDate { get; set; } // CreatedDate
        public string ModifiedBy { get; set; } // ModifiedBy (length: 50)
        public System.DateTime ModifiedDate { get; set; } // ModifiedDate

        // Reverse navigation

        /// <summary>
        /// Child policy_InsurerGroupSchemeAccesses where [InsurerGroupSchemeAccess].[InsurerId] point to this entity (FK__InsurerGr__Insur__583F609C)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<policy_InsurerGroupSchemeAccess> InsurerGroupSchemeAccesses { get; set; } // InsurerGroupSchemeAccess.FK__InsurerGr__Insur__583F609C
        /// <summary>
        /// Child policy_Policies where [Policy].[InsurerId] point to this entity (FK_Policy_Insurer)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<policy_Policy> Policies { get; set; } // Policy.FK_Policy_Insurer

        public policy_Insurer()
        {
            IsActive = true;
            IsDeleted = false;
            CreatedDate = System.DateTime.Now;
            ModifiedDate = System.DateTime.Now;
            InsurerGroupSchemeAccesses = new System.Collections.Generic.List<policy_InsurerGroupSchemeAccess>();
            Policies = new System.Collections.Generic.List<policy_Policy>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
