//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;

namespace RMA.Service.ClientCare.Database.Entities
{
    public partial class product_ProductOptionOptionItemValue : IAuditableEntity, ISoftDeleteEntity
    {
        public int ProductOptionOptionItemValueId { get; set; } // ProductOptionOptionItemValueId (Primary key)
        public int ProductOptionId { get; set; } // ProductOptionId
        public int OptionItemId { get; set; } // OptionItemId
        public System.DateTime EffectiveDate { get; set; } // EffectiveDate
        public decimal? Value { get; set; } // Value
        public bool IsExtended { get; set; } // IsExtended
        public bool IsDeleted { get; set; } // IsDeleted
        public string CreatedBy { get; set; } // CreatedBy (length: 50)
        public System.DateTime CreatedDate { get; set; } // CreatedDate
        public string ModifiedBy { get; set; } // ModifiedBy (length: 50)
        public System.DateTime ModifiedDate { get; set; } // ModifiedDate
        public OptionItemFieldEnum? OptionItemField { get; set; } // OptionItemFieldId

        // Reverse navigation

        /// <summary>
        /// Child client_OrganisationOptionItemValues where [OrganisationOptionItemValue].[ProductOptionOptionItemValueId] point to this entity (OrgOptionValue_ProdOptionValue)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<client_OrganisationOptionItemValue> OrganisationOptionItemValues { get; set; } // OrganisationOptionItemValue.OrgOptionValue_ProdOptionValue
        /// <summary>
        /// Child policy_PolicyOptions where [PolicyOption].[ProductOptionOptionItemValueId] point to this entity (ProductOptionOptionItemValue_PolicyOption)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<policy_PolicyOption> PolicyOptions { get; set; } // PolicyOption.ProductOptionOptionItemValue_PolicyOption

        // Foreign keys

        /// <summary>
        /// Parent common_OptionItem pointed by [ProductOptionOptionItemValue].([OptionItemId]) (ProdOptionOptionValue_OptionItem)
        /// </summary>
        public virtual common_OptionItem OptionItem { get; set; } // ProdOptionOptionValue_OptionItem

        /// <summary>
        /// Parent product_ProductOption pointed by [ProductOptionOptionItemValue].([ProductOptionId]) (ProdOptionOptionValue_ProdOption)
        /// </summary>
        public virtual product_ProductOption ProductOption { get; set; } // ProdOptionOptionValue_ProdOption

        public product_ProductOptionOptionItemValue()
        {
            OrganisationOptionItemValues = new System.Collections.Generic.List<client_OrganisationOptionItemValue>();
            PolicyOptions = new System.Collections.Generic.List<policy_PolicyOption>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
