//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;

namespace RMA.Service.ClientCare.Database.Entities
{
    public partial class product_BenefitRule : IAuditableEntity, ISoftDeleteEntity
    {
        public int Id { get; set; } // Id (Primary key)
        public int BenefitId { get; set; } // BenefitId
        public int RuleId { get; set; } // RuleId
        public string RuleConfiguration { get; set; } // RuleConfiguration
        public bool IsDeleted { get; set; } // IsDeleted
        public string CreatedBy { get; set; } // CreatedBy (length: 50)
        public System.DateTime CreatedDate { get; set; } // CreatedDate
        public string ModifiedBy { get; set; } // ModifiedBy (length: 50)
        public System.DateTime ModifiedDate { get; set; } // ModifiedDate

        // Foreign keys

        /// <summary>
        /// Parent product_Benefit pointed by [BenefitRule].([BenefitId]) (FK_product.BenefitRule_Benefit)
        /// </summary>
        public virtual product_Benefit Benefit { get; set; } // FK_product.BenefitRule_Benefit

        public product_BenefitRule()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
