//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;

namespace RMA.Service.ClientCare.Database.Entities
{
    public partial class product_Product : IAuditableEntity, ISoftDeleteEntity
    {
        public int Id { get; set; } // Id (Primary key)
        public ProductClassEnum ProductClass { get; set; } // ProductClassId
        public int UnderwriterId { get; set; } // UnderwriterId
        public string Name { get; set; } // Name (length: 50)
        public string Code { get; set; } // Code (length: 50)
        public string Description { get; set; } // Description (length: 255)
        public System.DateTime StartDate { get; set; } // StartDate
        public System.DateTime? EndDate { get; set; } // EndDate
        public bool IsDeleted { get; set; } // IsDeleted
        public string CreatedBy { get; set; } // CreatedBy (length: 50)
        public System.DateTime CreatedDate { get; set; } // CreatedDate
        public string ModifiedBy { get; set; } // ModifiedBy (length: 50)
        public System.DateTime ModifiedDate { get; set; } // ModifiedDate
        public int? DepartmentLookupId { get; set; } // DepartmentLookupId

        // Reverse navigation

        /// <summary>
        /// Child product_BenefitProducts where [BenefitProduct].[ProductId] point to this entity (FK_BenefitProduct_Product)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<product_BenefitProduct> BenefitProducts { get; set; } // BenefitProduct.FK_BenefitProduct_Product
        /// <summary>
        /// Child product_ProductBankAccounts where [ProductBankAccount].[ProductId] point to this entity (FK_product.ProductBankAccount_Product)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<product_ProductBankAccount> ProductBankAccounts { get; set; } // ProductBankAccount.FK_product.ProductBankAccount_Product
        /// <summary>
        /// Child product_ProductNotes where [ProductNote].[ProductId] point to this entity (FK_ProductNote_Product)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<product_ProductNote> ProductNotes { get; set; } // ProductNote.FK_ProductNote_Product
        /// <summary>
        /// Child product_ProductOptions where [ProductOption].[ProductId] point to this entity (FK_product.ProductOption_Product)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<product_ProductOption> ProductOptions { get; set; } // ProductOption.FK_product.ProductOption_Product
        /// <summary>
        /// Child product_ProductRules where [ProductRule].[ProductId] point to this entity (FK_product.ProductRule_Product)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<product_ProductRule> ProductRules { get; set; } // ProductRule.FK_product.ProductRule_Product

        public product_Product()
        {
            BenefitProducts = new System.Collections.Generic.List<product_BenefitProduct>();
            ProductBankAccounts = new System.Collections.Generic.List<product_ProductBankAccount>();
            ProductNotes = new System.Collections.Generic.List<product_ProductNote>();
            ProductOptions = new System.Collections.Generic.List<product_ProductOption>();
            ProductRules = new System.Collections.Generic.List<product_ProductRule>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
