//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;

namespace RMA.Service.ClientCare.Database.Entities
{
    public partial class reinsurance_CoInsurance : IAuditableEntity, ISoftDeleteEntity
    {
        public int CoInsuranceId { get; set; } // CoInsuranceId (Primary key)
        public System.DateTime EffectiveDate { get; set; } // EffectiveDate
        public int PrimaryTreatyId { get; set; } // PrimaryTreatyId
        public int CoInsuranceTreatyId { get; set; } // CoInsuranceTreatyId
        public bool IsDeleted { get; set; } // IsDeleted
        public string CreatedBy { get; set; } // CreatedBy (length: 50)
        public System.DateTime CreatedDate { get; set; } // CreatedDate
        public string ModifiedBy { get; set; } // ModifiedBy (length: 50)
        public System.DateTime ModifiedDate { get; set; } // ModifiedDate

        // Foreign keys

        /// <summary>
        /// Parent reinsurance_Treaty pointed by [CoInsurance].([CoInsuranceTreatyId]) (Treaty_CoInsurance)
        /// </summary>
        public virtual reinsurance_Treaty CoInsuranceTreaty { get; set; } // Treaty_CoInsurance

        /// <summary>
        /// Parent reinsurance_Treaty pointed by [CoInsurance].([PrimaryTreatyId]) (Treaty_PrimaryInsurance)
        /// </summary>
        public virtual reinsurance_Treaty PrimaryTreaty { get; set; } // Treaty_PrimaryInsurance

        public reinsurance_CoInsurance()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
