//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.Billing.Database.Entities;

namespace RMA.Service.Billing.Database.Configuration
{
    public class billing_AutoAllocationBankAccountConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<billing_AutoAllocationBankAccount>
    {
        public billing_AutoAllocationBankAccountConfiguration()
            : this("billing")
        {
        }

        public billing_AutoAllocationBankAccountConfiguration(string schema)
        {
            ToTable("AutoAllocationBankAccount", schema);
            HasKey(x => x.AutoAllocationBankAccountId);

            Property(x => x.AutoAllocationBankAccountId).HasColumnName(@"AutoAllocationBankAccountId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.BankAccountId).HasColumnName(@"BankAccountId").HasColumnType("int").IsRequired();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();
        }
    }

}
