//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.Billing.Database.Entities;

namespace RMA.Service.Billing.Database.Configuration
{
    public class billing_PremiumTransactionPaymentFileConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<billing_PremiumTransactionPaymentFile>
    {
        public billing_PremiumTransactionPaymentFileConfiguration()
            : this("billing")
        {
        }

        public billing_PremiumTransactionPaymentFileConfiguration(string schema)
        {
            ToTable("PremiumTransactionPaymentFile", schema);
            HasKey(x => x.PremiumTransactionPaymentFileId);

            Property(x => x.PremiumTransactionPaymentFileId).HasColumnName(@"PremiumTransactionPaymentFileId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.PaymentFileId).HasColumnName(@"PaymentFileId").HasColumnType("int").IsRequired();
            Property(x => x.PremiumListingTransactionId).HasColumnName(@"PremiumListingTransactionId").HasColumnType("int").IsRequired();
            Property(x => x.Amount).HasColumnName(@"Amount").HasColumnType("decimal").IsRequired().HasPrecision(18,0);
            Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();

            // Foreign keys
            HasRequired(a => a.PremiumListingPaymentFile).WithMany(b => b.PremiumTransactionPaymentFiles).HasForeignKey(c => c.PaymentFileId).WillCascadeOnDelete(false); // FK_PremiumTransactionPaymentFile_PremiumListingPaymentFile
            HasRequired(a => a.PremiumListingTransaction).WithMany(b => b.PremiumTransactionPaymentFiles).HasForeignKey(c => c.PremiumListingTransactionId).WillCascadeOnDelete(false); // FK_PremiumTransactionPaymentFile_PremiumListingTransaction
        }
    }

}
