//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.Billing.Database.Entities;

namespace RMA.Service.Billing.Database.Configuration
{
    public class client_StopOrderCompanyConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<client_StopOrderCompany>
    {
        public client_StopOrderCompanyConfiguration()
            : this("client")
        {
        }

        public client_StopOrderCompanyConfiguration(string schema)
        {
            ToTable("StopOrderCompany", schema);
            HasKey(x => x.StopOrderCompanyId);

            Property(x => x.StopOrderCompanyId).HasColumnName(@"StopOrderCompanyId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.CompanyCode).HasColumnName(@"CompanyCode").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(8);
            Property(x => x.CompanyName).HasColumnName(@"CompanyName").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(128);
            Property(x => x.Report).HasColumnName(@"Report").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(128);
            Property(x => x.StopOrderExportType).HasColumnName(@"StopOrderExportTypeId").HasColumnType("int").IsRequired();
            Property(x => x.Recipient).HasColumnName(@"Recipient").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(512);
            Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType("datetime").IsOptional();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsOptional();
        }
    }

}
