//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.Billing.Database.Entities;

namespace RMA.Service.Billing.Database.Configuration
{
    public class common_AnnouncementConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<common_Announcement>
    {
        public common_AnnouncementConfiguration()
            : this("common")
        {
        }

        public common_AnnouncementConfiguration(string schema)
        {
            ToTable("Announcement", schema);
            HasKey(x => x.AnnouncementId);

            Property(x => x.AnnouncementId).HasColumnName(@"AnnouncementId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Name).HasColumnName(@"Name").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.Description).HasColumnName(@"Description").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(250);
            Property(x => x.Html).HasColumnName(@"Html").HasColumnType("varchar(max)").IsRequired().IsUnicode(false);
            Property(x => x.IsMandatory).HasColumnName(@"IsMandatory").HasColumnType("bit").IsRequired();
            Property(x => x.PriorityId).HasColumnName(@"PriorityId").HasColumnType("int").IsRequired();
            Property(x => x.IncludeAllRoles).HasColumnName(@"IncludeAllRoles").HasColumnType("bit").IsRequired();
            Property(x => x.StartDate).HasColumnName(@"StartDate").HasColumnType("datetime").IsRequired();
            Property(x => x.EndDate).HasColumnName(@"EndDate").HasColumnType("datetime").IsRequired();
            Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();
            Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("nvarchar").IsRequired().HasMaxLength(50);
            Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
        }
    }

}
