//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.Billing.Database.Entities;

namespace RMA.Service.Billing.Database.Configuration
{
    public class finance_BankAccountVerificationRequestConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<finance_BankAccountVerificationRequest>
    {
        public finance_BankAccountVerificationRequestConfiguration()
            : this("finance")
        {
        }

        public finance_BankAccountVerificationRequestConfiguration(string schema)
        {
            ToTable("BankAccountVerificationRequest", schema);
            HasKey(x => x.BankAccountVerificationRequestId);

            Property(x => x.BankAccountVerificationRequestId).HasColumnName(@"BankAccountVerificationRequestId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.BankAccountVerificationId).HasColumnName(@"BankAccountVerificationId").HasColumnType("int").IsRequired();
            Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType("bit").IsRequired();
            Property(x => x.UserId).HasColumnName(@"UserId").HasColumnType("int").IsOptional();
            Property(x => x.UserEmail).HasColumnName(@"UserEmail").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.RequestedDate).HasColumnName(@"RequestedDate").HasColumnType("datetime").IsOptional();
            Property(x => x.ResponseDate).HasColumnName(@"ResponseDate").HasColumnType("datetime").IsOptional();
            Property(x => x.BeneficiaryId).HasColumnName(@"BeneficiaryId").HasColumnType("int").IsOptional();
            Property(x => x.BankAccountId).HasColumnName(@"BankAccountId").HasColumnType("int").IsOptional();
            Property(x => x.AccountAcceptsCredits).HasColumnName(@"AccountAcceptsCredits").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(20);
            Property(x => x.AccountAcceptsDebits).HasColumnName(@"AccountAcceptsDebits").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(20);
            Property(x => x.AccountExists).HasColumnName(@"AccountExists").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(20);
            Property(x => x.AccountIdMatch).HasColumnName(@"AccountIdMatch").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(20);
            Property(x => x.AccountNumber).HasColumnName(@"AccountNumber").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.AccountOpen).HasColumnName(@"AccountOpen").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(20);
            Property(x => x.AccountOpenGtThreeMonths).HasColumnName(@"AccountOpenGtThreeMonths").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(20);
            Property(x => x.AccountType).HasColumnName(@"AccountType").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(20);
            Property(x => x.AccountTypeValid).HasColumnName(@"AccountTypeValid").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(20);
            Property(x => x.BranchCode).HasColumnName(@"BranchCode").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(20);
            Property(x => x.EmailValid).HasColumnName(@"EmailValid").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(20);
            Property(x => x.IdNumber).HasColumnName(@"IdNumber").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(15);
            Property(x => x.InitialMatch).HasColumnName(@"InitialMatch").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(20);
            Property(x => x.Initials).HasColumnName(@"Initials").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.LastName).HasColumnName(@"LastName").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(100);
            Property(x => x.LastNameMatch).HasColumnName(@"LastNameMatch").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(20);
            Property(x => x.MessageCode).HasColumnName(@"MessageCode").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(20);
            Property(x => x.MessageDescription).HasColumnName(@"MessageDescription").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
            Property(x => x.Operator).HasColumnName(@"Operator").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(20);
            Property(x => x.PhoneNumber).HasColumnName(@"PhoneNumber").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(15);
            Property(x => x.EmailAddress).HasColumnName(@"EmailAddress").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(15);
            Property(x => x.PhoneValid).HasColumnName(@"PhoneValid").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(20);
            Property(x => x.TransactionReference).HasColumnName(@"TransactionReference").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(20);
            Property(x => x.UserReference).HasColumnName(@"UserReference").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();

            // Foreign keys
            HasRequired(a => a.BankAccountVerification).WithMany(b => b.BankAccountVerificationRequests).HasForeignKey(c => c.BankAccountVerificationId).WillCascadeOnDelete(false); // FK_BankAccountVerificationRequest_BankAccountVerification
        }
    }

}
