//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.Billing.Database.Entities;

namespace RMA.Service.Billing.Database.Configuration
{
    public class Load_PremiumListingCompanyConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Load_PremiumListingCompany>
    {
        public Load_PremiumListingCompanyConfiguration()
            : this("Load")
        {
        }

        public Load_PremiumListingCompanyConfiguration(string schema)
        {
            ToTable("PremiumListingCompany", schema);
            HasKey(x => x.FileIdentifier);

            Property(x => x.FileIdentifier).HasColumnName(@"FileIdentifier").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.PolicyId).HasColumnName(@"PolicyId").HasColumnType("int").IsRequired();
            Property(x => x.PolicyNumber).HasColumnName(@"PolicyNumber").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(32);
            Property(x => x.PolicyOwnerId).HasColumnName(@"PolicyOwnerId").HasColumnType("int").IsRequired();
            Property(x => x.CompanyName).HasColumnName(@"CompanyName").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(64);
            Property(x => x.ProductOptionId).HasColumnName(@"ProductOptionId").HasColumnType("int").IsRequired();
            Property(x => x.PolicyInceptionDate).HasColumnName(@"PolicyInceptionDate").HasColumnType("date").IsRequired();
            Property(x => x.CommissionPercentage).HasColumnName(@"CommissionPercentage").HasColumnType("decimal").IsRequired().HasPrecision(8,5);
            Property(x => x.AdminPercentage).HasColumnName(@"AdminPercentage").HasColumnType("decimal").IsRequired().HasPrecision(8,5);
            Property(x => x.BinderFeePercentage).HasColumnName(@"BinderFeePercentage").HasColumnType("decimal").IsRequired().HasPrecision(8,5);
            Property(x => x.PremiumAdjustmentPercentage).HasColumnName(@"PremiumAdjustmentPercentage").HasColumnType("decimal").IsRequired().HasPrecision(18,10);
            Property(x => x.PaymentFrequency).HasColumnName(@"PaymentFrequencyId").HasColumnType("int").IsRequired();
            Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(64);
            Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(64);
            Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.IsEuropAssist).HasColumnName(@"IsEuropAssist").HasColumnType("bit").IsRequired();
        }
    }

}
