//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.Billing.Database.Entities;

namespace RMA.Service.Billing.Database.Configuration
{
    public class Load_PremiumListingMemberConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Load_PremiumListingMember>
    {
        public Load_PremiumListingMemberConfiguration()
            : this("Load")
        {
        }

        public Load_PremiumListingMemberConfiguration(string schema)
        {
            ToTable("PremiumListingMember", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.FileIdentifier).HasColumnName(@"FileIdentifier").HasColumnType("uniqueidentifier").IsRequired();
            Property(x => x.ClientReference).HasColumnName(@"ClientReference").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(64);
            Property(x => x.JoinDate).HasColumnName(@"JoinDate").HasColumnType("date").IsOptional();
            Property(x => x.CoverMemberType).HasColumnName(@"CoverMemberTypeId").HasColumnType("int").IsRequired();
            Property(x => x.RolePlayerTypeId).HasColumnName(@"RolePlayerTypeId").HasColumnType("int").IsRequired();
            Property(x => x.IdType).HasColumnName(@"IdTypeId").HasColumnType("int").IsRequired();
            Property(x => x.IdNumber).HasColumnName(@"IdNumber").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(64);
            Property(x => x.MainMemberIdNumber).HasColumnName(@"MainMemberIdNumber").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(32);
            Property(x => x.FirstName).HasColumnName(@"FirstName").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(64);
            Property(x => x.Surname).HasColumnName(@"Surname").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(64);
            Property(x => x.MemberName).HasColumnName(@"MemberName").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(128);
            Property(x => x.DateOfBirth).HasColumnName(@"DateOfBirth").HasColumnType("date").IsOptional();
            Property(x => x.Age).HasColumnName(@"Age").HasColumnType("int").IsRequired();
            Property(x => x.JoinAge).HasColumnName(@"JoinAge").HasColumnType("int").IsRequired();
            Property(x => x.BenefitName).HasColumnName(@"BenefitName").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(128);
            Property(x => x.ParentPolicyId).HasColumnName(@"ParentPolicyId").HasColumnType("int").IsRequired();
            Property(x => x.PolicyId).HasColumnName(@"PolicyId").HasColumnType("int").IsRequired();
            Property(x => x.PolicyPremium).HasColumnName(@"PolicyPremium").HasColumnType("decimal").IsRequired().HasPrecision(18,2);
            Property(x => x.ExistingCover).HasColumnName(@"ExistingCover").HasColumnType("decimal").IsOptional().HasPrecision(18,2);
            Property(x => x.Multiplier).HasColumnName(@"Multiplier").HasColumnType("int").IsRequired();
            Property(x => x.RolePlayerId).HasColumnName(@"RolePlayerId").HasColumnType("int").IsRequired();
            Property(x => x.MainMemberRolePlayerId).HasColumnName(@"MainMemberRolePlayerId").HasColumnType("int").IsRequired();
            Property(x => x.BenefitId).HasColumnName(@"BenefitId").HasColumnType("int").IsRequired();
            Property(x => x.PolicyExists).HasColumnName(@"PolicyExists").HasColumnType("bit").IsRequired();
            Property(x => x.RolePlayerExists).HasColumnName(@"RolePlayerExists").HasColumnType("bit").IsRequired();
            Property(x => x.Address1).HasColumnName(@"Address1").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(256);
            Property(x => x.Address2).HasColumnName(@"Address2").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(256);
            Property(x => x.City).HasColumnName(@"City").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(256);
            Property(x => x.Province).HasColumnName(@"Province").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(256);
            Property(x => x.Country).HasColumnName(@"Country").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(256);
            Property(x => x.PostalCode).HasColumnName(@"PostalCode").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(8);
            Property(x => x.PostalAddress1).HasColumnName(@"PostalAddress1").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(256);
            Property(x => x.PostalAddress2).HasColumnName(@"PostalAddress2").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(256);
            Property(x => x.PostalCity).HasColumnName(@"PostalCity").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(256);
            Property(x => x.PostalProvince).HasColumnName(@"PostalProvince").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(256);
            Property(x => x.PostalCountry).HasColumnName(@"PostalCountry").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(256);
            Property(x => x.PostalPostCode).HasColumnName(@"PostalPostCode").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(8);
            Property(x => x.TelNo).HasColumnName(@"TelNo").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(32);
            Property(x => x.CelNo).HasColumnName(@"CelNo").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(32);
            Property(x => x.Email).HasColumnName(@"Email").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(128);
            Property(x => x.PreferredCommunication).HasColumnName(@"PreferredCommunication").HasColumnType("int").IsOptional();
            Property(x => x.PreviousInsurer).HasColumnName(@"PreviousInsurer").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(128);
            Property(x => x.PreviousInsurerPolicyNumber).HasColumnName(@"PreviousInsurerPolicyNumber").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(64);
            Property(x => x.PreviousInsurerStartDate).HasColumnName(@"PreviousInsurerStartDate").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(32);
            Property(x => x.PreviousInsurerEndDate).HasColumnName(@"PreviousInsurerEndDate").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(32);
            Property(x => x.TestDateOfBirth).HasColumnName(@"TestDateOfBirth").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(24);
            Property(x => x.TestJoinDate).HasColumnName(@"TestJoinDate").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(24);
            Property(x => x.MemberStatus).HasColumnName(@"MemberStatus").HasColumnType("int").IsRequired();
            Property(x => x.RetirementAge).HasColumnName(@"RetirementAge").HasColumnType("int").IsOptional();
        }
    }

}
