//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.Billing.Database.Entities;

namespace RMA.Service.Billing.Database.Configuration
{
    public class Load_PaymentStagingFileConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Load_PaymentStagingFile>
    {
        public Load_PaymentStagingFileConfiguration()
            : this("Load")
        {
        }

        public Load_PaymentStagingFileConfiguration(string schema)
        {
            ToTable("PaymentStagingFile", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.FileIdentifier).HasColumnName(@"FileIdentifier").HasColumnType("uniqueidentifier").IsRequired();
            Property(x => x.FileName).HasColumnName(@"FileName").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(256);
            Property(x => x.Company).HasColumnName(@"Company").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(256);
            Property(x => x.PaymentMonthYear).HasColumnName(@"PaymentMonthYear").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(14);
            Property(x => x.TotalPaymentReceived).HasColumnName(@"TotalPaymentReceived").HasColumnType("decimal").IsRequired().HasPrecision(18,2);
            Property(x => x.CollectionFeePercentage).HasColumnName(@"CollectionFeePercentage").HasColumnType("decimal").IsRequired().HasPrecision(18,2);
            Property(x => x.CollectionFeeAmount).HasColumnName(@"CollectionFeeAmount").HasColumnType("decimal").IsRequired().HasPrecision(18,2);
            Property(x => x.CollectionFeeVatPercentage).HasColumnName(@"CollectionFeeVatPercentage").HasColumnType("decimal").IsRequired().HasPrecision(18,2);
            Property(x => x.CollectionFeeVatAmount).HasColumnName(@"CollectionFeeVatAmount").HasColumnType("decimal").IsRequired().HasPrecision(18,2);
            Property(x => x.TotalPayment).HasColumnName(@"TotalPayment").HasColumnType("decimal").IsRequired().HasPrecision(18,2);
            Property(x => x.FileProcessingStatusId).HasColumnName(@"FileProcessingStatusId").HasColumnType("int").IsOptional();
            Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();
        }
    }

}
