//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.Billing.Database.Entities;

namespace RMA.Service.Billing.Database.Configuration
{
    public class payment_AllocationConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<payment_Allocation>
    {
        public payment_AllocationConfiguration()
            : this("payment")
        {
        }

        public payment_AllocationConfiguration(string schema)
        {
            ToTable("Allocation", schema);
            HasKey(x => x.AllocationId);

            Property(x => x.AllocationId).HasColumnName(@"AllocationId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.PaymentId).HasColumnName(@"PaymentId").HasColumnType("int").IsOptional();
            Property(x => x.PayeeId).HasColumnName(@"PayeeId").HasColumnType("int").IsRequired();
            Property(x => x.AllocationStatusId).HasColumnName(@"AllocationStatusId").HasColumnType("int").IsRequired();
            Property(x => x.ClaimInvoiceAllocationId).HasColumnName(@"ClaimInvoiceAllocationId").HasColumnType("int").IsOptional();
            Property(x => x.MedicalInvoiceId).HasColumnName(@"MedicalInvoiceId").HasColumnType("int").IsOptional();
            Property(x => x.DaysOffInvoiceId).HasColumnName(@"DaysOffInvoiceId").HasColumnType("int").IsOptional();
            Property(x => x.MonthlyPensionLedgerId).HasColumnName(@"MonthlyPensionLedgerId").HasColumnType("int").IsOptional();
            Property(x => x.CommutationId).HasColumnName(@"CommutationId").HasColumnType("int").IsOptional();
            Property(x => x.OverPaymentId).HasColumnName(@"OverPaymentId").HasColumnType("int").IsOptional();
            Property(x => x.PdAwardId).HasColumnName(@"PDAwardId").HasColumnType("int").IsOptional();
            Property(x => x.PostRetirementMedicalAnnuityInvoiceHeaderId).HasColumnName(@"PostRetirementMedicalAnnuityInvoiceHeaderId").HasColumnType("int").IsOptional();
            Property(x => x.AssessedAmount).HasColumnName(@"AssessedAmount").HasColumnType("decimal").IsRequired().HasPrecision(18,2);
            Property(x => x.AssessedVat).HasColumnName(@"AssessedVAT").HasColumnType("decimal").IsRequired().HasPrecision(18,2);
            Property(x => x.AssessedAmountInclusive).HasColumnName(@"AssessedAmountInclusive").HasColumnType("decimal").IsOptional().HasPrecision(19,2).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Computed);
            Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType("bit").IsRequired();
            Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.PaymentType).HasColumnName(@"PaymentTypeId").HasColumnType("int").IsOptional();
            Property(x => x.PensionCaseNumber).HasColumnName(@"PensionCaseNumber").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.BenefitCode).HasColumnName(@"BenefitCode").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.LedgerId).HasColumnName(@"LedgerId").HasColumnType("int").IsOptional();

            // Foreign keys
            HasOptional(a => a.Payment).WithMany(b => b.Allocations).HasForeignKey(c => c.PaymentId).WillCascadeOnDelete(false); // FK_Allocation_Payment
            HasOptional(a => a.PostRetirementMedicalAnnuityInvoiceHeader).WithMany(b => b.Allocations).HasForeignKey(c => c.PostRetirementMedicalAnnuityInvoiceHeaderId).WillCascadeOnDelete(false); // FK_Allocation_PostRetirementMedicalAnnuityInvoiceHeader
            HasRequired(a => a.RolePlayer).WithMany(b => b.Allocations).HasForeignKey(c => c.PayeeId).WillCascadeOnDelete(false); // FK_Allocation_RolePlayer
        }
    }

}
