//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.Billing.Database.Entities;

namespace RMA.Service.Billing.Database.Configuration
{
    public class policy_BenefitCategoryOptionConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<policy_BenefitCategoryOption>
    {
        public policy_BenefitCategoryOptionConfiguration()
            : this("policy")
        {
        }

        public policy_BenefitCategoryOptionConfiguration(string schema)
        {
            ToTable("BenefitCategoryOption", schema);
            HasKey(x => x.CategoryOptionId);

            Property(x => x.CategoryOptionId).HasColumnName(@"CategoryOptionId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.BenefitCategoryId).HasColumnName(@"BenefitCategoryId").HasColumnType("int").IsRequired();
            Property(x => x.BenefitOptionItemValueId).HasColumnName(@"BenefitOptionItemValueId").HasColumnType("int").IsRequired();
            Property(x => x.EffectiveDate).HasColumnName(@"EffectiveDate").HasColumnType("date").IsRequired();
            Property(x => x.OverrideValue).HasColumnName(@"OverrideValue").HasColumnType("decimal").IsOptional().HasPrecision(24,6);
            Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();

            // Foreign keys
            HasRequired(a => a.PolicyBenefitCategory).WithMany(b => b.BenefitCategoryOptions).HasForeignKey(c => c.BenefitCategoryId).WillCascadeOnDelete(false); // PolicyBenefitCategory_BenefitCategoryOption
        }
    }

}
