//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.Billing.Database.Entities;

namespace RMA.Service.Billing.Database.Configuration
{
    public class policy_PolicyInvoiceConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<policy_PolicyInvoice>
    {
        public policy_PolicyInvoiceConfiguration()
            : this("policy")
        {
        }

        public policy_PolicyInvoiceConfiguration(string schema)
        {
            ToTable("PolicyInvoice", schema);
            HasKey(x => x.PolicyInvoiceId);

            Property(x => x.PolicyInvoiceId).HasColumnName(@"PolicyInvoiceId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.PolicyId).HasColumnName(@"PolicyId").HasColumnType("int").IsRequired();
            Property(x => x.InvoiceAmount).HasColumnName(@"InvoiceAmount").HasColumnType("money").IsRequired().HasPrecision(19,4);
            Property(x => x.InvoiceVat).HasColumnName(@"InvoiceVat").HasColumnType("money").IsRequired().HasPrecision(19,4);
            Property(x => x.InvoiceDate).HasColumnName(@"InvoiceDate").HasColumnType("date").IsRequired();
            Property(x => x.InvoiceStatus).HasColumnName(@"InvoiceStatusId").HasColumnType("int").IsRequired();
            Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();

            // Foreign keys
            HasRequired(a => a.Policy).WithMany(b => b.PolicyInvoices).HasForeignKey(c => c.PolicyId).WillCascadeOnDelete(false); // FK_PolicyPremium_Policy
        }
    }

}
