//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.ClaimCare.Contracts.Enums;

namespace RMA.Service.ClaimCare.Database.Entities
{
    public partial class claim_StpExitReason : ILazyLoadSafeEntity
    {
        public int StpExitReasonId { get; set; } // STPExitReasonID (Primary key)
        public string Name { get; set; } // Name (length: 100)
        public string Description { get; set; } // Description (length: 350)

        // Reverse navigation

        /// <summary>
        /// Child claim_PersonEventStpExitReasons where [PersonEventSTPExitReasons].[STPExitReasonID] point to this entity (FK_PersonEventSTPExitReasons_STPExitReason)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<claim_PersonEventStpExitReason> PersonEventStpExitReasons { get; set; } // PersonEventSTPExitReasons.FK_PersonEventSTPExitReasons_STPExitReason

        public claim_StpExitReason()
        {
            PersonEventStpExitReasons = new System.Collections.Generic.List<claim_PersonEventStpExitReason>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
