//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.ClaimCare.Contracts.Enums;

namespace RMA.Service.ClaimCare.Database.Entities
{
    public partial class claim_PdRecovery : IAuditableEntity, ISoftDeleteEntity
    {
        public int PdRecoveryId { get; set; } // PDRecoveryId (Primary key)
        public int MedicalAssessmentId { get; set; } // MedicalAssessmentId
        public int FromPdAwardId { get; set; } // FromPDAwardID
        public int? FromBeneficiaryPensionId { get; set; } // FromBeneficiaryPensionID
        public int? AgainstBeneficiaryPensionId { get; set; } // AgainstBeneficiaryPensionID
        public int PdRecoveryStatusId { get; set; } // PDRecoveryStatusID
        public decimal OriginalAmount { get; set; } // OriginalAmount
        public decimal OriginalPdExtent { get; set; } // OriginalPDExtent
        public decimal? RecoveryAmount { get; set; } // RecoveryAmount
        public decimal? RecoveryMonthlyPension { get; set; } // RecoveryMonthlyPension
        public string CalcOperands { get; set; } // CalcOperands (length: 500)
        public System.DateTime? DateRecovered { get; set; } // DateRecovered
        public bool IsDeleted { get; set; } // IsDeleted
        public string CreatedBy { get; set; } // CreatedBy (length: 50)
        public System.DateTime CreatedDate { get; set; } // CreatedDate
        public string ModifiedBy { get; set; } // ModifiedBy (length: 50)
        public System.DateTime ModifiedDate { get; set; } // ModifiedDate

        // Foreign keys

        /// <summary>
        /// Parent claim_PdAward pointed by [PDRecovery].([FromPdAwardId]) (FK_PDRecovery_PDAward)
        /// </summary>
        public virtual claim_PdAward PdAward { get; set; } // FK_PDRecovery_PDAward

        /// <summary>
        /// Parent claim_PdRecoveryStatu pointed by [PDRecovery].([PdRecoveryStatusId]) (FK_PDRecovery_PDRecoveryStatus)
        /// </summary>
        public virtual claim_PdRecoveryStatu PdRecoveryStatu { get; set; } // FK_PDRecovery_PDRecoveryStatus

        public claim_PdRecovery()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
