//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.ClaimCare.Contracts.Enums;

namespace RMA.Service.ClaimCare.Database.Entities
{
    public partial class claim_ClaimBenefitType : IAuditableEntity, ILazyLoadSafeEntity
    {
        public int ClaimBenefitTypeId { get; set; } // ClaimBenefitTypeId (Primary key)
        public string Name { get; set; } // Name (length: 50)
        public string Description { get; set; } // Description (length: 250)
        public string CreatedBy { get; set; } // CreatedBy (length: 50)
        public System.DateTime CreatedDate { get; set; } // CreatedDate
        public string ModifiedBy { get; set; } // ModifiedBy (length: 50)
        public System.DateTime ModifiedDate { get; set; } // ModifiedDate

        // Reverse navigation

        /// <summary>
        /// Child claim_ClaimBenefitsAmounts where [ClaimBenefitsAmount].[BenefitType] point to this entity (Foreign_Key_BenefitType)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<claim_ClaimBenefitsAmount> ClaimBenefitsAmounts { get; set; } // ClaimBenefitsAmount.Foreign_Key_BenefitType

        public claim_ClaimBenefitType()
        {
            ClaimBenefitsAmounts = new System.Collections.Generic.List<claim_ClaimBenefitsAmount>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
