//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.ClaimCare.Contracts.Enums;

namespace RMA.Service.ClaimCare.Database.Entities
{
    public partial class claim_ClaimWizard : IAuditableEntity, ISoftDeleteEntity
    {
        public int ClaimWizardId { get; set; } // ClaimWizardId (Primary key)
        public int? ClaimId { get; set; } // ClaimId
        public int? WizardConfigurationId { get; set; } // WizardConfigurationId
        public int? WizardId { get; set; } // WizardId
        public string WizardUrl { get; set; } // WizardURL (length: 250)
        public bool IsDeleted { get; set; } // IsDeleted
        public string CreatedBy { get; set; } // CreatedBy (length: 50)
        public System.DateTime CreatedDate { get; set; } // CreatedDate
        public string ModifiedBy { get; set; } // ModifiedBy (length: 50)
        public System.DateTime ModifiedDate { get; set; } // ModifiedDate

        public claim_ClaimWizard()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
