//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.ClaimCare.Contracts.Enums;

namespace RMA.Service.ClaimCare.Database.Entities
{
    public partial class claim_ClaimsTracing : IAuditableEntity, ISoftDeleteEntity
    {
        public int ClaimsTracingId { get; set; } // ClaimsTracingId (Primary key)
        public int ClaimId { get; set; } // ClaimId
        public int RolePlayerId { get; set; } // RolePlayerId
        public int? RolePlayerBankingId { get; set; } // RolePlayerBankingId
        public bool IsDeleted { get; set; } // IsDeleted
        public string CreatedBy { get; set; } // CreatedBy (length: 50)
        public System.DateTime CreatedDate { get; set; } // CreatedDate
        public string ModifiedBy { get; set; } // ModifiedBy (length: 50)
        public System.DateTime ModifiedDate { get; set; } // ModifiedDate

        // Foreign keys

        /// <summary>
        /// Parent claim_Claim pointed by [ClaimsTracing].([ClaimId]) (FK_ClaimsTracing_Claim)
        /// </summary>
        public virtual claim_Claim Claim { get; set; } // FK_ClaimsTracing_Claim

        public claim_ClaimsTracing()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
