//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.ClaimCare.Contracts.Enums;

namespace RMA.Service.ClaimCare.Database.Entities
{
    public partial class claim_EstimateType : IAuditableEntity, ISoftDeleteEntity
    {
        public EstimateTypeEnum EstimateType { get; set; } // EstimateTypeId (Primary key)
        public string Name { get; set; } // Name (length: 50)
        public string Description { get; set; } // Description (length: 2048)
        public bool IsAlwaysApplicable { get; set; } // IsAlwaysApplicable
        public int ClaimEstimateGroupId { get; set; } // ClaimEstimateGroupId
        public bool IsRecoverable { get; set; } // IsRecoverable
        public bool? IncludeVat { get; set; } // IncludeVat
        public bool IsDeleted { get; set; } // IsDeleted
        public string CreatedBy { get; set; } // CreatedBy (length: 50)
        public System.DateTime CreatedDate { get; set; } // CreatedDate
        public string ModifiedBy { get; set; } // ModifiedBy (length: 50)
        public System.DateTime ModifiedDate { get; set; } // ModifiedDate

        // Reverse navigation

        /// <summary>
        /// Child claim_ClaimEstimates where [ClaimEstimate].[EstimateTypeID] point to this entity (FK_ClaimEstimate_EstimateTypes)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<claim_ClaimEstimate> ClaimEstimates { get; set; } // ClaimEstimate.FK_ClaimEstimate_EstimateTypes

        // Foreign keys

        /// <summary>
        /// Parent claim_ClaimEstimateGroup pointed by [EstimateTypes].([ClaimEstimateGroupId]) (FK_EstimateType_ClaimEstimateGroup)
        /// </summary>
        public virtual claim_ClaimEstimateGroup ClaimEstimateGroup { get; set; } // FK_EstimateType_ClaimEstimateGroup

        public claim_EstimateType()
        {
            IsAlwaysApplicable = false;
            IsRecoverable = false;
            ClaimEstimates = new System.Collections.Generic.List<claim_ClaimEstimate>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
