//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.ClaimCare.Contracts.Enums;

namespace RMA.Service.ClaimCare.Database.Entities
{
    public partial class claim_ReferralDetail : IAuditableEntity, ILazyLoadSafeEntity
    {
        public int ReferralDetailId { get; set; } // ReferralDetailID (Primary key)
        public int ClaimId { get; set; } // ClaimId
        public int OwnerId { get; set; } // OwnerID
        public int ReferralQueryTypeId { get; set; } // ReferralQueryTypeID
        public string ReferralQuery { get; set; } // ReferralQuery (length: 2048)
        public string QueryFeedBack { get; set; } // QueryFeedBack (length: 2048)
        public System.DateTime? FeedbackDate { get; set; } // FeedbackDate
        public System.DateTime ReceivedDate { get; set; } // ReceivedDate
        public int? ReferralRatingId { get; set; } // ReferralRatingID
        public int ReferrerUser { get; set; } // ReferrerUser
        public int? WorkFlowNotificationId { get; set; } // WorkFlowNotificationID
        public byte ReferralStatusId { get; set; } // ReferralStatusID
        public bool IsActive { get; set; } // isActive
        public int? ContactCenterNotificationId { get; set; } // ContactCenterNotificationID
        public int? ResolutionTypeId { get; set; } // ResolutionTypeId
        public string ContextualData { get; set; } // ContextualData (length: 2048)
        public string CreatedBy { get; set; } // CreatedBy (length: 100)
        public System.DateTime CreatedDate { get; set; } // CreatedDate
        public string ModifiedBy { get; set; } // ModifiedBy (length: 100)
        public System.DateTime ModifiedDate { get; set; } // ModifiedDate
        public string ReferredToUserName { get; set; } // ReferredToUserName (length: 100)

        public claim_ReferralDetail()
        {
            IsActive = false;
            CreatedDate = System.DateTime.Now;
            ModifiedDate = System.DateTime.Now;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
