//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.ClaimCare.Contracts.Enums;

namespace RMA.Service.ClaimCare.Database.Entities
{
    public partial class claim_ClaimBenefitFormula : IAuditableEntity, ISoftDeleteEntity
    {
        public int ClaimBenefitFormulaId { get; set; } // ClaimBenefitFormulaId (Primary key)
        public int BenefitId { get; set; } // BenefitId
        public EventTypeEnum? EventType { get; set; } // EventTypeId
        public string Formula { get; set; } // Formula
        public int? ClaimEstimateTypeId { get; set; } // ClaimEstimateTypeId
        public string MinEarningsFormula { get; set; } // MinEarningsFormula
        public string MaxEarningsFormula { get; set; } // MaxEarningsFormula
        public bool IsDeleted { get; set; } // IsDeleted
        public string CreatedBy { get; set; } // CreatedBy (length: 50)
        public System.DateTime CreatedDate { get; set; } // CreatedDate
        public string ModifiedBy { get; set; } // ModifiedBy (length: 50)
        public System.DateTime ModifiedDate { get; set; } // ModifiedDate
        public decimal? EstimatedDaysOff { get; set; } // EstimatedDaysOff

        public claim_ClaimBenefitFormula()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
