import { BankAccountVerification } from 'projects/shared-components-lib/src/lib/beneficiary-banking-detail/bank-account-verification.model'

export class BeneficiaryBankDetail {
  firstname: string;
  lastname: string;
  companyName: string;
  registration: string;
  contactNumber: string;
  idNumber: string;
  addressLine1: string;
  addressLine2: string;
  beneficiaryId: number;
  passportNumber: string;
  dateOfBirth: Date;
  email: string;
  relationId: number;
  contactPerson: string;
  relationOfDeceased: string;
  bankAccounts: BankAccount[];
  messageText: string;
  beneficiaryTypeId: number;
  insuredLifeId: number;
  telephoneNumber: number;
  mobileNumber: number;
  allocationPercentage: any;
  bankAccount: BankAccount;
  IsChildDisabled: boolean;
  IsInsuredLife: boolean;
  IsBeneficiary: boolean;
  InsuredLifeProductOptionCover: number;
}

export class BankAccount {
  id: number;
  nameOfAccountHolder: string;
  bankName: string;
  bankBranchId: number;
  bankBranchName: string;
  accountNumber: string;
  bankBranchNumber: string;
  bankAccountType: string;
  isPendingEdit: boolean;
  bankId: number;
  universalBranchCode: string;
  isPendingAdd: boolean;
  createdBy: string;
  createdDate: Date ;
  modifiedBy: string;
  modifiedDate: Date | string;
  isApproved: boolean | null;
  reason: string;
  haveAllDocumentsAccepted: boolean;
  isWizardCompleted: boolean;
  messageText: string;
  accountTypeId: number;
  accountType: string;
  accountHolderName: string;
  paymentMethodId: number;
  itemId: number;
  itemType: string;
  clientId: number;
  branchId: number;
  groupId: number;
  departmentId: number;
  name: string;
  linkedId: number;
  linkedClientName: string;
  bank: string;
  branchNumber: string;
  clientName: string;
  accountName: string;
  bankAccountServiceTypes: string;
  bankAccountServiceTypeIds: number[] = [];
  verifyBankAccount: boolean;
  beneficiaryTypeId: number;
  payFromAccountId: number;
  approvalRequestedFor: string;
  approvalRequestId: number;
  bankAccountTypeId: number;
}
