//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;

namespace RMA.Service.Admin.RulesManager.Database.Entities
{
    public partial class rules_Audit : ILazyLoadSafeEntity
    {
        public int Id { get; set; } // Id (Primary key)
        public System.Guid RequestId { get; set; } // RequestId
        public string Request { get; set; } // Request
        public string Response { get; set; } // Response
        public bool OverallSuccess { get; set; } // OverallSuccess
        public string RequestedBy { get; set; } // RequestedBy (length: 50)
        public System.DateTime Timestamp { get; set; } // Timestamp

        public rules_Audit()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
