using System.ComponentModel.DataAnnotations;

namespace RMA.Service.Admin.MasterDataManager.Contracts.Enums
{
    public enum DocumentNumberTypeEnum
    {
        [Display(Name = "Product")]
        Product = 1,
        [Display(Name = "Benefit")]
        Benefit = 2,
        [Display(Name = "Product Option")]
        ProductOption = 3,
        [Display(Name = "Brokerage")]
        Brokerage = 4,
        [Display(Name = "Juristic Representative")]
        JuristicRep = 5,
        [Display(Name = "Temporary Brokerage")]
        TemporaryBrokerage = 6,
        [Display(Name = "Temporary Representative")]
        TemporaryRepresentative = 7,
        [Display(Name = "Policy Case")]
        PolicyCase = 8,
        [Display(Name = "Natural Representative")]
        NaturalRep = 9,
        [Display(Name = "RolePlayerId")]
        RolePlayerId = 10,
        [Display(Name = "PersonEventId")]
        PersonEventId = 11,
        [Display(Name = "Policy Number")]
        PolicyNumber = 14,
        [Display(Name = "Group Reference")]
        GroupReference = 15,
        [Display(Name = "Member Relations")]
        MemberRelations = 16,
        [Display(Name = "ClaimInvoiceId")]
        ClaimInvoiceId = 17,
        [Display(Name = "AccountNumber")]
        AccountNumber = 18,
        [Display(Name = "Invoice")]
        Invoice = 19,
        [Display(Name = "AdhocCollection")]
        AdhocCollection = 20,
        [Display(Name = "RefundNumber")]
        RefundNumber = 21,
        [Display(Name = "TransactionReversalNumber")]
        TransactionReversalNumber = 22,
        [Display(Name = "FirstMedicalReport")]
        FirstMedicalReport = 23,
        [Display(Name = "Lead")]
        Lead = 24,
        [Display(Name = "Quote")]
        Quote = 25,
        [Display(Name = "HospitalAuth")]
        HospitalAuth = 26,
        [Display(Name = "TreatmentAuth")]
        TreatmentAuth = 27,
        [Display(Name = "ChronicAuth")]
        ChronicAuth = 28,
        [Display(Name = "ProstheticAuth")]
        ProstheticAuth = 29,
        [Display(Name = "TebaAuth")]
        TebaAuth = 30,
        [Display(Name = "TreatingDocAuth")]
        TreatingDocAuth = 31,
        [Display(Name = "BulkAuth")]
        BulkAuth = 32,
        [Display(Name = "PhysioOTAuth")]
        PhysioOTAuth = 33,
        [Display(Name = "PersonEmploymentId")]
        PersonEmploymentId = 34,
        [Display(Name = "MedicalInvoiceNumber")]
        MedicalInvoiceNumber = 35,
        [Display(Name = "PensionCaseNumber")]
        PensionCaseNumber = 36,
        [Display(Name = "BeneficiaryId")]
        BeneficiaryId = 37,
        [Display(Name = "CommissionBatchNumber")]
        CommissionBatchNumber = 38,
        [Display(Name = "MoveRepresentativePolicies")]
        MoveRepresentativePolicies = 39,
        [Display(Name = "Representative")]
        Representative = 40,
        [Display(Name = "EventId")]
        EventId = 41,
        [Display(Name = "CreditNote")]
        CreditNote = 42,
        [Display(Name = "Interest")]
        Interest = 43,
        [Display(Name = "Reinstate")]
        Reinstate = 44,
        [Display(Name = "WriteOff")]
        WriteOff = 45,
        [Display(Name = "DebitNote")]
        DebitNote = 46,
        [Display(Name = "Refund")]
        Refund = 47,
        [Display(Name = "PaymentNumber")]
        PaymentNumber = 48,
        [Display(Name = "PremiumPayback")]
        PremiumPayback = 49,
        [Display(Name = "Referral")]
        Referral = 50,
        [Display(Name = "TebaInvoiceNumber")]
        TebaInvoiceNumber = 51,
        [Display(Name = "TravelAuthorisation")]
        TravelAuthorisation = 52,
        [Display(Name = "QueryReferenceNumber")]
        QueryReferenceNumber = 53,
    }
}
