//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;

namespace RMA.Service.Admin.MasterDataManager.Database.Entities
{
    public partial class common_Country : ILazyLoadSafeEntity, IEntityStatus
    {
        public int Id { get; set; } // Id (Primary key)
        public string Code { get; set; } // Code (length: 10)
        public string Name { get; set; } // Name (length: 50)
        public bool IsActive { get; set; } // IsActive

        // Reverse navigation

        /// <summary>
        /// Child common_StateProvinces where [StateProvince].[CountryId] point to this entity (FK_common.StateProvince_Country)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<common_StateProvince> StateProvinces { get; set; } // StateProvince.FK_common.StateProvince_Country

        public common_Country()
        {
            IsActive = true;
            StateProvinces = new System.Collections.Generic.List<common_StateProvince>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
