//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;

namespace RMA.Service.Admin.MasterDataManager.Database.Entities
{
    public partial class common_ValidityCheckSet : ISoftDeleteEntity
    {
        public int Id { get; set; } // Id (Primary key)
        public ValidityCheckTypeEnum ValidityCheckType { get; set; } // ValidityCheckTypeId
        public string Description { get; set; } // Description (length: 100)
        public string Tooltip { get; set; } // Tooltip (length: 100)
        public bool IsDeleted { get; set; } // IsDeleted
        public int ValidityCheckCategoryId { get; set; } // ValidityCheckCategoryId

        // Foreign keys

        /// <summary>
        /// Parent common_ValidityCheckCategory pointed by [ValidityCheckSet].([ValidityCheckCategoryId]) (FK_ValidityCheckSet_ValidityCheckCategory)
        /// </summary>
        public virtual common_ValidityCheckCategory ValidityCheckCategory { get; set; } // FK_ValidityCheckSet_ValidityCheckCategory

        public common_ValidityCheckSet()
        {
            IsDeleted = false;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
