//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;

namespace RMA.Service.Admin.MasterDataManager.Database.Entities
{
    public partial class common_RolePlayerItemQueryItem : IAuditableEntity, ISoftDeleteEntity
    {
        public int Id { get; set; } // Id (Primary key)
        public int RolePlayerItemQueryId { get; set; } // RolePlayerItemQueryId
        public int ItemId { get; set; } // ItemId
        public bool IsDeleted { get; set; } // IsDeleted
        public string CreatedBy { get; set; } // CreatedBy (length: 50)
        public System.DateTime CreatedDate { get; set; } // CreatedDate
        public string ModifiedBy { get; set; } // ModifiedBy (length: 50)
        public System.DateTime ModifiedDate { get; set; } // ModifiedDate

        // Foreign keys

        /// <summary>
        /// Parent common_RolePlayerItemQuery pointed by [RolePlayerItemQueryItems].([RolePlayerItemQueryId]) (FK_RolePlayerItemQueryItems_RolePlayerItemQuery)
        /// </summary>
        public virtual common_RolePlayerItemQuery RolePlayerItemQuery { get; set; } // FK_RolePlayerItemQueryItems_RolePlayerItemQuery

        public common_RolePlayerItemQueryItem()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
