//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.Admin.MasterDataManager.Database.Entities;

namespace RMA.Service.Admin.MasterDataManager.Database.Configuration
{
    public class common_MonthlyScheduledWorkPoolUserConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<common_MonthlyScheduledWorkPoolUser>
    {
        public common_MonthlyScheduledWorkPoolUserConfiguration()
            : this("common")
        {
        }

        public common_MonthlyScheduledWorkPoolUserConfiguration(string schema)
        {
            ToTable("MonthlyScheduledWorkPoolUser", schema);
            HasKey(x => x.MonthlyScheduledWorkPoolUserId);

            Property(x => x.MonthlyScheduledWorkPoolUserId).HasColumnName(@"MonthlyScheduledWorkPoolUserId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.WorkPool).HasColumnName(@"WorkPoolId").HasColumnType("int").IsRequired();
            Property(x => x.StartDate).HasColumnName(@"StartDate").HasColumnType("datetime").IsRequired();
            Property(x => x.EndDate).HasColumnName(@"EndDate").HasColumnType("datetime").IsRequired();
            Property(x => x.AssignedByUserId).HasColumnName(@"AssignedByUserId").HasColumnType("int").IsRequired();
            Property(x => x.AssignedToUserId).HasColumnName(@"AssignedToUserId").HasColumnType("int").IsRequired();
            Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();
        }
    }

}
