//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.Admin.MasterDataManager.Database.Entities;

namespace RMA.Service.Admin.MasterDataManager.Database.Configuration
{
    public class common_SftpRequestConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<common_SftpRequest>
    {
        public common_SftpRequestConfiguration()
            : this("common")
        {
        }

        public common_SftpRequestConfiguration(string schema)
        {
            ToTable("SftpRequest", schema);
            HasKey(x => x.SftpRequestId);

            Property(x => x.SftpRequestId).HasColumnName(@"SftpRequestId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.SftpRequestType).HasColumnName(@"SftpRequestTypeId").HasColumnType("int").IsRequired();
            Property(x => x.FileName).HasColumnName(@"FileName").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(300);
            Property(x => x.SftpRequestStatus).HasColumnName(@"SftpRequestStatusId").HasColumnType("int").IsRequired();
            Property(x => x.ItemsInRequest).HasColumnName(@"ItemsInRequest").HasColumnType("int").IsOptional();
            Property(x => x.NoResponses).HasColumnName(@"NoResponses").HasColumnType("int").IsRequired();
            Property(x => x.RequestedDate).HasColumnName(@"RequestedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();
            Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
        }
    }

}
