//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;
using RMA.Service.Admin.MasterDataManager.Database.Entities;

namespace RMA.Service.Admin.MasterDataManager.Database.Configuration
{
    public class common_PostalCodeConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<common_PostalCode>
    {
        public common_PostalCodeConfiguration()
            : this("common")
        {
        }

        public common_PostalCodeConfiguration(string schema)
        {
            ToTable("PostalCode", schema);
            HasKey(x => x.PostalCodeId);

            Property(x => x.PostalCodeId).HasColumnName(@"PostalCodeID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Suburb).HasColumnName(@"Suburb").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(255);
            Property(x => x.PoBoxPostalCode).HasColumnName(@"POBoxPostalCode").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(10);
            Property(x => x.StreetPostalCode).HasColumnName(@"StreetPostalCode").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(12);
            Property(x => x.IsManuallyModified).HasColumnName(@"IsManuallyModified").HasColumnType("bit").IsRequired();
            Property(x => x.LastChangedBy).HasColumnName(@"LastChangedBy").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(30);
            Property(x => x.LastChangedDate).HasColumnName(@"LastChangedDate").HasColumnType("datetime").IsOptional();
            Property(x => x.CityId).HasColumnName(@"CityID").HasColumnType("int").IsOptional();
        }
    }

}
