//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;

namespace RMA.Service.MediCare.Database.Entities
{
    public partial class medical_ModifierTariff : IAuditableEntity, ISoftDeleteEntity, IEntityStatus
    {
        public int Id { get; set; } // Id (Primary key)
        public string ModifierCode { get; set; } // ModifierCode (length: 20)
        public string TariffCode { get; set; } // TariffCode (length: 20)
        public int? PublicationId { get; set; } // PublicationId
        public int? SectionId { get; set; } // SectionId
        public decimal? Price { get; set; } // Price
        public byte? IsIncludeTariff { get; set; } // IsIncludeTariff
        public byte? IsExcludeTariff { get; set; } // IsExcludeTariff
        public bool IsActive { get; set; } // IsActive
        public bool IsDeleted { get; set; } // IsDeleted
        public string CreatedBy { get; set; } // CreatedBy (length: 50)
        public System.DateTime CreatedDate { get; set; } // CreatedDate
        public string ModifiedBy { get; set; } // ModifiedBy (length: 50)
        public System.DateTime ModifiedDate { get; set; } // ModifiedDate

        // Foreign keys

        /// <summary>
        /// Parent medical_Publication pointed by [ModifierTariff].([PublicationId]) (FK_ModifierTariff_PublicationId)
        /// </summary>
        public virtual medical_Publication Publication { get; set; } // FK_ModifierTariff_PublicationId

        /// <summary>
        /// Parent medical_Section pointed by [ModifierTariff].([SectionId]) (FK_ModifierTariff_SectionId)
        /// </summary>
        public virtual medical_Section Section { get; set; } // FK_ModifierTariff_SectionId

        public medical_ModifierTariff()
        {
            IsActive = true;
            IsDeleted = false;
            CreatedDate = System.DateTime.Now;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
