//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;

namespace RMA.Service.MediCare.Database.Entities
{
    public partial class medical_ClinicalUpdateTreatmentProtocol : IAuditableEntity, ISoftDeleteEntity, IEntityStatus
    {
        public int ClinicalUpdateTreatmentProtocolId { get; set; } // ClinicalUpdateTreatmentProtocolId (Primary key)
        public int ClinicalUpdateId { get; set; } // ClinicalUpdateId
        public int TreatmentProtocolId { get; set; } // TreatmentProtocolId
        public bool IsActive { get; set; } // IsActive
        public bool IsDeleted { get; set; } // IsDeleted
        public string CreatedBy { get; set; } // CreatedBy (length: 50)
        public System.DateTime CreatedDate { get; set; } // CreatedDate
        public string ModifiedBy { get; set; } // ModifiedBy (length: 50)
        public System.DateTime ModifiedDate { get; set; } // ModifiedDate

        // Foreign keys

        /// <summary>
        /// Parent medical_ClinicalUpdate pointed by [ClinicalUpdateTreatmentProtocol].([ClinicalUpdateId]) (FK_ClinicalUpdateTreatmentProtocol_ClinicalUpdate)
        /// </summary>
        public virtual medical_ClinicalUpdate ClinicalUpdate { get; set; } // FK_ClinicalUpdateTreatmentProtocol_ClinicalUpdate

        /// <summary>
        /// Parent medical_TreatmentProtocol pointed by [ClinicalUpdateTreatmentProtocol].([TreatmentProtocolId]) (FK_ClinicalUpdateTreatmentProtocol_TreatmentProtocol)
        /// </summary>
        public virtual medical_TreatmentProtocol TreatmentProtocol { get; set; } // FK_ClinicalUpdateTreatmentProtocol_TreatmentProtocol

        public medical_ClinicalUpdateTreatmentProtocol()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
