//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;

namespace RMA.Service.MediCare.Database.Entities
{
    public partial class medical_Tariff : IAuditableEntity, ISoftDeleteEntity
    {
        public int TariffId { get; set; } // TariffId (Primary key)
        public string ItemCode { get; set; } // ItemCode (length: 50)
        public System.DateTime ValidFrom { get; set; } // ValidFrom
        public System.DateTime ValidTo { get; set; } // ValidTo
        public int TariffBaseUnitCostId { get; set; } // TariffBaseUnitCostId
        public decimal RecommendedUnits { get; set; } // RecommendedUnits
        public VatCodeEnum VatCode { get; set; } // VatCodeId
        public PractitionerTypeEnum PractitionerType { get; set; } // PractitionerTypeId
        public int TariffTypeId { get; set; } // TariffTypeId
        public int MedicalItemId { get; set; } // MedicalItemId
        public int SectionId { get; set; } // SectionId
        public bool? IsCopiedFromNrpl { get; set; } // IsCopiedFromNRPL
        public bool IsDeleted { get; set; } // IsDeleted
        public string CreatedBy { get; set; } // CreatedBy (length: 50)
        public System.DateTime CreatedDate { get; set; } // CreatedDate
        public string ModifiedBy { get; set; } // ModifiedBy (length: 50)
        public System.DateTime ModifiedDate { get; set; } // ModifiedDate

        // Foreign keys

        /// <summary>
        /// Parent medical_MedicalItem pointed by [Tariff].([MedicalItemId]) (FK_Tariff_MedicalItemId)
        /// </summary>
        public virtual medical_MedicalItem MedicalItem { get; set; } // FK_Tariff_MedicalItemId

        /// <summary>
        /// Parent medical_TariffType pointed by [Tariff].([TariffTypeId]) (FK_Tariff_TariffTypeId)
        /// </summary>
        public virtual medical_TariffType TariffType { get; set; } // FK_Tariff_TariffTypeId

        public medical_Tariff()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
