//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;

namespace RMA.Service.MediCare.Database.Entities
{
    public partial class medical_SwitchBatchInvoiceLine : IAuditableEntity, ISoftDeleteEntity, IEntityStatus
    {
        public int SwitchBatchInvoiceLineId { get; set; } // SwitchBatchInvoiceLineId (Primary key)
        public int SwitchBatchInvoiceId { get; set; } // SwitchBatchInvoiceId
        public int? BatchSequenceNumber { get; set; } // BatchSequenceNumber
        public string Quantity { get; set; } // Quantity (length: 255)
        public decimal? TotalInvoiceLineCost { get; set; } // TotalInvoiceLineCost
        public decimal? TotalInvoiceLineVat { get; set; } // TotalInvoiceLineVAT
        public decimal? TotalInvoiceLineCostInclusive { get; set; } // TotalInvoiceLineCostInclusive
        public System.DateTime? ServiceDate { get; set; } // ServiceDate
        public decimal? CreditAmount { get; set; } // CreditAmount
        public string VatCode { get; set; } // VATCode (length: 255)
        public string TariffCode { get; set; } // TariffCode (length: 255)
        public string OtherCode { get; set; } // OtherCode (length: 255)
        public string Description { get; set; } // Description (length: 255)
        public string Icd10Code { get; set; } // ICD10Code (length: 255)
        public string SwitchTransactionNumber { get; set; } // SwitchTransactionNumber (length: 255)
        public string SwitchInternalNumber { get; set; } // SwitchInternalNumber (length: 255)
        public string FileSequenceNumber { get; set; } // FileSequenceNumber (length: 255)
        public string Modifier1 { get; set; } // Modifier1 (length: 255)
        public string Modifier2 { get; set; } // Modifier2 (length: 255)
        public string Modifier3 { get; set; } // Modifier3 (length: 255)
        public string Modifier4 { get; set; } // Modifier4 (length: 255)
        public string DosageDuration { get; set; } // DosageDuration (length: 255)
        public string ServiceProviderTransactionNumber { get; set; } // ServiceProviderTransactionNumber (length: 255)
        public string CptCode { get; set; } // CPTCode (length: 255)
        public int? TreatmentCodeId { get; set; } // TreatmentCodeId
        public bool IsActive { get; set; } // IsActive
        public bool IsDeleted { get; set; } // IsDeleted
        public string CreatedBy { get; set; } // CreatedBy (length: 50)
        public System.DateTime CreatedDate { get; set; } // CreatedDate
        public string ModifiedBy { get; set; } // ModifiedBy (length: 50)
        public System.DateTime ModifiedDate { get; set; } // ModifiedDate
        public System.TimeSpan? ServiceTimeStart { get; set; } // ServiceTimeStart
        public System.TimeSpan? ServiceTimeEnd { get; set; } // ServiceTimeEnd

        // Reverse navigation

        /// <summary>
        /// Child medical_SwitchBatchInvoiceLineUnderAssessReasons where [SwitchBatchInvoiceLineUnderAssessReason].[SwitchBatchInvoiceLineId] point to this entity (FK_SwitchBatchInvoiceLineUnderAssessReason_SwitchBatchInvoiceLine)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<medical_SwitchBatchInvoiceLineUnderAssessReason> SwitchBatchInvoiceLineUnderAssessReasons { get; set; } // SwitchBatchInvoiceLineUnderAssessReason.FK_SwitchBatchInvoiceLineUnderAssessReason_SwitchBatchInvoiceLine

        // Foreign keys

        /// <summary>
        /// Parent medical_SwitchBatchInvoice pointed by [SwitchBatchInvoiceLine].([SwitchBatchInvoiceId]) (FK_SwitchBatchInvoiceLine_SwitchBatchInvoice)
        /// </summary>
        public virtual medical_SwitchBatchInvoice SwitchBatchInvoice { get; set; } // FK_SwitchBatchInvoiceLine_SwitchBatchInvoice

        public medical_SwitchBatchInvoiceLine()
        {
            IsActive = true;
            IsDeleted = false;
            CreatedDate = System.DateTime.Now;
            SwitchBatchInvoiceLineUnderAssessReasons = new System.Collections.Generic.List<medical_SwitchBatchInvoiceLineUnderAssessReason>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
