//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//		
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RMA.Common.Database.Contracts.Repository;
using RMA.Service.Admin.MasterDataManager.Contracts.Enums;

namespace RMA.Service.MediCare.Database.Entities
{
    public partial class medical_Icd10DiagnosticGroupMapping : IAuditableEntity, ISoftDeleteEntity, IEntityStatus
    {
        public int Icd10DiagnosticGroupMappingId { get; set; } // ICD10DiagnosticGroupMappingId (Primary key)
        public int Icd10DiagnosticGroupId { get; set; } // ICD10DiagnosticGroupId
        public int Icd10CodeId { get; set; } // ICD10CodeId
        public bool IsActive { get; set; } // IsActive
        public bool IsDeleted { get; set; } // IsDeleted
        public string CreatedBy { get; set; } // CreatedBy (length: 50)
        public System.DateTime CreatedDate { get; set; } // CreatedDate
        public string ModifiedBy { get; set; } // ModifiedBy (length: 50)
        public System.DateTime ModifiedDate { get; set; } // ModifiedDate

        // Foreign keys

        /// <summary>
        /// Parent medical_Icd10Code pointed by [ICD10DiagnosticGroupMapping].([Icd10CodeId]) (FK_ICD10DiagnosticGroupMapping_ICD10Code)
        /// </summary>
        public virtual medical_Icd10Code Icd10Code { get; set; } // FK_ICD10DiagnosticGroupMapping_ICD10Code

        /// <summary>
        /// Parent medical_Icd10DiagnosticGroup pointed by [ICD10DiagnosticGroupMapping].([Icd10DiagnosticGroupId]) (FK_ICD10DiagnosticGroupMapping_ICD10DiagnosticGroup)
        /// </summary>
        public virtual medical_Icd10DiagnosticGroup Icd10DiagnosticGroup { get; set; } // FK_ICD10DiagnosticGroupMapping_ICD10DiagnosticGroup

        public medical_Icd10DiagnosticGroupMapping()
        {
            IsActive = true;
            IsDeleted = false;
            CreatedDate = System.DateTime.Now;
            ModifiedDate = System.DateTime.Now;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
